export type SuggestedItem = {
  name: string
  path: string
  category: string
}

export const SUGGESTED_OBJECTS: SuggestedItem[] = [

  { name: 'arbre1', path: '/items/arbre/arbre1.gif', category: 'arbre' },
  { name: 'arbre2', path: '/items/arbre/arbre2.gif', category: 'arbre' },
  { name: 'arbre3', path: '/items/arbre/arbre3.gif', category: 'arbre' },
  { name: 'arbre4', path: '/items/arbre/arbre4.gif', category: 'arbre' },
  { name: 'arbre5', path: '/items/arbre/arbre5.gif', category: 'arbre' },
  { name: 'arbre6', path: '/items/arbre/arbre6.gif', category: 'arbre' },
  { name: 'arbre7', path: '/items/arbre/arbre7.gif', category: 'arbre' },
  { name: 'arbre8', path: '/items/arbre/arbre8.gif', category: 'arbre' },

  // Arme
  { name: 'arme1', path: '/items/arme/arme1.png', category: 'arme' },
  { name: 'arme2', path: '/items/arme/arme2.png', category: 'arme' },
  { name: 'arme3', path: '/items/arme/arme3.png', category: 'arme' },
  { name: 'arme4', path: '/items/arme/arme4.png', category: 'arme' },
  { name: 'arme5', path: '/items/arme/arme5.png', category: 'arme' },
  { name: 'arme6', path: '/items/arme/arme6.png', category: 'arme' },
  { name: 'arme7', path: '/items/arme/arme7.png', category: 'arme' },
  { name: 'arme8', path: '/items/arme/arme8.png', category: 'arme' },
  { name: 'arme9', path: '/items/arme/arme9.png', category: 'arme' },
  { name: 'arme10', path: '/items/arme/arme10.png', category: 'arme' },
  { name: 'arme11', path: '/items/arme/arme11.png', category: 'arme' },

  // Armure
  { name: 'armure1', path: '/items/armure/armure1.png', category: 'armure' },
  { name: 'armure2', path: '/items/armure/armure2.png', category: 'armure' },
  { name: 'armure3', path: '/items/armure/armure3.png', category: 'armure' },
  { name: 'armure4', path: '/items/armure/armure4.png', category: 'armure' },
  { name: 'armure5', path: '/items/armure/armure5.png', category: 'armure' },
  { name: 'armure6', path: '/items/armure/armure6.png', category: 'armure' },
  { name: 'armure7', path: '/items/armure/armure7.png', category: 'armure' },
  { name: 'armure8', path: '/items/armure/armure8.png', category: 'armure' },
  { name: 'armure9', path: '/items/armure/armure9.png', category: 'armure' },
  { name: 'armure10', path: '/items/armure/armure10.png', category: 'armure' },

  // Bag
  { name: 'bag1', path: '/items/bag/bag1.png', category: 'bag' },
  { name: 'bag2', path: '/items/bag/bag2.png', category: 'bag' },
  { name: 'bag3', path: '/items/bag/bag3.png', category: 'bag' },
  { name: 'bag4', path: '/items/bag/bag4.png', category: 'bag' },
  { name: 'bag5', path: '/items/bag/bag5.png', category: 'bag' },
  { name: 'bag6', path: '/items/bag/bag6.png', category: 'bag' },
  { name: 'bag7', path: '/items/bag/bag7.png', category: 'bag' },
  { name: 'bag8', path: '/items/bag/bag8.png', category: 'bag' },
  { name: 'bag9', path: '/items/bag/bag9.png', category: 'bag' },
  { name: 'bag10', path: '/items/bag/bag10.png', category: 'bag' },
  { name: 'bag11', path: '/items/bag/bag11.png', category: 'bag' },
  { name: 'bag12', path: '/items/bag/bag12.png', category: 'bag' },
  { name: 'bag13', path: '/items/bag/bag13.png', category: 'bag' },
  { name: 'bag14', path: '/items/bag/bag14.png', category: 'bag' },
  { name: 'bag15', path: '/items/bag/bag15.png', category: 'bag' },
  { name: 'bag16', path: '/items/bag/bag16.png', category: 'bag' },
  { name: 'bag17', path: '/items/bag/bag17.png', category: 'bag' },
  { name: 'bag18', path: '/items/bag/bag18.png', category: 'bag' },
  { name: 'bag19', path: '/items/bag/bag19.png', category: 'bag' },
  { name: 'bag20', path: '/items/bag/bag20.png', category: 'bag' },
  { name: 'bag21', path: '/items/bag/bag21.png', category: 'bag' },
  { name: 'bag22', path: '/items/bag/bag22.png', category: 'bag' },
  { name: 'bag23', path: '/items/bag/bag23.png', category: 'bag' },
  { name: 'bag24', path: '/items/bag/bag24.png', category: 'bag' },
  { name: 'bag25', path: '/items/bag/bag25.png', category: 'bag' },
  { name: 'bag26', path: '/items/bag/bag26.png', category: 'bag' },
  { name: 'bag27', path: '/items/bag/bag27.png', category: 'bag' },
  { name: 'bag28', path: '/items/bag/bag28.png', category: 'bag' },
  { name: 'bag29', path: '/items/bag/bag29.png', category: 'bag' },
  { name: 'bag30', path: '/items/bag/bag30.png', category: 'bag' },
  { name: 'bag31', path: '/items/bag/bag31.png', category: 'bag' },
  { name: 'bag32', path: '/items/bag/bag32.png', category: 'bag' },

  // Barrel
  { name: 'barrel1', path: '/items/barrel/barrel1.png', category: 'barrel' },
  { name: 'barrel2', path: '/items/barrel/barrel2.png', category: 'barrel' },
  { name: 'barrel3', path: '/items/barrel/barrel3.png', category: 'barrel' },
  { name: 'barrel4', path: '/items/barrel/barrel4.png', category: 'barrel' },
  { name: 'barrel5', path: '/items/barrel/barrel5.png', category: 'barrel' },
  { name: 'barrel6', path: '/items/barrel/barrel6.png', category: 'barrel' },
  { name: 'barrel7', path: '/items/barrel/barrel7.png', category: 'barrel' },
  { name: 'barrel8', path: '/items/barrel/barrel8.png', category: 'barrel' },

  // Book
  { name: 'book1', path: '/items/book/book1.png', category: 'book' },
  { name: 'book2', path: '/items/book/book2.png', category: 'book' },
  { name: 'book3', path: '/items/book/book3.png', category: 'book' },
  { name: 'book4', path: '/items/book/book4.png', category: 'book' },
  { name: 'book5', path: '/items/book/book5.png', category: 'book' },
  { name: 'book6', path: '/items/book/book6.png', category: 'book' },
  { name: 'book7', path: '/items/book/book7.png', category: 'book' },
  { name: 'book8', path: '/items/book/book8.png', category: 'book' },

  // Chest
  { name: 'chest1', path: '/items/chest/chest1.png', category: 'chest' },
  { name: 'chest2', path: '/items/chest/chest2.png', category: 'chest' },
  { name: 'chest3', path: '/items/chest/chest3.png', category: 'chest' },
  { name: 'chest4', path: '/items/chest/chest4.png', category: 'chest' },
  { name: 'chest5', path: '/items/chest/chest5.png', category: 'chest' },
  { name: 'chest6', path: '/items/chest/chest6.png', category: 'chest' },
  { name: 'chest7', path: '/items/chest/chest7.png', category: 'chest' },
  { name: 'chest8', path: '/items/chest/chest8.png', category: 'chest' },
  { name: 'chest9', path: '/items/chest/chest9.png', category: 'chest' },
  { name: 'chest10', path: '/items/chest/chest10.png', category: 'chest' },
  { name: 'chest11', path: '/items/chest/chest11.png', category: 'chest' },
  { name: 'chest12', path: '/items/chest/chest12.png', category: 'chest' },
  { name: 'chest13', path: '/items/chest/chest13.png', category: 'chest' },
  { name: 'chest14', path: '/items/chest/chest14.png', category: 'chest' },

  // Decorations
  { name: 'decoration1', path: '/items/decorations/decoration1.png', category: 'decorations' },
  { name: 'decoration2', path: '/items/decorations/decoration2.png', category: 'decorations' },
  { name: 'decoration3', path: '/items/decorations/decoration3.png', category: 'decorations' },
  { name: 'decoration4', path: '/items/decorations/decoration4.png', category: 'decorations' },
  { name: 'decoration5', path: '/items/decorations/decoration5.png', category: 'decorations' },
  { name: 'decoration6', path: '/items/decorations/decoration6.png', category: 'decorations' },
  { name: 'decoration7', path: '/items/decorations/decoration7.png', category: 'decorations' },
  { name: 'decoration8', path: '/items/decorations/decoration8.png', category: 'decorations' },
  { name: 'decoration9', path: '/items/decorations/decoration9.png', category: 'decorations' },
  { name: 'decoration10', path: '/items/decorations/decoration10.png', category: 'decorations' },
  { name: 'decoration11', path: '/items/decorations/decoration11.png', category: 'decorations' },
  { name: 'decoration12', path: '/items/decorations/decoration12.png', category: 'decorations' },
  { name: 'decoration13', path: '/items/decorations/decoration13.png', category: 'decorations' },
  { name: 'decoration14', path: '/items/decorations/decoration14.png', category: 'decorations' },
  { name: 'decoration15', path: '/items/decorations/decoration15.png', category: 'decorations' },
  { name: 'decoration16', path: '/items/decorations/decoration16.png', category: 'decorations' },
  { name: 'decoration17', path: '/items/decorations/decoration17.png', category: 'decorations' },
  { name: 'decoration18', path: '/items/decorations/decoration18.png', category: 'decorations' },
  { name: 'decoration19', path: '/items/decorations/decoration19.png', category: 'decorations' },
  { name: 'decoration20', path: '/items/decorations/decoration20.png', category: 'decorations' },

  { name: 'feu1', path: '/items/feu/feu1.gif', category: 'feu' },

  // Gem
  { name: 'gem1', path: '/items/gem/gem1.png', category: 'gem' },
  { name: 'gem2', path: '/items/gem/gem2.png', category: 'gem' },
  { name: 'gem3', path: '/items/gem/gem3.png', category: 'gem' },
  { name: 'gem4', path: '/items/gem/gem4.png', category: 'gem' },
  { name: 'gem5', path: '/items/gem/gem5.png', category: 'gem' },
  { name: 'gem6', path: '/items/gem/gem6.png', category: 'gem' },
  { name: 'gem7', path: '/items/gem/gem7.png', category: 'gem' },
  { name: 'gem8', path: '/items/gem/gem8.png', category: 'gem' },
  { name: 'gem9', path: '/items/gem/gem9.png', category: 'gem' },
  { name: 'gem10', path: '/items/gem/gem10.png', category: 'gem' },
  { name: 'gem11', path: '/items/gem/gem11.png', category: 'gem' },
  { name: 'gem12', path: '/items/gem/gem12.png', category: 'gem' },
  { name: 'gem13', path: '/items/gem/gem13.png', category: 'gem' },
  { name: 'gem14', path: '/items/gem/gem14.png', category: 'gem' },
  { name: 'gem15', path: '/items/gem/gem15.png', category: 'gem' },
  { name: 'gem16', path: '/items/gem/gem16.png', category: 'gem' },

  // Keys
  { name: 'key1', path: '/items/keys/key1.png', category: 'keys' },
  { name: 'key2', path: '/items/keys/key2.png', category: 'keys' },
  { name: 'key3', path: '/items/keys/key3.png', category: 'keys' },
  { name: 'key4', path: '/items/keys/key4.png', category: 'keys' },

  // Ladder
  { name: 'ladder1', path: '/items/ladder/ladder1.png', category: 'ladder' },
  { name: 'ladder2', path: '/items/ladder/ladder2.png', category: 'ladder' },
  { name: 'ladder3', path: '/items/ladder/ladder3.png', category: 'ladder' },
  { name: 'ladder4', path: '/items/ladder/ladder4.png', category: 'ladder' },

  // Potions
  { name: 'potion1', path: '/items/potions/potion1.png', category: 'potions' },
  { name: 'potion2', path: '/items/potions/potion2.png', category: 'potions' },
  { name: 'potion3', path: '/items/potions/potion3.png', category: 'potions' },
  { name: 'potion4', path: '/items/potions/potion4.png', category: 'potions' },
  { name: 'potion5', path: '/items/potions/potion5.png', category: 'potions' },
  { name: 'potion6', path: '/items/potions/potion6.png', category: 'potions' },
  { name: 'potion7', path: '/items/potions/potion7.png', category: 'potions' },
  { name: 'potion8', path: '/items/potions/potion8.png', category: 'potions' },
  { name: 'potion9', path: '/items/potions/potion9.png', category: 'potions' },
  { name: 'potion10', path: '/items/potions/potion10.png', category: 'potions' },
  { name: 'potion11', path: '/items/potions/potion11.png', category: 'potions' },
  { name: 'potion12', path: '/items/potions/potion12.png', category: 'potions' },
  { name: 'potion13', path: '/items/potions/potion13.png', category: 'potions' },
  { name: 'potion14', path: '/items/potions/potion14.png', category: 'potions' },
  { name: 'potion15', path: '/items/potions/potion15.png', category: 'potions' },
  { name: 'potion16', path: '/items/potions/potion16.png', category: 'potions' },
  { name: 'potion17', path: '/items/potions/potion17.png', category: 'potions' },
  { name: 'potion18', path: '/items/potions/potion18.png', category: 'potions' },
  { name: 'potion19', path: '/items/potions/potion19.png', category: 'potions' },
  { name: 'potion20', path: '/items/potions/potion20.png', category: 'potions' },
  { name: 'potion21', path: '/items/potions/potion21.png', category: 'potions' },
  { name: 'potion22', path: '/items/potions/potion22.png', category: 'potions' },
  { name: 'potion23', path: '/items/potions/potion23.png', category: 'potions' },

]

export const ITEM_CATEGORIES = [
  { id: 'all', label: 'Tout' },
  { id: 'arbre', label: 'Arbre' },
  { id: 'arme', label: 'Armes' },
  { id: 'armure', label: 'Armures' },
  { id: 'bag', label: 'Sacs' },
  { id: 'barrel', label: 'Tonneaux' },
  { id: 'book', label: 'Livres' },
  { id: 'chest', label: 'Coffres' },
  { id: 'decorations', label: 'Déco' },
  { id: 'feu', label: 'Feu' },
  { id: 'gem', label: 'Gemmes' },
  { id: 'keys', label: 'Clés' },
  { id: 'ladder', label: 'Échelles' },
  { id: 'potions', label: 'Potions' },

]

