---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-billing-owner
  namespace: data
spec:
  encryptedData:
    password: AgBglRirlt8Sml8c8SAv9tlrQQ4Fwp4PwfjMsPMiIQpwgrEWIkS1aJqRpxLmYFRabqHmCNkPHVV3Mtw718z7fS3wDdEA2mowVvIMNvZJPyV8MiwzA5xvQ2PmGBE5RABF+5Wgi3ddFCTCdgS/wGE5dIvPYB5EjvM4yplwaa4TFjxw0cJ/qPVtqufstmbXyWbQ+MLfnstSNemRLR/lmfZsOL3eKDVZ0JnlVPQ+2AzRuWtbEoqAZC77NbTdkZunGiYhrh37xSYzpBuc1ZrDyrECRDCNCJH09ko3BfyB8Gt7JFsFOXPDz2SjK4Ez/1HsChueFKYLBuBZmVj2E0iZJaHcI54Sxzgg1oUgIjeTBy9hxaHFSctMPNLeltqfnMQxK3VfPnwS+NRMfUVGqmlWcTX6w9FGl/emWsB0B9S/xqRLkB69i54veIcTePJr25rwIB6XLXtR/kCcFzx/EAKbnQ/Egq90Bcv33OvmATZRczrv+LElGKZJRwLzlz3ZQmT/Zl4Drhf+vRqJV7Bex1aUTeYwp/L/5K68aT6dM1c3w4MZXI/N0p7JrizTZ1vQQx1Z9J1OtQxcwYQEOpuc2KsyvZ+kjRLbGGGLyRuNGHZ0ZEdi8INy41hczoNrA8vn5HPgNtXtTS3gkvdZ9LIelVqcckI9tpJO6f9mDGVLPLf7sIRLswpxrcZWaxcp5e+bCzgCaGXkODgua84e5+xcsVYueZMCD3UKJ7AkKyke8CAaJf2Zyul53P/EjCj9z5LV32J6TO05tAA8qZefMFNUZ5ui8kQu7/kFbQ==
    username: AgC1Z4LHyBWV0w8rp+p8hqUQ1CBnGGSKRd0IK7mQhRYi2ANE7GjosjnYotqKNae4ZwnKg49iMJPYSfSE1yPDg+4iu2gWbHf6TFTF4nSSkD2avtJl0I1dUPriO38ZIGIqO+1t1ppM35R7STOyeF4XHLeqGZ3vwM6vFiuzOeDsCkF7q0Dyo/I9N09/S0z9xof+fWZ0rLC1uMeZOisAlRRlUHWuhU8ebfz9jQw6Kw9rvG8A+9gyUcQgbB90vsty7si4XLYHbVXuMe86HvakNPpHyjUb7Ul0C7W+WT4JbtEM2746RF64xQHA1KYPlq0SbPovAdN8x+kaWBDkmkA+tlZROryieH+mSBwPuj40HdUG1L3Dw/yhwvF869kXlo6o0/3uhmn64aczKIT2YZflJ0uPuQbHE1B5IBhiwc5blH5SPfsBdA6LbZ5aXarwsclSkDBeb/gKHE41trF+JnPNUXAUB4oeU1qwxKCB60MasHO4MzKiLIhGaHpWBtYzan2bFw59sURvsch26KCTL8ycLjsca7OIWjdYykkVI8dwpFwuP1N1S5TPK+UVpImPCCYCtSyEQ53D/SkdPokQrQEgBgbbGEtn+YzlkX3PFqiq2LBplj/jMn3WpNLWMPhhy5pWJnI7FQ+WabBvrRZa10CIWywhB3EqvEr4pwtir2LcioDgQVeA3qLD7xyC6XpTo4wKYEd6nDZpHvUj6Ka18AJ4zVlD
  template:
    metadata:
      name: pg-billing-owner
      namespace: data
    type: kubernetes.io/basic-auth
