---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-campaign-owner
  namespace: data
spec:
  encryptedData:
    password: AgBnKnnDnFZc6KFvcF9r0P/3RmZ9hOal+bRUJ3/sxCYVej0fEg4ovEg4P77xQL/Ta//ertprdFKn8KEsQbwku+WcYEtnoKd3p+6wcPaEGErjnqXKaGbWctHoTE6PfG7uPk3+Zx+Ug7xMdOpBT7Da8g0JQaOlHquV0s0G0dYHaZw2dOQFShRr5EJU31dyrKGbo3imKHzfWtLXNN1WqZGLlIrTig+AlXn3PgHwCNtnOlgxMcQrbpuxrua5j8Yfn2g8wbc9uAzSE8J0iYT1jU1+xOTB2jxAvSF3Acwdw6wQ9d6a9xIB6MVWpyC2LSlT45uj6+j8Bg+5NMV3bxG63tmbQYW3RSioI6vB9V9Li8W4gbN72buKYwFMwbRTXpiO3OhRlV/lIiTCpoCuxGcI0LCeWMX0PeCDhgKLxjAeQl7PE+NPX7yMoseDhmMfPb3ZYEhznGq9u69b/lM0YPF4R/Ws9DRrc3v2w83WRolFFO32VGRHtLyFG5rADLyzzUO0zyZhHY6QBabtdnITD8oFA39EoyU8f3bxXSXpzXZiJQS6YiuH5UMFYXse3gC8DT0YGyA3wn8T9SnhsQrLlbuM27iMu9xY6bgdCPqEztKJjbq0WRRsPNmw3GNnw3gAerLPBNh/2hWDNoW8YZsVLcbOvT2JiEoprshbN9J2RaviCTGytUbMZjmC1z+q3peUn5ppGeABVRDRvuGTHDsvucaIVct52EX1ha2we5PFFOyKr/PFmLffPNlxinsUOcKn1XpLte/VswlXhykW8ihQLspE7MxlybJhbg==
    username: AgBFrTA6zmo8BlHrMclxAcKyvTfW3jN56Ke7Q3ExHc9TfMkFLYjwbUwPNz//NVleZ7JpQ3Oj2LRBvigi7bYFVxvfmteGFk4oKeA1+WTM487f8w64EP9EyZLm44MYvOlnQKxY9fi/21ZOSO8r8DCIqgDwgrgs8fCkZLhAFaOdLx121z8ErsjEwApBK5HbWIEvOOKOAx8TDfO8+YRSo7GDftYKOsL58nY7zPCnm6d6krC2MKxqi4O6jNAAIPnMnqe6aTaw9DzieT6iaJcCtTd4bcjMxCZF/trJ8Wi5om7rEV6ZciZUGHn/dIgGkGDgy+hpSDZps7UYyKW8eYYlVB/CieNZb9Ofhu6B88F9vqU1BOYBTBydRanhZuwvLskJF7PFuQfec6g17nTfroijoGUA/YHTRZ29dZwEIGjjn+BK09JQcTFv10SL0JOJDIzfuxUJhqxw/++hMtVW1bQUoJF5rO0VtbJe/Br5oC+g5f3a3dSuGQFk74ZoMahFU9UdZPL4N6oDZh4Wc0iRLM7SqSYeu1Y8nLyBuJyMAbNK3UvP1xUgs3mhfec2DbISydsjTrja8DDPshMFqWReZLtXPtE9MdOQGcKmfc2t06hOmBInzdUrbspY6agkPENByFEbq1bZaMRhspCyS3XPXj4tiEPhOdP/d5l4QoHpq4/u+9mxV8VZGps3CQvNEVv5SPDOxm2N8G7nzGReaGE2So5o/UcDtQ==
  template:
    metadata:
      name: pg-campaign-owner
      namespace: data
    type: kubernetes.io/basic-auth
