---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-audio
  namespace: data
spec:
  encryptedData:
    password: AgAHVk4ZZ+EMLnpYzs4+s9/sxvgGQWTIfaDttCrO3IZfVwBlaLkKZJ4Feh6NV4uptLvfe8YWMDolhxvjNWcRorB3xbYzwt1l/kCb6g/YDznRvKId+G4x7CmmsHL1IO3d7QDHi/YCP4WVvTfdKDkpkimz7QNLWfM39+HlxJpdBouZ1i8gAcKsHFTRpohGNHysfnr6FxlZEG5MWahfEnWbjSUW7JoXHxe2iC10dafgDI6c6vPmL5wOZ9ykOKFYPcHHmglGaaZZ3rMH66rYrvZT8fZII7d89SDXU2qM6ZCnu8M4HfBuvvYgEulAaaNlixyfrqRTEzGlMJedmq6B17E35IeFU3eYa7yRAThsu8vK0+n5acRqKdpLh2paZlqWZEw1SrN4KVAtsMRFzi9RJkFyJs07/vJVSLfwQh3qBVLBelGB7b/S8sBHGrl1a2WbV2QbtKfXMLVoMRBu/AK/dXYQgRcRz05PTgOkiEv/xENkBvJDLkw8Qjn7O5Y+tiRbKfoKrlhybwVQJdoM/ZMhupiqsGSu5dxTFZS4zoQnAk3hpuT7gInkHE3XooNwC8zod+BUMYfWp8y/aAVAWgqfhiRmrlhyt5aM+ykYP7F5JJvHBsWg652ldyfdUxxkt1DGBD4g1DYI8TjBGEgWMXEdfDbxEouJ0u3B9qPA8ZPaKzsbzCT15ZiFiEsxxSSeGbG+llU0vquD1Iajrha+BD1suBagUS+2XHVMiDGaD+ybGUgKOqme6ji/CNpIz1Rg/spMqx8FCZ36cy8lvCJHFHgA6TkONbsWEw==
    username: AgCWekJrh6o6aggLOoJyGnVqdXZdbtxCknJHHwsnX7ZArKMXH79B/MOMEhX3g11iV7kW50InMzy/+UxQXu/hYJRBAM1lmbCYkxghZ90DWYWCIl5/zZpvqKfTM5KJnGte8xcyTExdHb8hdqyrBzcdHwUnlSaU8WooT7sieU2gXATbyQ8gnKaIwZwSL1iBYEyacn6Yz/95ZedarS/GLpEyWl+IvrJUEyGGHe4lS7gh6XXoteBXAEalCrBRE7/3f6XTZ06HO+mUTb+Iu9xDjgCqGcak0XSpckE3IWt8DwMIttUt6kH++K9N/kFoDvZb7r9uD2frvtZ4hGHzE3oTP6XONNAtPqBq2pUXWPE4lysRL/+lC5vnKW+GW2x7S+X3DHKz9GGG5qr+E8xvJzqdw+42Qb2SxNo6Hilkpd8yjqyPvXW6etfCZfNa+marOhlvzDNkX+0LZHG0V4r7OIm1SrZc3WAZyjYQkvQhYTtHqrwwNjY/YLdvdEp4/Qy25IFXS/D/rRNZfZXQVXQif2nPnTKr5h0MsxKULL/tntYXJnFe9/Os7Qrvp0Od/AjejEaPXwtqf2aC9lM+jug7O/zeHFqElmEufEfvZSUJrHiaMRZY/aQ/pwSOz1CSvD7c/RApzOKXsYQtdAjX0vwajZ0Mp8pjqdS/B//ymUOU+aOAC2+7iMIX9hJSzPtcmvWkWfzIVhMnh6iDRWyf/01YKu8=
  template:
    metadata:
      name: pg-audio
      namespace: data
    type: kubernetes.io/basic-auth
