---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-history-owner
  namespace: data
spec:
  encryptedData:
    password: AgAUNw1mgecuYbSxZT+F4QlUfoqNEwRz93dT4q1AUu6BW29Y2xhGLWMvhq9WRAzuiYha94cbDCajvsQ9zfiTR8O7sqrGGRIqi9YG838gLoek05d1UfZJ++BZIE0cA8eVSCK7dYdbBtKfa+1PbIxbyXbfTlmSnZto+VEbDWHMdDPI/gvQYlc+aIBpq53t+uR+cPykYLnuFYaDe5y12oyjalCFtx4ZskZ0A5Eu5vX5oXMvsDAoSv26OxseRHNUopEbf2xMDYEAveXW1ydbh8I1Rmcyw8Cz5cudTe0gYqmIP6QiNk1PlbAXkCuH4L7KD7WsPNPGKxnoQUX79UbAQjKzfk+qNrTG3dwma/TF+8YExAf5Fv4jB4gkLopwzBt34gnV4pLI3pGiMb/exVSsif8kqz8dD3u2nSAcHVc6K45QPmQtLj4YvBoGopmEzUi0xgfK38Hm/OpuKQcyRr6vvwINBd82XJokFIGh+l23coZJ1y+ZDq3JIqGk0F5BlyNvnO9477XlXPmQmd+ynHGH6TDqdEqCp7mHicu4/+SzEhTDrYsq5l3FE6GY83FJs08vOTAxosZ/pHb3vm7OVlnIcUb43M5msBlBSvyxYzKqAXjzcHeyMLWcsONUWzetYEQrZRwXjdOD4yUtCCbxBdBN75XdpBUsSjl9kgU2LKIhgj8IqKw5vjiyaL9xkwgbNhPisYdUyjkRAtpHZExeqgMpyzXczVl1X2xAI2wT7mlXqMvKI55kqiG9ILgGIiId1IM9lDotcSx5D7/BSOiFItdXUsFyP0GFPw==
    username: AgCbtc1P5tThuEdAHSQIJUBU1MXHC/MSZ5eLxrBcaLjwODrvh1/5b5H+lIuPnThq30UXwKgGTSVYih+tuexwrK4dRyr8oFECcEg1pK7JfnBBC+MxoPlW4T5Gtf2kS6qHO17rmjfNzF2GDfKgftYRLrKxQaXX102stnWx4TroNpcYsOfDtNFtBoPxlLNYMF66X6KNb/ny5tTGmITJKU2CCZT7qJxGmvkl0CmDW1T0CNOy2LjggbiqXqVEvEo2pRgrBfessYpZ01ZKwJggaKmrcTNvaRRmAl7B8mNz3qY2U+C3tLw6dp8iqG/KFknCQvgxbHReM/GgPklb6j2h8XQMSNUyIMxsUJoMRLLCLqhejFRf6jWGHvIxUO1HnU+Jo/gy4vm+x/jJjDBWlVvhPs+euY2ovmpIkCbeYyn9WnR+x8BtaZYIKxXt13l64LWqxeE9piOzhPIxpqM/+N/p2315g44TQ/rRcPFFNlZg+Tlgi65jwZTt/RBm52FPaBNIqmKZJxR93JYCfwmWRu9tQ01rrpiC1RBDTvtMxW9S4BBwu0zaSwTPPU/J5m22YqObLbw+LjmOz+SaWKNSy/ASA0saJeU0HIYpA7cTeya4SqI9QIPmXzWuM/t5/iyKo+F3Lo7RLUvPPTYzrm4vHJtGM80sKTJO1qOJHe3A0H3sybSp+/Za/c12ygKHhIlmo1x2etsMiQkXII8t3//xV3stSysP
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-history-owner
      namespace: data
    type: kubernetes.io/basic-auth
