---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-dice-owner
  namespace: data
spec:
  encryptedData:
    password: AgBWdCeyDRC0Unm6fsmJkgtEr0OjlyyMnEurLgAQ1M8mF/vyC01qdyuuoXJxuL3In+tv1QJS732jOSQgIUSBr6MdUgauX0ot8KiEMCKIP4c5rkHw1ZtlQiO6/McjcC7Ihou2CZyt8crfHs6orGMNamN3++R0VoyYmjx6H9/prXYDqY9nvOB8UxOhLhhpW0lP32p8zsmpbnnf8tUgE2ReDVmMCy7uKnoCjyzXosGi8yCnFcQ5H6Gp8fumluJ+GifaHZ11CPRuSnNdO7Nccvdfgx/hrZDSHZ8hErqvzNGVBBXyQWtCbJ9kmEghFobWJhmNR0hvxUFsptFlRe4y9JewMJSbGs9LNjcxdlmnC0RCTZbzF07FFkC9Mn3Cyfet3Fh72C/BTCxkoWMODdI+QxVMWfM4ver4gvRM04h6bSDztDySWTuRg+rj8Me1L2FfH2K/+qnqWetBwdv6tDMRx2Jf0wLDZ/dpvJHLUEr4EAtCOXY4dwe4+wollRxBsLwuzdpklMmqpgG50+wlrOGq9zSPTTnOIoiwKyXcefW6cM5kuTyTIEp7SSJufP2h8op2OB28rGa7GmGDMhfAV0Rhd+My1oJ1nIceu0rRk4JtqWhytpuoCds5KSlSvtZzppr73ahcANh5138Lm6Yb6vBCd19+QedKU1axbYv7HiCgTuNA0J+jww/xQ7wVOoT4bxhaHf27vb20aXilvvQdyXHuJVifsDHYBFy3h+sXqNPjcSolVi34mBjM7DBxLMUL1OcJHN6Auk0sUNaHiEbLeqftx9/yZaPc0w==
    username: AgCW3+OZhmFQjGHca8hmAHN0PFSHW/S4+OXAOWVhzoNHVZBbJhhzhhX1QQttCuDwlv79X9gtpK3vTy4QRGnndqN21vQqw8dhDwFsW4CjBcYR/aKUyIWo4FpVnLHO4201j2RYCLrs8oSWVN6q2z3HYl/KG0uH8bQsmmcZh8H1Z4HhvwX14k9HjISOxQHtWjZGViXzPFMuKJKZsDiUubWJY3QkR7E5GRX7LpWv3uqo7ii+0LZOBRkH7Afq2Lo9SORVNzFvNQTWW15k/0eoHiaPDh6gazW+JDHmqv+cuox1+LEkFOpv+Ssq4eg5cXEnZfEuJwlTo5mRaGOpfK+dO+DM/uCNVAM++wadh+8yH794UhBjctpaOD1zdXJsTeQiqTkgBGzRw2ib6S5H7fCe/FBkeG6EkTviUmaHmKcuJmFQ/owIyVP1RrSP0zttQJ5lF4NuJLYpdJ2Vky7S5905VweTFfzWiLWj9Q5aknI/1l3gSGQ6TUc6j7Cvt0Jc59eJfLR551v8+9kH0fB1P7t153UMLQL3idJZKlPiklE9L5ky84Lthom4HeBhasRJQ/T81zesQdSPoSkzmjiTE8vYbPSJct66ZaoFnZWBrvEbl+p5yoU4zoDFJMHueNtOfqomA2uqkJwWSy62+4hf6DEEQCaqx3FmQFQU7E/4JoKPjCrIAOzYy4xcfUfnyaBNWttkfCIKq0tLB/WhGGikPkqj
  template:
    metadata:
      name: pg-dice-owner
      namespace: data
    type: kubernetes.io/basic-auth
