---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-identity-owner
  namespace: data
spec:
  encryptedData:
    password: AgBhjwlez04a9LAQx5gmOC6r9GRFOWo8dDel3oNSyV4KAjKhpUzCO+9wRIFGeqGd7dCOI9BiLIN+HBeeGIQhXrSR51IK5TqbXGb8Yl7pjARUfsUyX0V2pZ59HgIfu75x+SilggtsxSLQzpvdGWxE2hDmXGOLZ0h5Hg6m2p9SoYrBBfrVJ1icZ3Xy+v7ZNG5b5mHWILzJSc9bbl15cUgpfaEEFgG8Rvb2EBNswGdKY5lp6d49Yr4OoTp05AaXbiAc6J+jSk+jA5B2VKOFfhuN0K4WHwhW2aBvt8d5hCMqnMicCsh2S8gaqFO6xTHxJB1BnUx5bCpXorNfVcNBd5wnEY+CkxwtnV/OStBojZYMgadrAe0W/8NiLi7z97ii4VheKzGk7yl7YqRpcHH+CuyzAonDdLifn6GXZ3D2b/R4kous+Ah5dJXzXsBwJ5B9f6tQNDx5UfffONp5oXdcJQm7ffVdaVfcHnhxecjSW5DlBu5Ni8BKRRPQhWcO7WZY6BGdksb2GZFiF01y/toMQOy6Jbry14WwoFE3sJdV0OWLIhoTX7Swxu70kAnfo3Aic0FupyNBJYEUGVasZADxmj/g6pUQSY6YNunaTtmZS2LE7H6KoMYRmLjP7zZRtu7xgySt6JPLmm1EFU4KrN8ARGFAQYI8gz7BvfKZgeeuPrt5Ezl0EV93/+M99Y1g2YPnBfzCYj7Nt28TxEFE9n/CWBd5vkmDWXCiwQfODKtrafIfZdNYjSeVvjTHCr/fwaYlkPd/HsjEFFp9Qo4vrng+xME6sjjvtw==
    username: AgAaroNZk2i2++uyoEDx7yPBk3/JWrZ4gcX38PnUFB76qHXq1btKEppydYAZEl7l15o/6gCKlUwyIzJ8QqE415qCvrlhe3jIFNbGWied1nVIXbKUjpkYrnZ4KrS7V9ZQlndHJ74Zq63LmF3/mzgG2rG/DjuXFoOWrBfZiXYKR0gSzPAt3SI8Awqdgjc4kP1SNvwlUTz2nksvmsqNSmIb0Gd6Sk1N8ShUHicAcuFu1beI2s38bq6bQE5yN4Mn/IqFZ54jcq4lcGbLocV6XLLMqj0vpnr8hlKpGHpDn95z8ngzr6osHDvLP7hNl7d3ejI7vjefziocRZ34oftS8Hn2JhWHBxaHlUoosCiDI/yupd+girNMCb1yDWt/08N73H2nLgEMJnakdOuBL/PgrqyQqCHKkmiDaof/YREb+C0ikBgBRbuFyKeGxUbv2mTs4K5NE9b9byVnZKT+ovWFlmdj8HSmgl3xihfwhqVhw6nk8pq05d5+RyuX6ln4/t2GAabrOVqq4/8mp3qhqXXFVqDuB9l+IFs80/vNiv8QpOhwSu44QTNcfcLoDENVlkjlt1FT61mRMppkXPmenZuu2UdZLKP3gBByxghey4MTWVkZ2JYb309poSAScHWUypPQB5Fl9Skc6KwabYuaeOF/8T2MTDoxaKcGfPWeW2e04T+JZzV8qCt81SuywH04qfnG3HWnj4aL+MTjb5z2XsrrJykmXw==
  template:
    metadata:
      name: pg-identity-owner
      namespace: data
    type: kubernetes.io/basic-auth
