---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-characters-owner
  namespace: data
spec:
  encryptedData:
    password: AgAE7rBJMPdoV/hKymQw6Rq4RdTt/RAcJIQEQ9k62wibDFBS/B9JqaIkRyeFlplMQpln5Fxd32Mu0zLdIKIbCDoKDTkSVhnOIIUcc4CHHe1Bzd1uJHtcBMDHGeYAgRXbjnvY4R3xYmpdLrnLUZ3QxDwC+c1aH25EVI+/zEGlNYIwdPdcnv1K/K8AN19Ajy1FhNVtxhnBWcBObZKUR7nLoQhf0ODHWT2nm6ibxcGuhrZRcAz9czZ6Gt1N+H3+q1dIaP7UOgN5oCehbo7KhUHdbezp0GA4RoP/6jAyGgZIpDDDr2GCiCyMtMisTw9O/NkOS+VFjPKd7GMY1mUPHeSEX5tY8U6Ybd39XYgKAXPY9VZ0ePOIBfb45jazs/SGA2VqBIn2/cY1NnMcjt2T28HtGAWrYrR14nArq5F2+voGiZa9iE25qQAlrtxpMsSIrNGX/C0qUStY0P2ENFxxwAMKXmW8fpP94sm0ZepFHgbLBx6zd7MRaN7hduDeWV/pz+tSRzX6rm+U20hRcJs7R5scPdqsMgszySCByn2+jGdDOW5++2Q+YGJygUS+HuxsXgYwef/IzCDMxdcbprxLJLklSPeMCESbYEPEakV8IRC3AVljiFsD/P3XxcQ8U1mipFYqZAoJs3+Jsu9Uk3HCARNcNoWbzQ1navNbm2i6eKcJyJWAxExBYPBaRajfL7moY5EsHyY2Wr87KO2j96snBTsAGqWrBaQZyrIZPSNiFMg8HVbA/CqbOtdQx47Yfb7gmaMCzNvgrFYThQxMM3jCA977eofvqg==
    username: AgC3KYjvc09CY3aQ9n32xMh4m28dpJTB0nDTQKSAt7sl1HGThc+ex9YCGF5IMNxtPu43Ue0HHSAfVBkJkwOww+aov9u7WDldHcO97JBPq5xwZmiJW4m+0K+33+sMjNN5QtGZvMSL0vogNyQouVLZukf4XuoAc6r9jrcHD9cfbxnCehlWKLv9XgIPTVcRiXW7vi0DUfeGnKl7xK/XfeNcW0XrnTXgDr+0nwaGQK12COkGlZBGPYICYK/gVknnKJnAhKLt73pPfCkKELScn3Dm6UbcRloASYT6a12YtrWaW8Rg63q73We0MhCynDUHJOaRw75bNg7P+8E6n/9axkYT6+ANkBTLrpXwXmZCKSxp70DplY6qjyv3kQxFiHOgPv9a2g9iFpNGJgUpo5vjsgdxvCZEPCfcGnMDJdlFIZuDblc0Qn3sMZTG/Sm8UNLQDn8uTzoYFxmlbFDILbHfgnnuTcn9IienlCToEaV9LV6rV49Qvl2H51Nf+P2vOQNZNNqBTYvsXmAnlv6SSQDEGEm00CvQwtHRCcfF89RW5X/2jVqLJVNhtq5bmZLAn77pEWSBJYEUGIAju6AQCfOsR6fshYPiYCyeXnSDdpr0Y4MF8fvKNDFAW2mMhaexCjYaUfx5/G5Z/6qr1E/bJV5NKqyAQXQ394n3KMMNif9HdxRnXycON68dIIqAeQUZBUBykxAu5/jpt5JDCjyJ/0NnRIej/7fJ
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-characters-owner
      namespace: data
    type: kubernetes.io/basic-auth
