---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-wal-r2
  namespace: data
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAx/F2Brfwf+FpCa4AUe1zJLlnN0a5jsPs2nX821h4iTVTUmz9Eap/dQWy2nBlfGtNy1hxUYUuUjOQBfsiKKtHON2LONrLDZCzqjh760RSxfxVzyLzBRKi8bZY+VLsk0N+5fwANJ74pZ1EVCZL4t1i3aaqroTnFvdqZyq2HJUQPI6D/DMvs4CXI+WmL55ab9x/Fe6VirLxJVV4n5krK/SWpTfOZ0APxNHWlRHdYYkbqkZkjFCEC9UdizpZdV4rm7La7FXekhYQNnQq8l57hnZdxisiTVO45kmnFjdyBFdJUPF0t7TnRiZqHq/x42Vb+hgrIzXpYeK/GgSac0u/XnKdDoKqGPrpAAIB/HvzJXKr9145ndrLweDWUgnrEUzdm0kwzXTw89PTGIGcVPhVNKGE8kkD/KtCbkjBY2aP3hO9Y5rU53BQzi8YJWVum4yHWHItkj/lLd1kS9Gydta8hS2le8CffL7xWK2EPkATvuIPnQBcwFpwUgycgk0ztU/evgHNMnjKymK1rqRWj+a2iWTKwmmDbiPhbvSysL8thJZYtf5DADMdOvif/VO+wCJp0jymPRynJXrXTp5CFfxEP3Mk3a3kSM96xKbrF1l4aNzumhsQy4jdfhdUPkbbLI8W//y8BcsYFZxveRD4L0FWdoDq37A/fH7Qm+qKYV4QswIAkrCFnqJ7d4J8ljGK3PubTrYSsFUfEo31WSD4X6u63dt5Hsyo3qB9BJDEVlvneqz3a4w==
    ACCESS_SECRET_KEY: AgCo3Q9L03Ftb6+TcynvxFG0xPjdX18ChdqO6zqILPGI2j0lysAu+j/Es2YawBu/H6STYHbsaKihJyez20VWNwNxnMoYq0963g7uu7zd2+ek58MMxgqFqcrf2mUTKUo3H2LjCyzSCtc7pzEB3a92TK0QUAYChvY6vNvLqWFuT0Ooe2gue0UbjgvLtEUI612/vyMGDuYo4up+Hkv0o7gs+iHSOrMGiuIAunMOX+YNVlb7V+MU1TtkruC3l7lIUYcwZpeY6NZRmY++X+JBM29zCVLAgAMJypQ44/YzYcJm+bpGwqid2CV8vOKX9c1q+xC+KzYGlHCBkgrGY3502YePLqTE/qs3/fgL5p+r2U6P54ovNMBN/Mj0FAA4etUeCudDH2Ig6irARVijGavtBU1LeBIWRy7QcS7PwDpzax6wPIa5QkppE9j9B04PdSrkEwneGaJYeRKIwxykRLaRSS0p2Pgq3bSL3wZe0mtA0nchPIiyMfkIwN+e+MjZPYQXteKdFdUPf+ipWjWfOS3SU3iMnIKungbYFY2vDWJjNQUdmMIOewZEEAsZ6CmV6DHKumE37X/L9XfEYdcfj+WXLUhNU9FcynLbxcsS/XfSQe5dxSwMEY5zDSdonVXBW5pvHaZInGmOWtaZ9nAuLoNDuJHUehAIoXogMcvr6cvyoEke/cBCR74bf9qtX5eokcOr9KqfAsLw4dqUSSoAP644bXxLJm261/5KWj7HV5OTyc93jOQ6SlB3bsO0QpJJFTcTE4xyYY2UalbgQ2LCSqAtqlGqiMut
  template:
    metadata:
      name: pg-wal-r2
      namespace: data
    type: Opaque
