---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-campaign
  namespace: data
spec:
  encryptedData:
    password: AgASAnbACF8U29zr9ldwdqa7sxInzwiFbzomdFajffc18I2jzoAaHC6Yj8YymVf9w25bPEpy5WzoUWYMV7xXb0XLoh3evU/MKh+reqCndUNDvfcS7VJbbfC6yenNEvlMY9avm7OPmXx5cKqXjj1PWnk0xwtCxAisTYKuAgchEAD4iqZ/jQUgvjeON48l8NKduFhUUwrRI0nN27C0VPY0I4mY0Gm3VTVubczEoIGDpfrypZM4uhoD/yblbBLD5XYiMoPU0DLvzLirtzDlsyiY9OO2W2ZM9+HS44qFjWOg4+nq6qf4flcsCIiW2HQzBTf4Dq7+GjsTzOqb/314+aGR0aL3sAbYQfrtKgAlEBETsnI6ghc4dIXwP4l4FXnDEhp8JGvTVVBSvekvIZPpaKPSYu+nXPAqADsfmMP3dZ9QMWWPsLEGSSx1b90+kozNUvgiVx/NUWDK3w2JJnDLD249b2K4mK3AIaWIoIuLPX7sswkLkiezQTJLfE3woIQGLc3UuvFY2xAHdcF4Kk5c9SGFqBBo7vLJl6LThM3iA/ydVQMu25/oVM/Ov63AxpsY/Gi2J5D8p3Bz5k+0iR2apFPqlNkT+4mFyRx/VDEhXdUGH4nP4NIYFbQN74g2MT5VKyyCAoDCYRKVqKyfyaqI7jEMOO5J+cP3Sd+yHKsTg0E7+bHJHPPUfKC0vBViDd9eq+WOG7rgNbYB/zE/9B180kW1k2AspbH7qGWjyVIfJhCaEo8gvgbQAs7C6koldmthsifUEVM09ua12SwnUKeVQnqRMDAnkQ==
    username: AgC6Jjhy27HHdCMtAoNDLCw4cN7e1VRR/fcJOVCZO9ckC5esikru5lFwN4GoYFHxy5JUodP5m2CNbcZHMH2Pn79Jzal3vgv/UNAmLerNcYcN29bSH/l3XWCgkJDe1XrFLS50XMAJJM4XzkTLrMuz3W2ea49xrLtomacnZAkOTOy2SVQY5KiPcagQddb0EyGVfSTSCkz3joHX1Yt+goOGLg2Ryx9pokLc3/UP09656P8w5Ix18kS4P0tQQU1DFnr34JR6cajzp2ZcEZiot/rQEiAi30dU1R5GmDt1dwe3iSe8wiU+SP7h9qTWtfVsAnBqDLyjQPE4XjQXDdugPulfP1DkvmwYvWj2sEjfeNCXiFhxNDPogrrW5JIgrGi0o+iDh7B3pruh9bDpOR5AWNwuUq074ntQ+aL5LcfvPjpmAB8Hw9N6bAstnN99Pt4nA5X2FkGeS/4E3GZTuF4O0bLDLUTt/SivlMa+XRkUKLgcRid8jHuCRDpgKEvHqCaXu4dPJPKojw1htZ/yFvTZkUJG7SJhzKLmx3GrSkr1vEKuvccNEygfq/SmtsXV7bhANWAhUeB2CXxYVuHjNfvBk4omcnnsUeEcxNUzls+Xu7aiN/J20nAnqH7Nm8BtAONAu3ydz6ySw3PogQS08sr6bc3r5yQufAxmZM2gUo44KOv5diw/eqeHsLrb88ACNrcbLndacTr2A6kwX8Ca6LjR3jc=
  template:
    metadata:
      name: pg-campaign
      namespace: data
    type: kubernetes.io/basic-auth
