---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-characters
  namespace: data
spec:
  encryptedData:
    password: AgClhilroXdlv2t7+XCNH6YnYlvz39qS+Ti9OnxFRkOVmx8DHaLXTh9+g4X1o32SyCWyxhFZipDrubV09FlvHwZdvTd+ULm03zhstBs9HJJReg5zXiK1SzTPsQUyZKVU7GIYsA8IFD+5sFFooujSTXXWot3OrI5aIOvNIvo2UqljTzlZ6IKkBTiz8emEinSy5MgOZXMDQtI8oNRi0CiqhbMordDouZOR8geuJTcKKsJQLYs6/9EKe/PgBfVY6jNw0HgnpA2rROOCBVW93YsK9MjZE54MBi3XvNFh4RrKf8mDZYLTq3Z5MMUjqhgd2jqBpPM32NHs5eM9fNVw4dMz++ESgkJbWAdB0NDb21VMbE5q5xKYMzjBug+x4ORnMuifC6/0oSPnOxT6Uhn+r5ifpmScQdLpiz7RnBLZ3RTqiKyd3zbUBk34+ujH4evPB53LAmSpyP95Sg3ny6Jccbam+8GxpBhsJ0PZ3aK4QQlM9ly05eHwZMMP61ZigCANcqCv5olq3FWK19wUNRMZk4wH1M3gZnSTIQ0F4iKH4WACLaw2B3r9dTWqzHT+w4vK3nCg+74Lb1TsBhGKCnUWqye7HUp6JdQGzQM6O6nFkGpJRuHZqIM53PsPlEbW+QtbgG9iAOW+ENhNgRkcZ4PZgmm+F9oPMz9CQOsEdNo11hkUzq1InnMUnW5cBHZNflzH4TKBhexMUtwwxKKktDjIZEsdhjj0P4EiJW+TYYJBQHonMfLpOKLoBH6acxgV8Udwct7yIzrdofLz+IaSwqy5oh1AXsLQJg==
    username: AgBuSx42/w8zzu9Zm3hCvtNxt3NfEcCH+UY5t9Vl6BTC7ZyxOoZChCcsGmHrV00gT8wrYqKNqMB82xAPhI4O+4b6aGYJUFaDsoZD7NZZ3pMLVwjXFv4znU5oIV7MLDwcFegRTgnYOpf2FAY6Kod+9wZfhoY/RQiHwFHxiVj/DLHNzL57ie7QVnr47SS2F5JQDSAuH5eu534RHJmCP0ht8mXd9esraXu2r5e0oqE6XbLSmQTf9ijSG8Tvmyr59lsEkoFprocv8H7wnlNtUwHPxE0L1o1dTL842e32DLGsQafvABdeVxlp5CmvUtaIPqqw4Asvuru/c/xZ6iXWRvz0Djvb8x7opnsOgQutLuKoJSttGCdYDvqgmvGvS776X1iHs/qdL0xluR+fBIKHUHdY3L0Pfl0g0saYL+DrZYNj0H3EBJGZpu44+3DVwZLgNMRhbTqbv/tjC3HYnUqtimrGJm3YrgGNOsZq6b94EkLKSi6w4jKjIWhEGkJV8m+Q3sF8kAJW53tbE3Snl5TRPkquLuGBCmC80FKPELfpLhurE1WVj2lhpdUbGdkOgdHfcCg913yq6IIbNr0LpQiobK4+sJxr46RKczAB2Wj5ph6TnI08SJsybZcxOo9BkdWYoJRLChPtXgtw3NPpgRyNJP/H7/LD1aOSzNPMAln4au1dAO3Ltx+LnPV6U6GQo+x11Im6UajXuBfmBb65XmTh+16/1g==
  template:
    metadata:
      name: pg-characters
      namespace: data
    type: kubernetes.io/basic-auth
