---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-billing
  namespace: data
spec:
  encryptedData:
    password: AgAgEv4WaCtUIXhU/1xmSxmfO2gGIGvThfAOyRsctgAORiIsOnbX/uf8AI4fTwlGWGuT/+pSQe7sxW++XHvodz0UwQHBbhPta/D85MPFMqdhTo3392LHb4sMYHCo+0wSoIrnB7Bw3XOPHw7e70Z1MmdKoZe7lGok7UWp5OZDz/MHiIQ3gEAiLq4HkwBA3xKMVM/9EjFj5JLuPvefsb0KAp/kW1mxgjN2+Ajxg4KoVPgEH7nPrjU+Ni4Iv/JuDXSxi55cMSltqoIlR2vq0D6CV+vtF40MhCcKn4ZcHVoBU1uY6NkwoCxY+kDWPuXMwWYQVt+OLvhuypGxjneTyoQY4b+7Yqn0CcoSNCFxUcapu+x0zYzZzmNDAkj5yIME2yoJR4y0CU+s0MgrnxeweGQ6HP/WClCmG65C8hFDnrbbLl1qiFzBwnLtxI2CknQAqO6g4qpYxrUdhm29iU3wodx4vV4lqo4vtfiR63xkSCGhVxkJHsgIjV+rvmnJz8LjwmkJmRMH76WMCDmmyHMLtotkrYY/bb773CE47wYQIbPQ40AhCSl9yJ8SdjInyWVVumfRNMfJj9l7yw8BM9IAF8gR1TM1VwNCnuDPGQ6D8kuy/NbSphPgUNknQl8iHML1JtdLEb+X9e6mD36eAvEF2Cjd+RDABprg/lU7YDl+gu/ofh+ucRiFmtfc3VPExHGx7ODLp6VOWMb0clOAEtK26vcRu1MtdNfU/7GC5vQHkoh4LOzY7FN5dN+0Udcq/2OarRaLJG1FsOOgEAiWxJ2MJZRtei+rHA==
    username: AgCkY81e//vOrnzJKibka1Co2x0St/NYHzd0pUOMB7t+4R7CdGy5MvzOkJ7AjSfz4lO28oiY9KWO9OSsD0ZQBK7IV5Hv6C7elmkXiM0GS8xXlv6lrlQBjnCTHFJZ7+ZCqwx84UIO95RTuk78fSOCrPqur6q75OCBqhK+UwAPAz6UmV3fa0WBmkvqbXHw4TdiVvIeRPLU3zi0P4Ek8O4MbUJ6y82xuGWg7lr8RqCspcqNDMYCDfOFTpx+lv301JLnYzFRbANgHP65Pm+q8hcbLGSS1hl52krOaOuQrT/shBO9lO+ceRHKBpfQ/mbdUlNjq3QG7hlP1W1BElp7EV4xe/lII+L/rswFLz+d109mX9VnWtIewwp4mPJIHNFo9FS8/EFZAI6/jtDe9H8inALg1+aUEW77/h9CExuNgl6B6cf+D04TMaIyoKeC2xjfx9ZQX95EnYmYiqpWqI+prcgbf6wX2HgKSky5vffdFUu2PYHGquEjkAT2hYWL3+DI/wmVe35r4zdILn/L+m+4X4eHrn+DNhDYHPGH7obRE1UQ2Ko4UnwOJlGnXAD/PEwew7eqjcf+ImJKGZg5Y2IOg7wxrnszyy3swWjwXryjlpdqda+k8bKKi507DPYqw6WVIx/r2MVUJmFoLnf5bT+Wi4eMNuh4chspkfoHl2cneAFXn0aNtpyNpw0FumSSvxztkkU8bu0n1fAReGoTaoFWMQ==
  template:
    metadata:
      name: pg-billing
      namespace: data
    type: kubernetes.io/basic-auth
