---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-backup-ro
  namespace: data
spec:
  encryptedData:
    password: AgA7ytkZL5Mxo2ODuIZDgDb41Mz5SJMJQ98oHGaYbzTaXLdhKKLsuSBLzoKfQ07GrMnvceo/0AhERF8QiixlBM98OBScSQzDtCQ4VSeHQohvC1SctC37CqUNeveaLGQc2lLdh8YfAm7LlcJKI5o6DhmH1yIBmJwnL8jgldRaliywdclApPV0sJSeFtp5aOUDL48Id+yGYbqJU8nIpEISCoOo9Dp7JLtyltLymICI6qxZCMdxma0geFBpqBaJQ7xo4sJVbOm66y2Dg8XKcOCgX9Oc1WvkIwuaAaXp0S91xvTL+jNfFAEZ0Vuswxq4OdjmxpI6lI+WDgKapOZuq9t6WGs1AIXgp6894YTM6KI+KWe65v0/MBU+HD8MycuEBKYXdQMbDI4oRJznWre6e601CbFl6dZ0afhR2SEe82lcBdoYoauEdQxrWIN8EcYQWzMrKufYjaHGKvWk1bKNzipVQfH+TUUOfiYygDJ4vfleu4WkrnHIxaexQJ8Snq19kbKCXMBdftJY5ZjalwRttClnyPs+qDJwl/moZEpgNnaT8icMkeDrXgaqzyLbfHkvvFizAQXeeZtuoBTNBiue+TamYbQNDn/C7KnSqZdoULZlKBBt3PtmgKv+K1A5IoFHlOqqBsJe8TJ8IxgNTch1hLeZHSDRp+rZb33WtrW7A/UyqK6S21HwvnqsJK6W7VTPCS8o7XEP9mswk/KpYy/vsPpjCRKjX838+uPP7opv/rEfdDucTm+gpq/GHH46/dVvPFGth9cxUXc67sQaGP28M1bhPDlYZQ==
    username: AgAXUbZLN2KqUY46gcCu/p/ypL0dXsKO7NsekDMPYlJTumo76rBQqZ4BITO+/Bdf7IVK++scqBbiVT5ydF9mYz8xM0ZsFUsLVUEIA4haKrCFWOwElU+6ZS00NV7yVIcEXdljs3A96rJ6E+RTXsz5Q80QZ2n1efnP5dVSQG7YM+4aRQz8aHl36kMuk4XrBViKWM9QV6rA/kq0M0lsgiJyMquKOc7lzFSWxKjaF0oCH0ma5lYq2vU/A9OmXEXBtVKhC9e/yZGYloazjSdVxP/C9jxm4dcH+wcPw9BuwKGIxToJJjET4zImslTLtWDcd1kLnHTpVq7mZMaXO2cTAToAga/Uqy1Lkjro2DlHliRB1pnkYgGqIR+UN6ZJdoiHH+cmaPSOZBcoDrj5VsQZV+mLWET5rYEbkOPYSUxQoAz+ShxfUiJoKonV4ers2ucG3qM7Wmpg78qi+qTRnxWNRJIUaTqhwr+eQfPMNI2iSGvRSDz4bPEn8bviG3JvNxWvsSA5svarpaPYTEeP0qsnFyU58ZnwQGExDYKAmlbEeD/U2K1T5n+VlBPGZVVjVRNqem9U70GD2yyWOyNhj3xacupZDsNGJzb78SI+P81UK2SJF/cP9hE6yZmFk4Ik/LGTmkSEDrqyok21H18gKsb4hAFLIdKsEa3YO7YKstpUJ2k8c2QHpQC7FIT3BTvdCAoYdiECdmMqD9n22Ng0q1Q=
  template:
    metadata:
      name: pg-backup-ro
      namespace: data
    type: kubernetes.io/basic-auth
