---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-identity
  namespace: data
spec:
  encryptedData:
    password: AgCyv+pCGTwY6spmIueQH9lMoBezy6hyqPmf0qE1+YFoSIubkC5S5tTOglokuhVdb2U3IVMHDzYDNiPFalwCOWPTOzhUJhUzND4FU0eYuwtLv2vI8HBtnqUAYMmvY58gMDOIlnliElINcMAolkmaJtXFIdnKjpBiYDWnC4LZTVJhCEEiYhPcc1PltDmwCrb6lRCNU7tLkydcg+u28n/xvm0dQh5cFUs2x0YugAFYVRMKxx25ofx/wpnhxHAc2KpErQUWJZ0pgm6y2TeCo2911LtFiiQBUpn+UFt0PjriubuchAMTKTnIf0G8SMOxwVEptLJLnoULT0CE8hjjYUz0PpxeaOgi26+bLfslWET8HM567yC+tBwBjUBZIeY3dMogYyDIQKYT20k1kbR+ncdUfHajB9AMOcQXPIctddI6pXNa9HrTYE6H/F2VqUaYDI5xU0tXt+IWQWtsc2aDZZobyYHo0+HsZD4SzWEV27j3ZI3wSupXQEds0JPAuti8K1kxaMfb8vQ4nAS7wGb0+yYb/qrAhd1Q7u+vjYl8YnYeLmKUduoHDN5bdqUaqsn7qOxleWhQ8zIWvzml6Y2uu06NDa+ZhTEZIdvw+lFGGOYTfx+WIM+kpQjn5zC8Fg314tWNmE97T+mjQ2Pfyrj14biFQ1W8x8iuaqzhVHdM3gN1jMP6y2ht6o6F0Sjbl188OzgVf+WyiUASXvkQNO33f56AoSbez3gbN90UjLRsfkBYXLUQ/V0WZF6DUCIRBr8mvSBRg5CytjxLvRWNfDgucO0EBi7wLg==
    username: AgCH6aeBnfcRQOKDtkgNaD8/vB1BmleGjNnoUodVps+BoYjlG25ElIqyo70Z+JswmMqrnayyeqyPdqhs0/wTysSk2TI4L7nrc7mJq27sZ7/SfMFjrUeOLE57LkMSiFRk8I6zVhJRVs9P7GNn2S3P8MP/tXhpZ7Yp1BKZqFyQmPfKMNt+kN1wpqRtNdW329XCx9k4Sx4GVRwN5VcF1cX4zQnhcfWhxEaQFJVJ8ZQHMTkcC6v8aQbwDLmYbGDdaSwFaoiSoADkhApdJtoKWppHSwWgA2iy1lhXVncwjQaSCF4CCGzo8EG7pccii4S/71D/Lquw6m7BCG3W9QpR7Yb3QzYQMRqhzGWJtWe8i4kkSYqwaLjmUZbe58zsvAW8usMfPUQiDoVx2LkqajiesyEFyP0rEEaP5tlE9B4F15xtEQqSl7grqQdvmKRjpA4f4mCV4+Uc74oc0CBMosfAatibLMaw47gJCKV4DK52a2EJAUeuR6YP8Ic0JxmN8LWQD1PnOBr3+5FykV1fDdqUavUNrsR+iiBsmk4Fw6VBzhAIFfykAGwA01XyMwqhzWBx7Qrqh4rWx+EFrnSs1ViQJSNodNm9ozVyZ6o8x1BoBecUWIhaQU/cvDxuni1iFAK3HMFPMuOTxxRUy3l1e+XwaZOw+5W0RAqJUxm0//AfIQKXH+4LA2FC6DhLwXEttZ3GAGrWS6mMmSjsR7iwmVR8QYw=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-identity
      namespace: data
    type: kubernetes.io/basic-auth
