---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-audio-owner
  namespace: data
spec:
  encryptedData:
    password: AgABWpXd/7wzbHTP84AJGdPSrYOWNa6m/CRB2np6Z45jU3mZD3TyLi6LOul9auf3A1/2bFhjgSYsD4xtIBk7sbA7l8um0yyQSb1R3xZEB+rqq2wSFls1ALPreFUpMI1IaI5S23vwRSi/4CqCYa/bZdlweDKlKcuP1Ur9C3QwI1mY8Nd+7mrFcb6PpFCKoOvpo8L9bv8QrNYuFHjJ5+ij9ML6nEB5SPymNsja1GnUXIrvRhFt6KhjZ+LPYoBw9TV0sOJ56PgIw4vSxmjLNWA1O6EXwJ4Gy4dCnNG0S9wsdQ7eZhHOOStebt5+HKvT0JQ/OKPQRImi0ymNLgVkE+jyIsBa2vE61fmLXf3ejur2tGDWq/N1sFF2veWZNRGTDyaFcGCaIuKvc53A3z0pTW8Q+nwPRV3YZMsI7XLA/JXcH9VdRvWOsM/xlfERhYX/cgIZwFgeHmafWZFnNnCXG4qKRF0cUHm85mJ8swbTVYGCSD4sCdq4zjDB2bqLq1khQwBisEy0I37QAwxUhzJ88PiWmSmlLjCy/v4hDJnl0D5vnraezYaPQOtO2iQGXfk4yPzvU7huwvpERuADKSwmvTvD2G4bu/YKeGAL3CItp3zMI1ERgWq8giWVOl75gMPu/G6CPHWhDnpQ4X7LjnM8IxbRWXeuihtWRz2SHL3zzehHXgqjDH/BmU0ZW659KfaLU7TdNGkCe5Ydgy6q+7D1FFk3/3RTQRD/26hPpBe1QRJUHmPZ5Xs/fcHbr0QuOHNSTovddp8nTV3ut1EcS6NhDPUw8mOr3A==
    username: AgBTI2xj8+mm+jUckg9MsGdwjXbfs8CNvG5eSne2Ae/tOyFc1IVbfSS9jc3yhP/+Tx8OWVnnd4o5hCbfIzc8wTrAGYLjwmoQXPmHVXSIThbqwJy/QXipPnXOMprGby2U7FEOXSMf3Mjvi/Tf9ijCa5V9KcVIPNPLjtBPMTo+AubLtc2VSO8WnVexsDgJpDO6K1JxrTMo19EeOiWudzTt0A1qLqa1SIpQuRTPudExG9TWF8EtTau1Onf+Y+Lp4NKtk9VB4saM2fvgNGymv68Qd1L0fXyeDHpx1rCwtWwrsFtSw8svBigi11Wh9SuTWRl+42xv90WgrpiO2mzmJJ5aSsrCjV8b6HXQUNy1C6vU50b+ckyBSYd1UmTvzg6qkr5U3XZKlxgBRACRldiah43qfqojoROvpwOdK+c/f/QsDz+vfufSNDc6NlvsDJ363aGo9b2BhvGX6zKRdTdlQFAsCByRzNYpzFUAN9/N/0ZnxL7FVTRO9UdAtwc91ZOwCKVi5I4OzznvrmjPr8hcc0nxIbvMug2Gxb2eQdbHyRQq53Y3pXyCj+zHDq6W9IfqddA5MIOCXGYQtwhNB6lZmgXeoObgVwGbpd6VAU+Z7YUpw6J5q1WU/MBW2HtSKXEZ5ZWEd40ettK4CZSGqy2eX+4UD700tBYaaeIh6TIWuGV4hnkzRvBRb2Rs/R4oKTDIjUtddGBXeYFcpti03/5fZQ==
  template:
    metadata:
      name: pg-audio-owner
      namespace: data
    type: kubernetes.io/basic-auth
