---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-history
  namespace: data
spec:
  encryptedData:
    password: AgC0ONIdvYWEjgWvlI9BXWsdmrDFYcA6m9xpmI1GcfyzWKojWaZbuCBM0eerBnCZ+SJuuom+gp1t6E3lp9PGzxov2Ctn2++UYYBXPIPXRC5bpnSagw8BQUv/ZsUog9/YnEZ9JXhuA2Kc0SbBDhdOcqmWhfIAbX32rtWiDCGGMMpaJFPc+SZKOpZAp54Yic90IXj9/HNlcbp0R/ZF+hmtnPV1JKSaShfRe2IOYNAj2G+0haVB6Ake9SDvG4NZs+OoyvOELcNjgqEDdN9RGnAUTyMvBE4Pb1vrwE1kw0mkCIaIFHGymdECy6EJHY3rCADa64E+XFfEGPDKNTSeiYA0F1YSCOCDf+900QVzojkcxtiBHe02Kv4Lo7XwOUNXBiN+NPsILFXQU0uc636DpjBBqzinuTw82r0lnvX+g4kkwfT5NY9wa6gqzzISPcwBNaKdiyMmw6R64ZmXUGgBQu8FnUePxu2b6Dn6LnfTUs1nRENaqpKOuD8vjCDFfhzX3QXib4egWGQTxKCxSNSHpZ31bHPPi5v7H93uVSrLvy/xMFvuzrZSfUs+/fuuduUrTYbY3a4GVsihPirtNLsWfpw5opicHCeSTJMt1VPlSGbCuv+suFS+7dxiznyji/p+doHOk9EcSU26oGF+yS91YTvdptsn7vzwuXnCesMqNH5KyzmPC/EJkyzsHtKtTFdnWmzZ37tQjx3gN/bfsabU9MI5OX5T2UqBjr4CxLCd98JQYvjecu13zw6VZE3PBFqmEJxojPLMX6mXPOlC6k5/PM25lEXCxg==
    username: AgA2JSSVu5Iy8Hk1GlTrgFFxC/zUAxdF2UjcQ6zIsulFd7X7qNHgxPrSl6jd8nPhFjYyRDHG8kJW/D0YysY0oUJajVvErlz356rs6GW3DbTnT4QBDhBv8s3J7t9qfL7ePtlCtXmwuGpSJnHNwcWdWtP6Mqvo+VYXlKfo5u1ljiPtLFkiweDf0Rux+wIbIuU0OdeXsafC8oTxNWwP7Hmr6rK/QcEv7BBSt/7QIO/uRSuIjOuV8/SDkHefiWqNa6nJPcEzOVcJ/7bz4BIcSR7T4gr9RffNO7RnYKGh9nhh6S9G2CFzgcthkvb9nLHz0ZEqQbNswqSKoP6CSrfrb/URpM0MegtMsMlz/2VRopdjBu/X2AJj0PrnKeFxizW+kK2n0if2h8DvaQtUX8Aggw1pEc0W+QV6b8lw0MgMkUIoviRwP+vuGQcSTtEKn/3YRITZYttdRJaYAEyCJ7tJTPVg1ZscXdAmlqboeRP5t/mM09oxUNs03v9aVWsgsFJwgpjxPAw6y/kEAohJaD+d7CCMCup5rnNxW/200erGIW/QXY5cuChG34XCOkQAk7NdAUpJnuPn+MIVyh35DcWa9iIARD1Yoqkc9ewzxZQRC6ustGvoXv/C1o6m3/VcCABM6BkYts5+WXNW2NCGAJz37yEkQaLC7mQbLYQkgujk984dXBIVfow6Brf+WPzV5HWsXeT2NnilQIJ2d4GfO2xIOA==
  template:
    metadata:
      name: pg-history
      namespace: data
    type: kubernetes.io/basic-auth
