---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-dice
  namespace: data
spec:
  encryptedData:
    password: AgCNTpd79cPbjUo9aKb/I1Qa8+gxhOtt1VRYqnNRNQI6D4gnyudFIfy46FIN4Axc1cMnc2ekNcN6brDmUjg9xH+nMJmgidgzjiXeKEvSTIinuibrM+TpMjrfVTMfQqPSI+/4wwLH5nG7757YoPScACcxXSZ8Erj9wYjfa7/u6gyUr9VXu2mCsEmPxoXvqRzc4if3sBx9fL/UcbBOX0F6Ih/+yxwBXjfxZMZZWWwClHbTnONDj++tIljmRq2WhSsUprmp31z9KOaLN4UktcFvRLhiNd5B6XBACc9cI559RStxEl4pkc8LnqWhWiJRHnJD6e60NUuKYre+YvEVvsaShRhVILQUA57xjwEDgehgEjT+/gzpS9qIrkgKbf5vEIY+E+SUB6nzC6OiDvJj6x5muX4vHPXgZ9CXib/FMhGsDGAxOFctYljpk2L7xa6RdpIrFq8PKs9JiXbkWAxVz4WPNYCwsEfTKuTFsguhVPIvME1Ho0FQ+HkyoroncE1zML6/yipPJGHLLIRBDYSr5Q5B7FYGMW6hu5H/yLShaXMj6xsGoRzmfuBCEoHQRAs3wi04kbrYcxlNJGKUx1k9lBCU8RCyc8jSxy3/dTRRWy9Hv1Hh1kSxkNpFqq3HaUII2a9VSsc4DMmIpiK4Q9Re+BvSy5qcylSfG0cc5F0gORXkhDi9J6kR0/kSFsjS0W0JMR4qyHOdUPEZyOPH4Ms9qf+WamqDbWabWfZwTDAAdSfLdPbtI8wjaNsd4Ffp28HBwhUuo+yUJKyCCQOxtoB6JzQM9YdF9A==
    username: AgBS2RFMXy8IhK8TojlMg8s7f53/pCZy98atXQYMCPy9q27vuQX3QNSeXCGkvCMY6TLcKBJcxIdk1hEe9lDDp9RQ9M6CmkW1eYs3W73sFs7kk18kzktUZ+tv8BJfnjqb3Q5anTGzP+yfRQGtzMOMkxZNLcwLVju+/QNKr2MaC38neGKIGXfwoopmaOFPsKqq33HxqI/R1B6jw5whURInu/aYU5ypg3oLf9KNiUPOHjdo3QOfLjPk4NzVQE2+z3otaHu0cJ5LZ72YwNMoxjeRx9g5xJ0xnkVjHsFL27jkAGwNd5q/XwyLnsV0H9wLO3k09QEicUJVlwJJa7mme1C/ZzYpFkKvgNG0AINd8pKD8O7oAOwtqJOMrbwuq8MA1EeIvNBWX7qQWuoCCt0nPEu8impYiPSuLwpaxiGB+zHc0UxZk2SMxePsqy8cDUgTIkWlAo2jUVQLXBRcV99ISJhsNscFL+JtbQF6aeqOBb1IrCoGU20BlUHJGynGkcTu4ulrFYLXaiZQtBvC7yCLM3fnXI5qzufsBDrxX2ehfqZ3Wfyzwg90ljrUiB6K6lSfEBEXID76bmX1EK5/cayjC4M9LNwtft22E5qc4QkLlglDo5yrkBwh7UHeEZ0y3i7EmGWdw0R8sC/b/OlVvsoKUgYF0bBbkWuC7upi5dKD3HCYjBubrBfVWBWr/puFR1DbhNk9blvKgq0i3Q6rcA==
  template:
    metadata:
      name: pg-dice
      namespace: data
    type: kubernetes.io/basic-auth
