---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey-staging-users
  namespace: messaging
spec:
  encryptedData:
    default: AgCX7iaVPYPKI8b+wTRiL7eHhF0ZD6PYgjWCUlOQ6TKk1q3d7XW4tFBmjRP7ER80LLrbw7vl1UvpAmdaZcW1xdHQlM7x2hYRUXb4ki+/iEi8DOmYQVXF6cNhKFCjAZvezZQ095OWC9vZzwlK38vsDjDH4BTaUtgbCqDj/T4lp0h2sH6KYPZsaawwwNNhFK4iSiJlrKEn1dKn0X8DmNcWz0XXkhf8jzbrakqd9sY1j/5264o5yIlE3DhVt+pr7Gn9OwmUf/EiDZYGqD+KlFKg+yJw9ZUbEWNBwDSPowJxgtZoCw1lMxNf/aQzHeNRJqiRKH71Xg0XRVBx+v9DqNL0sK0/FmUjoWGu4xpMFZ6vyzGUaH/r/uNGkNSoSv/N/SZIqF+RbEXaoblVH4RcC3kHa+YQitUaUiOm8Z0kBySv8O+PHvk/C7pkSEwW5Kb8QfDfArqa0cE5zLKZ18ZIcjXPTLSjhX5CCdTY4vrIZzLB4yU+8G3PAYXu0k2b2mvE+6dXi684rn/bl05YjSvACaD7pAMqSiNe22VKJ0PeDhnyzdnR/0RiSZ4ib9IfnDtzKVSD3guHbigeNanNwyrNILFkiRsEBzJpmBrXo0fWz14L/uvOxv3NgQ5f+xI4lUGvjusak6MljV9ONlb8BBcw15q7fVwk5fq2na4v0IRZ1dRpywo8rB7T0dGMwUFuvpVKoWRfaayAvcml9FN/YDR2DfCPMY8IFIhnsIL86EoT/OloGgrmLm2LhylEsOiO9SzmgH0QwfG1xoVxMVn7UR/Y++qjHeq3ow==
  template:
    metadata:
      name: valkey-staging-users
      namespace: messaging
    type: Opaque
