---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-dice-owner
  namespace: vtt-staging
spec:
  encryptedData:
    password: AgBKSDUsORqGVGehY/tI6L+E/4Y3salCKKye1BNhtnH2Kmsu5P1KV4mlnT+jlkuHKb39yOW8kf4UStnLXMmTJ7ewjkL1ZCysMXJA16MOs/l+TmFq0NpWdnoesdP94QHCTQMBV4sPLDpKSE9pxFAYyVqQpb28XSxjT4yCUZZrH4uzvIPyErgRh90nx3eU4eLPXahtTCIhFKUn7JR5tKg4VMKIISGeFoAK1e5D7qQKJwVkOqNg17/NA/OpgW35BDqRenfpROT7f6mKKDZdyG0mfxinAz5ddEELHMt1OlE7ROhmI9FxagVqnbe+3PugN3pLdn8cj2veCN0V4JM5+rkG3ysBoX2gHhIwxDgNxxNQTCHIVru7s6RfUEcC0DflCLxm7cOtxOijxPOEULiH3GY5Uq4JjfVKd3+hE03VojVia5/So0M2f1IzGbicdpj8WTFGdSX2r+IO1bgWzL/vk0+MblsHVBX6l93KTEF9kaM2d9zKmbVbGW2vVkfKBFX8xH2rQD+gg+3yQckcYGsj1+j0q49M21EypGRw34KVk/N52c7CFjcF8E72sgCxklRTAMcPJzomw5EwAgxipnh7CqVdrmcYnDb4Ksd7VSjMCwD2Y3CZDsuX/fMaBsP+wfrRT1FIniGJWMfKgEGXvGJ9C7ravYfGZgD8n1Dkn6SOCmXEuTruBRDEDS28wqUHuq+vTxkg3dFsBbUV7mhW3T/bo262H8JvCzec4oB+xGyMNpMRk/4NRgBGxOSo6kShj1x8zNAaSPgwQNWtZnTc4CRzi9PUhF8gQg==
    username: AgCuYM4D4sbvxbdGWv8UqKxBZo7YQJ4iYdyDGRdigPNSmQfa80tLXTyOfNJTr2wiyzq+AjRqFr1Xf6EsYmf9Z9dPvwQAkK7l1E+OX9afDd0QvbSjXF+4b1EzPJDQS/VAWZtVduK9fTnYAWsOpvlhxuxTSrC6dc8ob9qizUB+JnC0yh0yhvAs+LNcSNrPuSdI0EO6zGHoicVb/Vex4Og97jPKJjHex2KQ3Vpiz2g+pFwuu9pvpzDXiDxz6lndKIV7gCbWLsjwtv1M0hJu7/G3MO071YAGzrr2EbR3aSXHUSwTx1xjmjOredbauyynU1N3tNMxSjehzrQDCLes5pCWcP1ATA43KA7bwCOkkBwv9oUp4pfOC7/fCErWRWtANw/zojVEBWuWJhPKBnmtwuRsQwz5knL7c19Xkrj01QdAWByVfDGJv+On7Y7A+QZieg6VJbIL074Gj6iXTmyCmeWtDwXBZRrbqTOtlKJ/mirOfiEzwSAMEgDI1DntPBx7MuTi+NP8elAcIffZ0KTVcQBNIwH01TA4c7aRZOk6dNU847QCEFHe7zvNZxkxVtKUMr4iBXlsVj/lYkV3RPRJY3cWChYgGT3hjVi2OGSlt+wnbnY6ZZNVQFLuE5V1PaIxudA4cOSWbB8VS/zUXdVdarPP3iMnCqCmEZpoo6yxCwyqtlntn65QEQ+dUaZcxn5A3Bw4CFTGza03PZDHcLqx
  template:
    metadata:
      name: pg-dice-owner
      namespace: vtt-staging
    type: kubernetes.io/basic-auth
