---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: realtime-secrets
  namespace: vtt-staging
spec:
  encryptedData:
    INTERNAL_API_SECRET: AgANWuxIlweBR6x+7Kp01ePcp7tnsBtX9yDuszUVOAILSjVTKHRn4e4FkMmudmntUhoYyVAcDzjUKnBURgN2y/5zRGbZuJFPc3yaPx4GzT+2yTwWmyoSUtOt28kq3nDSI4MsuT0Y5uDuNIzdI9MBdmV2CBICGXfvoKo0Ecyh4QGiaLsxRpKumWiVWph4RaHFIVDl4cU7HvTQVRoFCrm60l5lQPKSjY9k2hSBz6XaS61lYAIfGNTcQKuXdxdAex75x3czux7vdJBgPAblewv2oVbRglixEBe0wanzePeAu3xOzZ3WdUDLrWOS8Zm9XP+bWdnhC3GLnFEqVCnEYdme1VU1992LGkbkATuBKTIc5aWN1D5uMCD+xTC8jZvmjPg+URv6rmJAj9F6J+L/3cAOHLgRouYxjeUv/KrRlXjSOl2J5lUdr3GpSK3Lhi+kHoTqO3oPBta7TB+jWsojO6UbSIcybrM3mnh3gQ8vkXsjaKWGznDDxxvKU5f1hAypFsr3Q/k1BGE1Cm7pEjEPBOWBGAF7mDuRnIa8AKpY/LOxcAzJ+4ZnTPoyj0zvQF31yP2e1R8eG+sG4hkkewqnT/qgXzGhBUP+vT5zDD2hZlgMk/XrIFF+mXGc4KT39wNjNYxz2JOJh+LaRYLVR0e4BWOtB9haRUcIctdrerhAiPKH4VJzepVAs+u5hPqfajEUvnUsV0pCydQ3S+LWuGVJlsg8BU8x93O5NgdB4oErDwNWlRG1BWxWO/rkhFeUul++392WsunNGrD/wuPgkq30FmE+Txy6Qg==
  template:
    metadata:
      name: realtime-secrets
      namespace: vtt-staging
    type: Opaque
