---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-characters-owner
  namespace: vtt-staging
spec:
  encryptedData:
    password: AgAJhmPrGXvgRLkHDQ6t/wedb2yzRNTEukOHPb5t/IQlOs8V3j3tkA5YbvMw651ourAZOQXu5ODB84A2WrVBuBWHirf/3MBc1icVIKAMEz5oFwJ7lhxivpfzpDv71DGFLL139yuvvzaPsgTqOlleo5gJzMmQoJdIW67aYGRC2lu79xXeYi9yZoA1hGhzsNYGoIwyDr8X6y2/21L8xXdKXYQ4Ffa3s/lfm3Jkjs4YWKTAPXPf0Bhk2ia/yweyC5Uco6291XBZE6BQVEklUuGkgW7P9IvIbsHEb7IDi7+k+oEZLOh5UiJfKygeePi+5wkEXQy8kkQurJKdFsxqrjazsAHXOwoxuqC82U49+VVvELTKA5gNzciSXbh0kkLpD0xG1x9A3VPfq/AohEQ1c9ujw2B+0FbCJIZnySvjpdjD+5HHU9KzB3IR5fSFdLIrYDe2KHOwfRo5U3jiVOStE78mUgNIry9IRU8RNQLCEv9/t2rKEqjWP7eAZ+Ph5nWJTJnzivbUVgraotCv2pDKRbi2D8sE8zTwcmwZPZAaGui/VRzVs0fi2DPIHIVoJoIqVx+E8NPsVv5/RQE5glZt67PF3boVLVhbKw9g9RAy5eKy8NMaXZfcBZfU8AozE2uT3is68U5waIp2eNoXiYhY0OjW1e1zg/r7HTUx649hl3NzUEJoS7+Rxmsc5rXO4r0CdyFYmpI2l5F/u5PKKA7QExpTRwrWg9nt8hw/vtRLIuxsjdCAMVtumT2LJD/XdtTK1n3jUWlYOEV+lyGR7kABgWaMlIi+2Q==
    username: AgBid02Q5G8qrD8vm6t4N4FxduCi0qA3uNAhOKd7TIZNy6Xs3zhoYC6u5GOJxj9TC22C774mkiKBx4r8vyzy9qfeYLarrsmk9RNwECZir2U3agF0v/ArtbyeE+774lPulzaNZaSmKlFlaDghJhuBJUkLWiZhkmrfuHYcwDTTNY7Xb0DUIeHRr6Nqyglqcyur/IDNK3ob/fPnhd1AieiNojt7eD8F3nnKzOrChEIT/lsXLRarY8I07OgCiBoUtTbPVYO1POqJs4QMDA3v/pu3Z57XB9TZFN4php8xD3aNvfEbyXu1hsMFBFPAfu2YPKKqy1sfh+26DVJp/jdDZPI/ohcLPchp7x2x+EP0LIWOTG0qihptoKBGpj4O6N4IvZXvv4MkEpuSlUS9LZ1VWd9VtDgznz/50OIkADK8SwKwEPkUvfoIZ7iHXZ7H7tlw+sKnJh7Z3twDskiqwv1+ghhQKTvv8+yt2j6lnCTXccYKfqWEQgYNUoJIEbprrxCnUbpPBi0wujWotaVwH4lHd9ej0zJ0iOlSuZCnF2vNUTWQWRgNIedbSwaC3Ob0QvF/i0CGAJzx5I8qOGRvybaFIIhY6WyHbA2cYvqrTEHbi+Fg/f97t8QZiUMVXtu4P9wlJ5RFk2AMLAa0GHAzt/5iwmUmcEylVWYash9SzgEnKzyVq0XRwDdjbo6BPllzAq2v5fsjgGliZkkaze/YVB4qV8/FA8F/
  template:
    metadata:
      name: pg-characters-owner
      namespace: vtt-staging
    type: kubernetes.io/basic-auth
