---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-audio-owner
  namespace: vtt-staging
spec:
  encryptedData:
    password: AgA7lhdkfmFyvdh6+oC+lhA4sEtVp0NlU1WtaUoWpCia/KfE/yudw6/q7leWbielkwPpbI3ROUNSyNrNjhF5ghzAePQM6FnbekLZ4xXP0A5b90OAQNlXlA+fHraQ3QX70riRPr64E+VNok2aO789XA3seaQ42c1for2EHMbWLBW0eARPNrBDTnxWZYpAUd7SJuu+O5i8fyGSScCiBcqBCwYbxoMyg6oAk/x7D6KNtO1HjJ9+LptgHBrJ6DoCSRwbZk/YE72VhYrlkyiUrGHvZmzkJZpqngfitl5OmrYEGWL8DP2Mk3H3UO1jzQWUxgFkColzi8nKSa8mdpJArFDsYXm1aygFntiebfS9L9fCF8eN143PWg0nPXRk5xGjYWvmir6MuIsIuLN4TZFDMdeGKmuT9Xrfxv3s3KsHhJlxRgStdF8OpNHAwjYni29bQNgU+LSKio+lrqz2FD3DMjH9qboub7XjEaSNwYdfZl71quXu8ay/PzOBCIolDv3npzwOx4PkWqmompoAEuShXepx87r9HL95SaAVVUgU0ce//vd2jwBeQeKzRdEBqVPvOr2lgX5hX4n1Yyn3Uzt3oL4EKCul5oyVEDZVjldYIvo3KH5a5h/fNA95PjGVx3DHcFfeWZ5k5h+GFQE5/7/y57tM6YeyAEt1JrnHBjJX1NGwDYsowUZvG2jiHUyhHgc8rep9/imvmVKWjS+KTsbJCPMG0zhKdOPR1a6onyuj+RPBggk4aR4PJS3gkC9skzQZqYkACxXB2hUD17VUclnebaoeXZqB3A==
    username: AgCCeYjkqqsN1qRjkuXaAKf9N75W6ybNU/PQDktRjAUFv413IbOI7gGIZW8OU+ma5eKKu/eCczsRCN8HdSX1qbaXA9eodQqX66qxNAPOjxfTHmIvvEB+hVz1rav/2WMQrG9MvouqcoJQqSZUsvQFneYVtYwHPTIgg2BcQ61Gu5gIwDt78VLDYrr7ReYvPicT3yMqiKLzJ7HT2n39s29+1rGJ1xAqsoI8avM/ivTJFmvIyq0o0M9G6ituyHQ2BRCGKc6GOjOptIhGPaAD96ZUzE57yQnDgUum1vZHkqiyH4NQV/hWJelRqJZCtLvtQTKto6mgdiFF9eb53PToDjcnLPkLmTQNwY6yinySiRblMKOJ2rXSaehhbJrPw6G+7+YAMHIzqkLeSix7GG4N3/bOpDasbHrwBc1k5zZ2qs0H982LWU4thnUVLvkIkhoZr1c4PyqRQX7JmN4QiPdzFuracEn0UAu2s7qpeJ9jrKBSi8dG3Zdvo5IOJCaxPf2RAHCszP3vRJc0NAeHWLkUL+TrcBu+shISs1MJs+aLDesUaQN5C4ToTpcpf8IyidhcM+q399jJHDX/1lmwGhFGOIu3Ykzb28X+PNOAlalYSVDCQsnJu4CSLz3wKh5VLcg3L+XcPNic/Yn9HHH5+UF9BOba/xu7e9AqL3aaG3v6bReQSybFJF5hKqdxJSMnHbwIuOrf/HAQJ23wlR1YcdDAAw==
  template:
    metadata:
      name: pg-audio-owner
      namespace: vtt-staging
    type: kubernetes.io/basic-auth
