---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-billing-owner
  namespace: vtt-staging
spec:
  encryptedData:
    password: AgBeHLtGzJ2NWaxB1MiWzypq3inpT/yGzjlDGC4X993DnCRklmLmKQcCw+JubcNCgBOYmghoRDaGOXG8gNAGKwTXRca4VN+tsOo/S7/ON79BdtOka2qSLxsWWbsRd9dBEMZcG+Gq/04nNcVD8bmO99NQtQGAA5GcR0NV1L6q8I85wlV8sx5CLM/A3QZy9foBPnzKInZc3G6+cSjlNMXMt17HwjEP/HhmPAnfmDWjAjnFDKA1Kqqf36OVewKmET4eZfzdvmEQCnBJcMN68jNSsBsVFf2X4AskGaONZ7UxfHSLtnBQdw1CV2mAlsJevhEIbA6IRiYa3sH9TTUEr+dcxEJThEw5MdfHK+IvmiABY8ZnKh9PGNBI2CkbsEHNb4WpSR8cSaqM1OdsH4nU95F97+8/EfNnc4LqzMep52BIF1G+dLZ2tY4A1k/Cfl6hqPpme3NiY4oAqRfCl3eDX4jZxdrT4pys8lig5eGu9sad69xEMY6Eydl/sZbQAeGMK5ACxBTzdACK9v8sJiK9vzWvK7Hd1AdlXVnro+Xgxsd1m9aqG41xXicrClnwAjvYA3TgLFZxuflJyppaxZUMGB3KqWKg8xZuKph05sAfcOhPq1qjk//xiSRhsQ+PJLHl1c2Fa0p5WbN+b7kwa+KEIesBcKFh4p8Vrjsvwekyww4di1l/zMt+3vWinJNo0r5FkxEgde22Wj6+x/LbZl+2phq4qyQqkfGhjR5i4rw6h7msXUNZYxYUQ9NlS1Kkc5QzU+cP8dhxPZOr/LTLZIvv/1eFM1rq/Q==
    username: AgCXZI051bIByl6QFsWMBkepGeO9cSEokkyybW7KEz9VaI4Whvu45mt+ipO6AG44I0Rl8Ns/M/wtKIOVVVxSAh1Nr1S7sXCE9FD7dUTI7mw69xAU8U4Q/UpYGoNqdNBpef4H3jT6ylJYo4dIa+HDleAjSye2nfMmskvfl+GIU/OHpSmLk3aUV+tDklbrq+55Qq4WDFK/CliLJXw3MPkpnw2nfpCbylXcyyDmRaikxsJFq48JbAOw9lM+DFHM0x4ggrWumtzxVWX6/c9ReTg7iNI+OVleLgibyhT7bCger7CGAioEnbKvcd1YnmKL/pFP24LGB7IoKKqhPlqYkV3372z5koQIGu2j9bilSdNR4gAR7tPe1TMWcnTuwJMRwX6ZO8bkYHY5a7kirBcHck3Tv3rNqCvdXqU+pWRhGBANhcTbW0uQ+AzIgA2sEinQUwQZ9LTDRitiYBCoo0moVZfrh/2ieaut82p87JZf5KSDwnP2c72UgTY0Be8MaGvX1L2Aswum87hFDQ544NQ85pj30sT1x37D6G6wWf6HZ+C6vraiPXdfO09X9MUEYwNwUW4Dm7tRXWyzAgkLv3E303CGJdqGKs7T9cLRtCRVuKbvrxhfb0PQnG0ji4CG3DkSWekffkIFSIY1ok78p6TuknvCsAeUmW2WHwLWYvxDFOmSHAayzocgKL2YtI8Z1YZAj1FdQpD5zTgB9Q2VmkxbLQu+
  template:
    metadata:
      name: pg-billing-owner
      namespace: vtt-staging
    type: kubernetes.io/basic-auth
