---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-identity-owner
  namespace: vtt-staging
spec:
  encryptedData:
    password: AgBhM7c0VSX/ALxcqNlTb5Vr23ManSuz7TdWEWpNQ7a9rroNzZsNPwwOIX9+O1OKQKUS9MfA9cx9CmHzdCr+BwIUiQeT77hD4TguRdZ5ZsDptqDjB+jZeb6A/7HCbDUAFXr3UG26Om9fX7MO0/z/fjBv1tAr/rXtstGf+mMebveio0+q0ciryWCVfSMkv1Ttq8qVHoj6n1Fh2M1WCWpJodmhfbZ0GxfWJfjHwjEbLyaIYCALs0xa3N3nNtVHKEkbGwF2TW8IlOuvfc3Iavm3rNW1Zz9uJTmyXkM7vCOKknEt2rN4qr+RxYgq9YaZmcI157I2zS1rYe+Y1Q850hmgPxafXuG2W4vOimcSNQjZUjheqNkrSJdGXTW490JnKhcKc4z9GYt6EiQ7opzXWr8nsLPU51tL0sfAwq5Qpji+G+HkkG/deiTkCvf+XeMQ2rz6WUsyEYjDTnlwdzyQoO/mhcrwV7JlHQYrS02baINcc0g7Y1ELvib3s1NjNzcLW/VYLJWmvhID02w0trdbHwd+ey1ebjJdlMTa2tvOgE5sFcEMk4hLm0J56MNm2OVsGMZtkt4P/HG6cW4e84Ywx1KzlOP3YYeJ/++oQSku6P4HwT+ec3NXcSVrmOBTojxzFZ+kvIkfeohYr00FQWlN3jZcTKsLeEvWNpkNCRTUv32hqW6m0fgzdkuL/9Aqa9FO9OdJ6JdOmrj8h9SGHNhMdPB+6ZfMviWwse6nVmCh72vZS1031uWaPYy7NZ14tKbCR7MvHXMDL19vn5mnSkvNzTGGiIvxyQ==
    username: AgA2OYDUFSsv3Mamsj5ZtBSI5Qy+eJdr3l+XwW98NubY3/NtsjRRpoBRYhjDQdqhhc2XCQD2/4W4OdeUo6z10a0mf8+J5o3Kg9zpW63cGwGLV/MJ3yfOhOcOMK6ihSHdYMh9h/FINlzzMNXfzbYKQ3KXAoPRtM0gV8y18YhI2pKvwKh0llosGEOuycuVZAKjrVWs++A1TViGWzoAFq1V0zFglhNSC9TYj1oK2k3/p3NcfhjSlE/W4QbN+A980KavwJvYDFP9bwe1mXqvXR3bdkuGAXTqUTH/bjmarhI7CK0e+lGCJBnGSiCcPTFDGYuC5Zc9naHK8JF4iV1rRPlnRx5jQcotFsYPxeO0zqblL7VNX54D+KpMfU7GfA/XFgAX6qMJlzID7t3xzRroo7dilWgTWfZUD/QIA8kizKGmssra3iWr/55Jnv9K9a4CTd4DZeHIpbFaqwDnf59XtbazUdQkEtXG6l/Q51pNvL45Ap3o7ITBo//Nl3VqPHvIHm0le1OftGyPsDL3jM/ss1x9lJQsYJfkCRM3o+3481ekAoaAoraAHH765R0tEv1rsOg5B5ukcpoNE9tgkXPiKn2JKjEztwG68HI9aruC6WZSv7oF1I73dj42DDcJQ2xmShWKAmzXOyw9bx8rjUUZXbeNG5ZRAossvpRo8bRiDeUpSDzNDrVVKo3TwWAXAeKm/W6it51SSuif2vtJzhdLnBqrvA==
  template:
    metadata:
      name: pg-identity-owner
      namespace: vtt-staging
    type: kubernetes.io/basic-auth
