---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: messaging-credentials
  namespace: vtt-staging
spec:
  encryptedData:
    NATS_PASSWORD: AgCDSwXAXYdbvyxypDOIDtwrhRx+7bSgMg3OXd4oibkXqlJMF3fIRDkF84iUaFCc1PjELxYgXS4cJiChumRR+zevnJVHLDppFYnU04eWv2qBsICJb9oTnruYUpRZNpUqC55HxD4ImsinCvKOo0Ox0dx0AldGJYZc+Uam6J5v/hFAtiYbVG+JY1CD/j6C2EY+kJyZ60gKDN9f7+gQ99BDx1EXVypja5EVtDfhP+aMdbw+ZwnsFM0oezUdV4rw0lyTd8YhWGE6BI4YM371VGiOjNBucIF852Ca1qRsBoYjgkeWUsoPumVsqfWeNbw83pnOF+sLGHl1ozhu5cmaqOg1ZCZIxSunfenEZ4zVauOVgfowgEc085jUdyZpyMcuj5hra4ZiazIE5+eI3hOkWypzYSuMO3IofvMAP7iMGgLL5ivgI9xEhwuieS81XZbmIHP2HK4rOEKFp6v/AXSvplRYGMiM76WTfrTdXiijuv0Mvq1ude1WR5FHUt/ej6CqKrQYtinzob6y+KJBiSWI8eCR1fqfScVBO98Qvfk8YjAc7p9Wxds7HV9n/pG/JYarnXmFx7ZyvawJINoQU/elTYGdNBsTQzTeEKdL73BEqqbYuVA0LKIGPL2RyjkOpM49acd7UB/ZYAA4KdHbVX2VBIxMFXdxUVRkHQ2c7HH/YmstUSxvB2Qknf4xu9soGHliBY2wd5x1hSUaae3EW4ibfczUB+MIOBiTNvN4v8kRmwAsMKrsEP3fioQG6ac1zgK6PAP0GkjP0Mitel3Z6iFWhCXAx0I+FQ==
    REDIS_PASSWORD: AgBpZ66r1OwzZZX2qUwiCp2X6g3RM06T8dYlVW1UVrtviJaxbEN94z0R9B1rCoT9Mlg7yrWQ+emg0yrfqqYgYoqWmPx3O1+PBmbZ0GGccNcM0CUwkdouYOk1ScWhpriFJVTmwFCC+36KN7f7RRLKpuWHiKb1rOZfFOEQLE8u8I9jwOCIa/lPrExkpevoHnHFqYVV3KH9zlWRYs+bYpZMLPWpQKlBwvcDF5/Ewkz8Y2lQ7RAUhESC7ee5p9lVcT+Pq+iEFFV2/Q97gcMeQRytMMRfx2F/AuHdrWE4AVH61Mmkcqtw7OZiNpBjWAp8E8sjWnxBbmPF1psjqy+ZFDtNTP582O/TJdAqwxC9d5/9h47zbif37Pu2g3L52XLNJ+GfIwtmfqlaihOMKvs8kz5xEnpbl6KG6UkFwCQM4dP9gb67+hCaFjqDKTB66ucen7I13uj9IReeMAK3jVU4vqkMlgZJKuT/s1uf4CI6NQTTBZD9/7bn3hGKdsW9ZTAeU03D12636GMRc+xXvrfT0ozWnm93Rh84K8EvqHCUW2a1a3V0Tf+zSWzulpvsdP9uHI3y8YDEc91T87U2EeLpwfH21O+vVPt3Dnymfd/8xa32k3lsjuG27YesNFlcOpDaSWqazyd54xH7Bkn9TGjjUdpLoTP6TiEb+5PP5PdjR9TX/3HW7xVMX6O52Sdo0tNlffsCQb1fktQXTDqNV+yA/kYg9/Lf5oxdqc9LuvlFNN/YOfSfw+oa1dWqeyvx/JXaNk+LCPTlUH3sE9TX1w1D/fYzIiYX1A==
  template:
    metadata:
      name: messaging-credentials
      namespace: vtt-staging
    type: Opaque
