---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-campaign-owner
  namespace: vtt-staging
spec:
  encryptedData:
    password: AgCPpZ2F0YR0b/blDpgsk0vtBLyGH8DtnXKcEk5rz3tcvXM4Trws687BUWJ6xGeJ0t/3SOdzZpbqerEp0e3Tt+MAIY8Xhc7YUVZ1NSEuC/2KGFTvVWiMI10yWuipnYM61kn82wGNwx/rpfyv6Vy6Lu6WCM3+vPzi55HU3WB51Su3KrI0bezNE5hmJthGWaDS7YFCj8PcUhy6ZshPDTEvhFSo1cevuPNycMBNw8LZ8IHoPdGzf8kogxUGey4+a1vMyJdKz5po+lRjnDsLohfmLlOsmRN2SSjSmFYtD28vwvDu3rgzOgwqImJNxX3TcHEwb4V9j6syneEFc4eC5+SIL+WibrLGtDs2l2asAaxcApfIoL1AWDFC6iHZaJaYNyQAhAQR0YL7vLkNNJXWVJdqSDFPBbahSnX+5xIkB5oGEkozJiEnuEWuOjiknk9zWBhhbrIVuigq4b6mGzwkANESj3JQoi3Y1Q/lfuKN8JxEStZnSJ5kBmEVr5ZmJhYx885SJgdi0gj/ZJZ1MDrIrL67nlMV4wIjCuoMZWyfNNR7FEHQ4fPoKdNK3HS2+3tNSPcLvFkgXmj28fkcy3Xn6WNvhOdZkA2n4jAGlW+J17pwYhn0Gi8z3i5Tgoigg0UfR6NnVvf3YZsa+PP1WLzUinThOusgDtuZOv0QOMsyikAJBePywEynZttyRpeStnT/jsc3XGtArFIqDh3AZEpSHTSU3b+hEFtz2UmKen+y2s+oJe2s4CjIfiD2Cgj9nGRghXPkeQhFNO0zmwP3dhZyy5X8XepT/w==
    username: AgBh+1Unw4O+9WPGcUfd5GXrIJc7riCk1XnvxshsCgSFkhu6aBTSsJG77XTg7/6/5ckB/QwYeqv1pMxHewhWVYhCwmLmHX3oSMPF18ui7s0UmDBcRS7oswh9VKxViAP+sq1yeQarFp0l/ktjBJ5/jo9DhyMaEagUy8T2s3J0keNRHTlNtixniBC+0FjaY3UqTEaHDEiBSanDvBJSfaS0601mFerfdCnumRLTiUSJImovXH6s3ViK+brU/i6jK2oOtNgQ4+AVq0qjR1cSbf/SJJIefblWDRRcz7UULbmuxTy6xFPW/dlCejTslRCXMcMNvLDfUWcUvv3u6NZp+z9vVZqAL4L6rV5ls3snzTTFqmz+uy5VjSI9Nngv8jD2t92Uio7fgJ/2y+R4j4p6FQs0u7POGJF3zSEtHhVdnRcIz5UzLUMxShaAoY9gAWUbMMyLymwGMs/7h7NPZYsBSse/NoexCuUjw6q+YWZQnm/mBR8P+wUfbxm9faFbpTytwrNW53HmFO7NS0ffRqonaCF6PiH9GHURIGBPV9s04b7rVVvffidWXUEeNmBE1dLRPdAv6Pv4j+wtFyxIouJ7CsCL4mTdETVtHDshRmPOpI1qsqhKJgO7uwUDM7LVCn/PBKLCmYPamgwSpjgzUgd06hFdDXQcRC1UauUWA979TYRIwj7p3tO0bidjzPrycAq6aJZUzHntg/81LjSoXS46OPrCxw==
  template:
    metadata:
      name: pg-campaign-owner
      namespace: vtt-staging
    type: kubernetes.io/basic-auth
