---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-history-owner
  namespace: vtt-staging
spec:
  encryptedData:
    password: AgALHKL37U8u5oGxsW8vAnrbtPX2FlQBvWmWPXqK6pp6rbfhvLIiTGvb8I0sc8/VYmN2JB2DrGX9UgdKLGsi70WX1RdUZNds2DBVKpRo99s+jgb2IjvWp/fl51dVBSNppvMBlcFocI19T4t6z5eLN1nGnQkb2dJ9TnXUZgM0RiZamPKOKglZdRJqn81ttwqQweHHKsQZbGdlcZoGX6gjOmHF91grOKRNb/kV9I4KZHsA9/D18rvI5BZPYKqThg1Q8M56WtBS16T5tF9ov7H4oGXQSzWBthQihQbgJSNP+KlA3cgm23FHmbOms7txiMYR9VDD+oon0J+xnxs6/wL32C1s4koHb+poqyATbluYLKPb/5tEV7CujE0RS12wI0stjrbuuamF9CRgXJtbqxF2EOg9o+G4NMBt9CRYgOoZSoFmGnMZHLZQuAfgHx+bvD3IZ3C0DLDpARLqbTgXBND4cNr9MhAVwwbKntBF7mBh/ue5/ewfyUIpvvFJ2psL1fcxsiFKqLUlkesF5Mt1gN3HGsrxKr/knncs51xJFaCaevirZc2Jl4z4rsCYf8zMV+4oSu3iP6i+bbZ+F2xKJHpxdfdjJjANKNIL/wVnA1t6CE98qhufvqAGTA5A7TKMBJOTwFXyIdGC9z7mimHN0bNjXg6MeNZhnMib+33o+OH3/LeJ446YPM9j4RKQtj0Mck08QiCnR9/pq2GsReZc4jn5CeHmK47TmWm7mowjDmVumuExVZDnymedu8jWzUOF65UZTwYgv9cRcsJq/Srg6gRNBuCMqQ==
    username: AgC0aFi9Fz3AEdYrBNYPON7hj72dZYHhjYyM+zchVksqlt3WF8Qg2zVAJuq9a0jbzCmaHc+FEwMztFvYuUmpG4GVONtYvGdTmWETpkpuF+Cp2/Mh3g7cd9hDoUigq/uWmmxKOffxdGTyBn5MeuPJlaL3UUwFOYSSnHznsb4JQemG4iEvb8fEkw3ON5tHWWRSJXYEvH3/SQ4vfq40CUwEtlUOmkL08MIXLfPRopX+bnJw7o0zh5oMV0L4U4oCkjVOTs1pG+hglhDiyQmXzQfHJjXqX5RSmNoHzRPG2cetWEzUn4+CZa2tcNTm2M98pih4krHNwwZu73ylM1P+zH9ZIpR8TM6J+Tjd+iw5ja6yaLxVDEVfNHxHf3m6HEtUXw/iCCiaN0vqefiI7lljc12IyCSi0FpoNGIKloDqvG0TvztzmWq5bQDhJEfrts+oOShKFu0k0QA2XGcY14LYjha80ETUEXu/JIAfsocrxOsHv4yfubSOszFOe7ejYg0Vg8eccWFSn8ME1YOjCYlBO6fyUnnoC0W2pgjuox6OZxwnbiRVXd1ljGjiJNsvtMtZpEDUpidDqe1jmOuvJb+s+81nvnJdTWGJdofWQTvRYs8JSQbYgHXE0R1g5nHlgnZen/+VmTnx1A+Bjo/Z7M/JlZlswFbBu6NLpmZLEb06ozMzwMViQnnFuvnXouJO+koJZuF4EY2bD1sqdYzO50LV2bjD
  template:
    metadata:
      name: pg-history-owner
      namespace: vtt-staging
    type: kubernetes.io/basic-auth
