import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Aclonica } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/toggledarkmode"
import { CompetencesProvider } from "@/contexts/CompetencesContext"


const Aclonica_init = Aclonica({
  subsets: ["latin"],
  weight: ["400"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "JDR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body
        className="antialiased"
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <CompetencesProvider>
         
            {children}
          </CompetencesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
