import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { CompetencesProvider } from "@/contexts/CompetencesContext"
import { GameProvider } from '@/contexts/GameContext';
import { CharacterProvider } from '@/contexts/CharacterContext';
import { UndoRedoProvider } from '@/contexts/UndoRedoContext';
import { Toaster } from "@/components/ui/sonner"



import { IM_Fell_English, Cinzel, Caveat, MedievalSharp, Inter } from 'next/font/google';

const imFellEnglish = IM_Fell_English({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-body',
  display: 'swap',
});

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-title',
  display: 'swap',
});

const caveat = Caveat({
  subsets: ['latin'],
  variable: '--font-hand',
  display: 'swap',
});

const medieval = MedievalSharp({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-medieval',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-modern',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "JDR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      suppressHydrationWarning
      className={`${imFellEnglish.variable} ${cinzel.variable} ${caveat.variable} ${medieval.variable} ${inter.variable}`}
    >
      <body
        className="antialiased"
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <GameProvider>
            <CharacterProvider>
              <CompetencesProvider>
                <UndoRedoProvider>
                  <Toaster position="top-right" />
                  {children}
                </UndoRedoProvider>
              </CompetencesProvider>
            </CharacterProvider>
          </GameProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
