import { getAssetUrl } from '@/lib/asset-loader';

export type SkinEffectType = 'metallic' | 'gem' | 'glass' | 'stone' | 'magic' | 'dark' | 'cyber' | 'organic' | 'celestial' | 'cursed';
export type ParticleType = 'none' | 'fire' | 'ice' | 'sparkle' | 'smoke' | 'gold_dust' | 'silver_dust' | 'magic' | 'electric' | 'void' | 'nebula' | 'blood';
export type CriticalType = 'success' | 'fail' | null;

export interface DiceSkin {
    id: string;
    name: string;
    bodyColor: string;
    edgeColor: string;
    borderColor: string;
    textColor: string;
    shadowColor: string;
    metalness: number;
    roughness: number;
    envMapIntensity: number;
    effectType: SkinEffectType;
    emissive: string;
    emissiveIntensity: number;
    opacity: number;
    innerGlow: boolean;
    innerGlowColor: string;
    innerGlowIntensity: number;
    rimLight: boolean;
    rimLightColor: string;
    particleType: ParticleType;
    particleColor: string;
    particleColor2?: string;
    // Textures (optional)
    textureMap?: string;
    price: number;
    description?: string;
    rarity?: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
}

export const DICE_SKINS: Record<string, DiceSkin> = {
    gold: {
        id: 'gold',
        name: 'Or Royal',
        bodyColor: '#c9a227',
        edgeColor: '#ffe066',
        borderColor: '#ffd700',
        textColor: '#1a1000',
        shadowColor: '#000000',
        metalness: 0.95,
        roughness: 0.12,
        envMapIntensity: 2.0,
        effectType: 'metallic',
        emissive: '#ff9500',
        emissiveIntensity: 0.15,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#ffffff',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#ffe066',
        particleType: 'gold_dust',
        particleColor: '#ffd700',
        particleColor2: '#ffaa00',
        price: 0,
        description: "L'élégance intemporelle pour les aventuriers fortunés.",
        rarity: 'common'
    },
    silver: {
        id: 'silver',
        name: 'Argent',
        bodyColor: '#c0c0c0',
        edgeColor: '#ffffff',
        borderColor: '#e8e8e8',
        textColor: '#1a1a2e',
        shadowColor: '#000000',
        metalness: 1.0,
        roughness: 0.05,
        envMapIntensity: 2.5,
        effectType: 'metallic',
        emissive: '#ffffff',
        emissiveIntensity: 0.1,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#ffffff',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'silver_dust',
        particleColor: '#ffffff',
        particleColor2: '#c0c0c0',
        price: 0,
        description: "Brillant et pur, efficace contre les lycanthropes.",
        rarity: 'common'
    },
    ruby: {
        id: 'ruby',
        name: 'Rubis',
        bodyColor: '#cc0033',
        edgeColor: '#ff3366',
        borderColor: '#ff6699',
        textColor: '#ffffff',
        shadowColor: '#330011',
        metalness: 0.3,
        roughness: 0.1,
        envMapIntensity: 2.0,
        effectType: 'gem',
        emissive: '#ff0033',
        emissiveIntensity: 0.4,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#ff3366',
        innerGlowIntensity: 0.8,
        rimLight: true,
        rimLightColor: '#ff6699',
        particleType: 'none',
        particleColor: '#ff3366',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/rubis_diffuse.jpg'),
        price: 250,
        description: "Une gemme ardente pulsant d'énergie magique.",
        rarity: 'rare'
    },
    obsidian: {
        id: 'obsidian',
        name: 'Obsidienne',
        bodyColor: '#0a0a0a',
        edgeColor: '#1a1a2e',
        borderColor: '#6633ff',
        textColor: '#aa88ff',
        shadowColor: '#000000',
        metalness: 0.95,
        roughness: 0.02,
        envMapIntensity: 3.0,
        effectType: 'dark',
        emissive: '#4400aa',
        emissiveIntensity: 0.25,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#6633ff',
        innerGlowIntensity: 0.5,
        rimLight: true,
        rimLightColor: '#8855ff',
        particleType: 'none',
        particleColor: '#6633ff',
        particleColor2: '#220044',
        price: 500,
        description: "Forgé dans les ténèbres, pour ceux qui embrassent l'ombre.",
        rarity: 'epic'
    },
    jade: {
        id: 'jade',
        name: 'Jade',
        bodyColor: '#00b377',
        edgeColor: '#33ffaa',
        borderColor: '#66ffcc',
        textColor: '#003322',
        shadowColor: '#001a11',
        metalness: 0.2,
        roughness: 0.4,
        envMapIntensity: 1.2,
        effectType: 'stone',
        emissive: '#00ff88',
        emissiveIntensity: 0.1,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#33ff99',
        innerGlowIntensity: 0.3,
        rimLight: false,
        rimLightColor: '#00ff88',
        particleType: 'none',
        particleColor: '#33ff99',
        particleColor2: '#00ff88',
        textureMap: getAssetUrl('/textures/jade.jpg'),
        price: 125,
        description: "Symbole de sérénité et de chance.",
        rarity: 'uncommon'
    },
    crystal: {
        id: 'crystal',
        name: 'Cristal',
        bodyColor: '#eeeeff',
        edgeColor: '#ffffff',
        borderColor: '#aaccff',
        textColor: '#0044aa',
        shadowColor: '#6688cc',
        metalness: 0.1,
        roughness: 0.02,
        envMapIntensity: 3.5,
        effectType: 'glass',
        emissive: '#aaccff',
        emissiveIntensity: 0.2,
        opacity: 0.7,
        innerGlow: true,
        innerGlowColor: '#ffffff',
        innerGlowIntensity: 1.0,
        rimLight: true,
        rimLightColor: '#aaccff',
        particleType: 'none',
        particleColor: '#ffffff',
        particleColor2: '#aaccff',
        price: 250,
        description: "Transparent comme vos intentions... ou pas.",
        rarity: 'rare'
    },
    sapphire: {
        id: 'sapphire',
        name: 'Saphir',
        bodyColor: '#0044cc',
        edgeColor: '#3377ff',
        borderColor: '#66aaff',
        textColor: '#ffffff',
        shadowColor: '#001144',
        metalness: 0.35,
        roughness: 0.08,
        envMapIntensity: 2.2,
        effectType: 'gem',
        emissive: '#0066ff',
        emissiveIntensity: 0.35,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#3399ff',
        innerGlowIntensity: 0.7,
        rimLight: true,
        rimLightColor: '#66ccff',
        particleType: 'none',
        particleColor: '#3399ff',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/saphire_diffuse.jpg'),
        price: 250,
        description: "Aussi profond que l'océan, aussi dur que l'acier.",
        rarity: 'rare'
    },
    amethyst: {
        id: 'amethyst',
        name: 'Améthyste',
        bodyColor: '#7722aa',
        edgeColor: '#aa44dd',
        borderColor: '#cc77ff',
        textColor: '#ffffff',
        shadowColor: '#220044',
        metalness: 0.3,
        roughness: 0.12,
        envMapIntensity: 2.0,
        effectType: 'gem',
        emissive: '#9933ff',
        emissiveIntensity: 0.35,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#bb66ff',
        innerGlowIntensity: 0.6,
        rimLight: true,
        rimLightColor: '#dd99ff',
        particleType: 'none',
        particleColor: '#bb66ff',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/amethyst_diffuse.jpg'),
        price: 250,
        description: "Mystique et royale, favorisée par les mages.",
        rarity: 'rare'
    },
    inferno: {
        id: 'inferno',
        name: 'Inferno',
        bodyColor: '#ff3300',
        edgeColor: '#ff6600',
        borderColor: '#ffaa00',
        textColor: '#ffffff',
        shadowColor: '#330000',
        metalness: 0.4,
        roughness: 0.3,
        envMapIntensity: 1.5,
        effectType: 'magic',
        emissive: '#ff4400',
        emissiveIntensity: 0.8,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#ffaa00',
        innerGlowIntensity: 1.2,
        rimLight: true,
        rimLightColor: '#ff6600',
        particleType: 'none', // Removed fire
        particleColor: '#ff6600',
        particleColor2: '#ffaa00',
        price: 500,
        description: "Brûle d'une flamme éternelle qui ne consume que vos ennemis.",
        rarity: 'epic'
    },
    frost: {
        id: 'frost',
        name: 'Givre',
        bodyColor: '#88ccff',
        edgeColor: '#aaeeff',
        borderColor: '#ffffff',
        textColor: '#003366',
        shadowColor: '#004488',
        metalness: 0.2,
        roughness: 0.15,
        envMapIntensity: 2.5,
        effectType: 'magic',
        emissive: '#66ddff',
        emissiveIntensity: 0.5,
        opacity: 0.8,
        innerGlow: true,
        innerGlowColor: '#aaeeff',
        innerGlowIntensity: 0.9,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none', // Removed ice
        particleColor: '#aaeeff',
        particleColor2: '#ffffff',
        price: 250,
        description: "Froid comme la mort, tranchant comme un blizzard.",
        rarity: 'rare'
    },
    // NEW SKINS
    cyber_neon: {
        id: 'cyber_neon',
        name: 'Cyber Neon',
        bodyColor: '#050510',
        edgeColor: '#00ffcc',
        borderColor: '#00ffcc',
        textColor: '#ff00aa',
        shadowColor: '#001111',
        metalness: 0.9,
        roughness: 0.1,
        envMapIntensity: 1.5,
        effectType: 'cyber',
        emissive: '#004433',
        emissiveIntensity: 0.3,
        opacity: 0.95,
        innerGlow: true,
        innerGlowColor: '#00ffcc',
        innerGlowIntensity: 0.8,
        rimLight: true,
        rimLightColor: '#ff00aa',
        particleType: 'none',
        particleColor: '#00ffcc',
        particleColor2: '#ff00aa',
        price: 1250,
        description: "Une technologie perdue d'une autre dimension.",
        rarity: 'legendary'
    },
    bleu_marble: {
        id: 'bleu_marble',
        name: 'Marbre Bleu',
        bodyColor: '#004488',
        edgeColor: '#ffd700',
        borderColor: '#ffffff',
        textColor: '#ffffff',
        shadowColor: '#000033',
        metalness: 0.1,
        roughness: 0.1,
        envMapIntensity: 2.0,
        effectType: 'stone',
        emissive: '#000000',
        emissiveIntensity: 0,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#ffd700',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/marblebleu_diffuse.jpg'),
        price: 125,
        description: "Élégance classique avec une touche royale.",
        rarity: 'legendary'
    },
    cosmos: {
        id: 'cosmos',
        name: 'Cosmos',
        bodyColor: '#1a0033',
        edgeColor: '#9933ff',
        borderColor: '#ffffff',
        textColor: '#ffffff',
        shadowColor: '#000000',
        metalness: 0.5,
        roughness: 0.2,
        envMapIntensity: 2.0,
        effectType: 'celestial',
        emissive: '#4b0082',
        emissiveIntensity: 0.3,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#9933ff',
        innerGlowIntensity: 0.5,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#9933ff',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/cosmos_diffuse.jpeg'),
        price: 1250,
        description: "Contient des galaxies entières dans chaque face.",
        rarity: 'legendary'
    },
    space: {
        id: 'space',
        name: 'Espace',
        bodyColor: '#1a0033',
        edgeColor: '#9933ff',
        borderColor: '#ffffff',
        textColor: '#ffffff',
        shadowColor: '#000000',
        metalness: 0.3,
        roughness: 0.2,
        envMapIntensity: 2.0,
        effectType: 'celestial',
        emissive: '#000033',
        emissiveIntensity: 0.3,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#00ffff',
        innerGlowIntensity: 0.4,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#00ffff',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/space_diifuse.avif'),
        price: 500,
        description: "Le vide infini entre les étoiles.",
        rarity: 'epic'
    },
    ocean: {
        id: 'ocean',
        name: 'Océan',
        bodyColor: '#006994', // Ocean blue
        edgeColor: '#00bfff', // Deep sky blue
        borderColor: '#ffffff', // White foam
        textColor: '#ffffff',
        shadowColor: '#000033',
        metalness: 0.4,
        roughness: 0.1, // Wet look
        envMapIntensity: 2.5,
        effectType: 'organic', // or magic/glass
        emissive: '#004466',
        emissiveIntensity: 0.2,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#00ffff', // Cyan glow
        innerGlowIntensity: 0.3,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#00bfff',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/ocean_diffuse.webp'),
        price: 250,
        description: "Pour ceux qui entendent l'appel du large.",
        rarity: 'rare'
    },
    merveille: {
        id: 'merveille',
        name: 'Merveille',
        bodyColor: '#004488',
        edgeColor: '#ffd700',
        borderColor: '#ffffff',
        textColor: '#ffffff',
        shadowColor: '#000033',
        metalness: 0.1,
        roughness: 0.1,
        envMapIntensity: 2.0,
        effectType: 'stone',
        emissive: '#000000',
        emissiveIntensity: 0,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#ffd700',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/merveille_diffuse.png'),
        price: 1250,
        description: "Une merveille d'artisanat magique.",
        rarity: 'legendary'
    },
    ancient_bone: {
        id: 'ancient_bone',
        name: 'Os Ancien',
        bodyColor: '#e3dac9',
        edgeColor: '#d4c5a9',
        borderColor: '#8a7e68',
        textColor: '#3b2f21',
        shadowColor: '#2b2216',
        metalness: 0.1,
        roughness: 0.8, // Matte bone
        envMapIntensity: 0.5,
        effectType: 'organic',
        emissive: '#000000',
        emissiveIntensity: 0,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: false,
        rimLightColor: '#000000',
        particleType: 'none',
        particleColor: '#d4c5a9',
        particleColor2: '#e3dac9',
        price: 125,
        description: "Sculpté dans les os d'une créature oubliée.",
        rarity: 'uncommon'
    },
    void_walker: {
        id: 'void_walker',
        name: 'Marcheur du Vide',
        bodyColor: '#000000',
        edgeColor: '#111111',
        borderColor: '#4b0082', // Indigo
        textColor: '#e6e6fa', // Lavender
        shadowColor: '#000000',
        metalness: 0.8,
        roughness: 0.2,
        envMapIntensity: 1.0,
        effectType: 'dark',
        emissive: '#1a0033',
        emissiveIntensity: 0.4,
        opacity: 0.95,
        innerGlow: true,
        innerGlowColor: '#4b0082',
        innerGlowIntensity: 0.6,
        rimLight: true,
        rimLightColor: '#8a2be2',
        particleType: 'none',
        particleColor: '#4b0082',
        particleColor2: '#000000',
        price: 500,
        description: "Il n'y a rien ici... absolument rien.",
        rarity: 'epic'
    },
    celestial_starlight: {
        id: 'celestial_starlight',
        name: 'Lumière Stellaire',
        bodyColor: '#0d1b2a',
        edgeColor: '#415a77',
        borderColor: '#e0e1dd',
        textColor: '#ffdd00',
        shadowColor: '#000000',
        metalness: 0.6,
        roughness: 0.2,
        envMapIntensity: 3.0,
        effectType: 'celestial',
        emissive: '#1b263b',
        emissiveIntensity: 0.3,
        opacity: 0.9,
        innerGlow: true,
        innerGlowColor: '#ffffff',
        innerGlowIntensity: 0.4,
        rimLight: true,
        rimLightColor: '#778da9',
        particleType: 'none',
        particleColor: '#ffffff',
        particleColor2: '#ffdd00',
        price: 1250,
        description: "Guide les voyageurs perdus dans la nuit.",
        rarity: 'legendary'
    },
    blood_pact: {
        id: 'blood_pact',
        name: 'Pacte de Sang',
        bodyColor: '#3a0404',
        edgeColor: '#610b0b',
        borderColor: '#8a1c1c',
        textColor: '#ffcccc',
        shadowColor: '#1a0000',
        metalness: 0.4,
        roughness: 0.4,
        envMapIntensity: 1.0,
        effectType: 'organic',
        emissive: '#520000',
        emissiveIntensity: 0.3,
        opacity: 0.98,
        innerGlow: true,
        innerGlowColor: '#ff0000',
        innerGlowIntensity: 0.3,
        rimLight: true,
        rimLightColor: '#ff3333',
        particleType: 'none',
        particleColor: '#8a1c1c',
        particleColor2: '#3a0404',
        price: 500,
        description: "Un serment qui ne peut être brisé.",
        rarity: 'epic'
    },
    steampunk_copper: {
        id: 'steampunk_copper',
        name: 'Steampunk Cuivre',
        bodyColor: '#b87333',
        edgeColor: '#cd7f32',
        borderColor: '#d4af37', // Brass details
        textColor: '#2a1a0a',
        shadowColor: '#1a0f05',
        metalness: 0.9,
        roughness: 0.3, // Brushed metal
        envMapIntensity: 1.8,
        effectType: 'metallic',
        emissive: '#b87333',
        emissiveIntensity: 0.1,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#d4af37',
        particleType: 'none',
        particleColor: '#d4af37',
        particleColor2: '#b87333',
        price: 250,
        description: "Rouages et vapeur, pour l'ingénieur moderne.",
        rarity: 'rare'
    },
    royal_marble: {
        id: 'royal_marble',
        name: 'Marbre Royal',
        bodyColor: '#f5f5f5',
        edgeColor: '#ffffff',
        borderColor: '#e0c090', // Soft Gold
        textColor: '#d4af37', // Gold
        shadowColor: '#cccccc',
        metalness: 0.1,
        roughness: 0.1, // Polished stone
        envMapIntensity: 2.0,
        effectType: 'stone',
        emissive: '#000000',
        emissiveIntensity: 0,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#d4af37',
        particleColor2: '#ffffff',
        price: 250,
        description: "Digne d'un trône.",
        rarity: 'rare'
    },
    galactic_nebula: {
        id: 'galactic_nebula',
        name: 'Nébuleuse',
        bodyColor: '#1a0033', // Deep purple
        edgeColor: '#4b0082',
        borderColor: '#00ffff', // Cyan accents
        textColor: '#ffffff',
        shadowColor: '#000000',
        metalness: 0.7,
        roughness: 0.2,
        envMapIntensity: 2.5,
        effectType: 'celestial',
        emissive: '#2a0044',
        emissiveIntensity: 0.2,
        opacity: 0.95,
        innerGlow: true,
        innerGlowColor: '#cc00ff', // Magenta glow
        innerGlowIntensity: 0.4,
        rimLight: true,
        rimLightColor: '#00ffff',
        particleType: 'none', // Uses texture effect mostly
        particleColor: '#00ffff',
        particleColor2: '#ff00ff',
        price: 1250,
        description: "Là où naissent les étoiles.",
        rarity: 'legendary'
    },
    dragon_scale: {
        id: 'dragon_scale',
        name: 'Écaille de Dragon',
        bodyColor: '#004d40', // Deep Teal
        edgeColor: '#00695c',
        borderColor: '#ffd700', // Gold borders
        textColor: '#ffd700',
        shadowColor: '#002222',
        metalness: 0.8, // Metallic scales
        roughness: 0.15,
        envMapIntensity: 1.5,
        effectType: 'organic',
        emissive: '#004d40',
        emissiveIntensity: 0.1,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#00ffaa',
        innerGlowIntensity: 0.2,
        rimLight: true,
        rimLightColor: '#bf9b30', // Gold rim
        particleType: 'none',
        particleColor: '#ffd700',
        particleColor2: '#004d40',
        price: 1250,
        description: "Dur, brillant et extrêmement précieux.",
        rarity: 'legendary'
    },
    moonstone: {
        id: 'moonstone',
        name: 'Pierre de Lune',
        bodyColor: '#f0f8ff', // Alice Blue
        edgeColor: '#ffffff',
        borderColor: '#b0c4de', // Light Steel Blue
        textColor: '#5f9ea0', // Cadet Blue
        shadowColor: '#8899aa',
        metalness: 0.1,
        roughness: 0.05, // Very smooth
        envMapIntensity: 3.0,
        effectType: 'gem',
        emissive: '#e6e6fa', // Lavender
        emissiveIntensity: 0.3,
        opacity: 0.85, // Slightly translucent
        innerGlow: true,
        innerGlowColor: '#ffffff',
        innerGlowIntensity: 0.8,
        rimLight: true,
        rimLightColor: '#afeeee', // Pale Turquoise
        particleType: 'none',
        particleColor: '#ffffff',
        particleColor2: '#b0c4de',
        price: 1250,
        description: "Baignée dans la lumière de séluné.",
        rarity: 'legendary'
    },
    bois_noble: {
        id: 'bois_noble',
        name: 'Bois Noble',
        bodyColor: '#5c4033', // Warm walnut brown (fallback)
        edgeColor: '#8b6914', // Golden oak highlights
        borderColor: '#d4a76a', // Light wood grain accent
        textColor: '#f5e6c8', // Cream/ivory inlay
        shadowColor: '#2a1a0a',
        metalness: 0, // Wood is not metallic
        roughness: 0.75, // More matte wood texture
        envMapIntensity: 0.3, // Low reflection
        effectType: 'organic',
        emissive: '#3d2817', // Subtle warm glow from within
        emissiveIntensity: 0.05,
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#d4a76a', // Warm golden undertone
        innerGlowIntensity: 0.1,
        rimLight: true,
        rimLightColor: '#c9a66b', // Honey colored rim
        particleType: 'none',
        particleColor: '#d4a76a',
        particleColor2: '#5c4033',
        // Wood texture
        textureMap: getAssetUrl('/textures/wood_diffuse.png'),
        price: 50,
        description: "Simple, robuste et fiable. Comme un bon nain.",
        rarity: 'common'
    },
    marbre_blanc: {
        id: 'marbre_blanc',
        name: 'Marbre Blanc',
        bodyColor: '#f5f5f5', // Fallback white
        edgeColor: '#e0e0e0',
        borderColor: '#d4af37', // Gold accent
        textColor: '#2c2c2c', // Dark grey text
        shadowColor: '#aaaaaa',
        metalness: 0.1,
        roughness: 0.15, // Polished marble
        envMapIntensity: 1.5,
        effectType: 'stone',
        emissive: '#000000',
        emissiveIntensity: 0,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#ffffff',
        particleColor2: '#e0e0e0',
        textureMap: getAssetUrl('/textures/marble_diffuse.png'),
        price: 125,
        description: "Poli à la perfection pour les temples sacrés.",
        rarity: 'uncommon'
    },
    cuir_ancien: {
        id: 'cuir_ancien',
        name: 'Cuir Ancien',
        bodyColor: '#3d2b1f', // Fallback dark brown
        edgeColor: '#5c4033',
        borderColor: '#8b7355', // Lighter brown accent
        textColor: '#d4a76a', // Gold/tan text
        shadowColor: '#1a120b',
        metalness: 0,
        roughness: 0.85, // Matte leather
        envMapIntensity: 0.3,
        effectType: 'organic',
        emissive: '#1a0f0a',
        emissiveIntensity: 0.05,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#8b7355',
        particleType: 'none',
        particleColor: '#8b7355',
        particleColor2: '#3d2b1f',
        textureMap: getAssetUrl('/textures/leather_diffuse.png'),
        price: 50,
        description: "Sent le vieux livre et l'aventure.",
        rarity: 'common'
    },
    pierre_donjon: {
        id: 'pierre_donjon',
        name: 'Pierre de Donjon',
        bodyColor: '#5a5a5a', // Fallback grey
        edgeColor: '#4a4a4a',
        borderColor: '#3d5c3d', // Moss green accent
        textColor: '#494949ff', // Light grey text
        shadowColor: '#2a2a2a',
        metalness: 0,
        roughness: 0.95, // Very rough stone
        envMapIntensity: 0.2,
        effectType: 'stone',
        emissive: '#000000',
        emissiveIntensity: 0,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#6b8e6b', // Moss green rim
        particleType: 'none',
        particleColor: '#6b8e6b',
        particleColor2: '#5a5a5a',
        textureMap: getAssetUrl('/textures/stone_diffuse.png'),
        price: 0,
        description: "Aussi froid que le sol d'un cachot.",
        rarity: 'common'
    },
    fer_rouille: {
        id: 'fer_rouille',
        name: 'Fer Rouillé',
        bodyColor: '#5a4a3a', // Fallback rusty brown
        edgeColor: '#8b4513',
        borderColor: '#cd853f', // Peru/rust
        textColor: '#ffd700', // Gold text for contrast
        shadowColor: '#2a1a0a',
        metalness: 0.6,
        roughness: 0.8, // Rough oxidized surface
        envMapIntensity: 0.5,
        effectType: 'metallic',
        emissive: '#ff4500',
        emissiveIntensity: 0.1,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#cd853f',
        particleType: 'none',
        particleColor: '#cd853f',
        particleColor2: '#5a4a3a',
        textureMap: getAssetUrl('/textures/rust_diffuse.png'),
        price: 25,
        description: "Oublié depuis longtemps, mais toujours solide.",
        rarity: 'common'
    },
    roche_volcanique: {
        id: 'roche_volcanique',
        name: 'Roche Volcanique',
        bodyColor: '#1a1a1a', // Fallback black
        edgeColor: '#ff4500', // Orange lava
        borderColor: '#ff6600',
        textColor: '#ffcc00', // Bright gold
        shadowColor: '#000000',
        metalness: 0.2,
        roughness: 0.9, // Very rough basalt
        envMapIntensity: 0.3,
        effectType: 'magic',
        emissive: '#ff4500',
        emissiveIntensity: 0.6, // Glowing lava
        opacity: 1,
        innerGlow: true,
        innerGlowColor: '#ff4500',
        innerGlowIntensity: 0.5,
        rimLight: true,
        rimLightColor: '#ff6600',
        particleType: 'none',
        particleColor: '#ff4500',
        particleColor2: '#ff6600',
        textureMap: getAssetUrl('/textures/lava_diffuse.png'),
        price: 250,
        description: "Attention, c'est chaud !",
        rarity: 'rare'
    },
    glace_eternelle: {
        id: 'glace_eternelle',
        name: 'Glace Éternelle',
        bodyColor: '#b0e0e6', // Fallback pale blue
        edgeColor: '#e0ffff',
        borderColor: '#ffffff',
        textColor: '#003366', // Dark blue text
        shadowColor: '#4682b4',
        metalness: 0.1,
        roughness: 0.1, // Smooth ice
        envMapIntensity: 2.5, // High reflectivity
        effectType: 'glass',
        emissive: '#add8e6',
        emissiveIntensity: 0.2,
        opacity: 0.85, // Slightly transparent
        innerGlow: true,
        innerGlowColor: '#e0ffff',
        innerGlowIntensity: 0.5,
        rimLight: true,
        rimLightColor: '#ffffff',
        particleType: 'none',
        particleColor: '#e0ffff',
        particleColor2: '#ffffff',
        textureMap: getAssetUrl('/textures/ice_diffuse.png'),
        price: 250,
        description: "Ne fond jamais, même dans un volcan.",
        rarity: 'rare'
    },
    ecorce_ancienne: {
        id: 'ecorce_ancienne',
        name: 'Écorce Ancienne',
        bodyColor: '#3d3d2d', // Fallback dark bark
        edgeColor: '#4a4a3a',
        borderColor: '#6b8e23', // Olive green lichen
        textColor: '#c0c0a0', // Light tan
        shadowColor: '#1a1a10',
        metalness: 0,
        roughness: 0.95, // Very rough bark
        envMapIntensity: 0.2,
        effectType: 'organic',
        emissive: '#2d2d1d',
        emissiveIntensity: 0.05,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#6b8e23',
        particleType: 'none',
        particleColor: '#6b8e23',
        particleColor2: '#3d3d2d',
        textureMap: getAssetUrl('/textures/bark_diffuse.png'),
        price: 125,
        description: "La nature reprend toujours ses droits.",
        rarity: 'uncommon'
    },
    parchemin_ancien: {
        id: 'parchemin_ancien',
        name: 'Parchemin Ancien',
        bodyColor: '#f5deb3', // Fallback wheat
        edgeColor: '#d2b48c', // Tan edges
        borderColor: '#8b4513', // Sienna ink
        textColor: '#4a3728', // Dark brown ink
        shadowColor: '#8b7355',
        metalness: 0,
        roughness: 0.7, // Paper texture
        envMapIntensity: 0.3,
        effectType: 'organic',
        emissive: '#d2b48c',
        emissiveIntensity: 0.05,
        opacity: 1,
        innerGlow: false,
        innerGlowColor: '#000000',
        innerGlowIntensity: 0,
        rimLight: true,
        rimLightColor: '#d2b48c',
        particleType: 'none',
        particleColor: '#d2b48c',
        particleColor2: '#f5deb3',
        textureMap: getAssetUrl('/textures/parchment_diffuse.png'),
        price: 50,
        description: "Les mots ont un pouvoir.",
        rarity: 'common'
    }
};

// Default skin
export const DEFAULT_SKIN = DICE_SKINS.gold;

// Helper to get skin by ID or return default
export const getSkinById = (skinId: string): DiceSkin => {
    return DICE_SKINS[skinId] || DEFAULT_SKIN;
};
