#!/usr/bin/env node

/**
 * Import asset mappings from JSON to Firestore
 * 
 * This script reads the asset-mappings.json file generated by the upload script
 * and imports all entries into the Firestore 'assets-mapping' collection.
 * 
 * Usage:
 *   npx tsx scripts/import-to-firestore.ts
 */

// Load environment variables
import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

import { readFileSync } from 'fs';
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, writeBatch, doc } from 'firebase/firestore';

// Firebase configuration
const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "AIzaSyDrc70mfENCh6gCd5uJmeVbWJ98lcD6mQY",
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || "test-b4364.firebaseapp.com",
    databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL || "https://test-b4364-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || "test-b4364",
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || "test-b4364.appspot.com",
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "260245361856",
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || "1:260245361856:web:99808b241e1a7c1e25c925",
    measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || "G-TT348Z0BVP"
};

interface AssetMapping {
    name: string;
    path: string;
    localPath: string;
    category: string;
    type: string;
    size: number;
    uploadedAt: string;
}

async function importToFirestore() {
    console.log('📥 Importing Asset Mappings to Firestore');
    console.log('==========================================\n');

    // Initialize Firebase
    const app = initializeApp(firebaseConfig);
    const db = getFirestore(app);

    // Read the JSON file
    const jsonPath = path.join(process.cwd(), 'public', 'asset-mappings.json');
    console.log(`📄 Reading mappings from ${jsonPath}...`);

    let mappings: AssetMapping[];
    try {
        const jsonContent = readFileSync(jsonPath, 'utf-8');
        mappings = JSON.parse(jsonContent);
        console.log(`✅ Found ${mappings.length} asset mappings\n`);
    } catch (error) {
        console.error('❌ Error reading JSON file:', error);
        console.error('\nMake sure the upload script has completed and generated asset-mappings.json');
        process.exit(1);
    }

    // Import to Firestore in batches (max 500 per batch)
    console.log('💾 Importing to Firestore...\n');
    const batchSize = 500;
    const totalBatches = Math.ceil(mappings.length / batchSize);

    for (let i = 0; i < mappings.length; i += batchSize) {
        const batchNum = Math.floor(i / batchSize) + 1;
        const batchMappings = mappings.slice(i, i + batchSize);

        try {
            const batch = writeBatch(db);
            const assetsCollection = collection(db, 'assets-mapping');

            for (const mapping of batchMappings) {
                const docRef = doc(assetsCollection);
                batch.set(docRef, {
                    ...mapping,
                    uploadedAt: new Date(mapping.uploadedAt),
                });
            }

            await batch.commit();
            console.log(`✅ Batch ${batchNum}/${totalBatches} imported (${batchMappings.length} documents)`);
        } catch (error) {
            console.error(`❌ Error importing batch ${batchNum}:`, error);
            throw error;
        }
    }

    console.log('\n🎉 Import complete!');
    console.log(`📊 Total assets imported: ${mappings.length}`);
}

// Run the import
importToFirestore().catch(error => {
    console.error('💥 Fatal error:', error);
    process.exit(1);
});
