import { NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import path from 'path';

export const dynamic = 'force-dynamic';

interface MapFile {
    name: string;
    path: string;
    category: string;
    type: 'image' | 'video';
}

interface AssetMapping {
    name: string;
    path: string;
    localPath: string;
    category: string;
    type: string;
    size: number;
    uploadedAt: string;
}

/**
 * GET /api/maps
 * Fetch all map backgrounds from R2 via local JSON mapping
 * 
 * This route reads the asset-mappings.json file generated by the R2 upload script
 * and filters for Map and Cartes categories
 */
export async function GET() {
    try {
        // Read the asset mappings JSON file
        const jsonPath = path.join(process.cwd(), 'public', 'asset-mappings.json');
        let mappings: AssetMapping[];

        try {
            const jsonContent = readFileSync(jsonPath, 'utf-8');
            mappings = JSON.parse(jsonContent);
        } catch (error) {
            console.error('Error reading asset-mappings.json:', error);
            return NextResponse.json(
                { error: 'Asset mappings not found. Please run the R2 migration script first.' },
                { status: 404 }
            );
        }

        // Filter for Map and Cartes categories
        const allMaps: MapFile[] = mappings
            .filter(m => m.category?.startsWith('Map') || m.category?.startsWith('Cartes'))
            .map(m => ({
                name: m.name,
                path: m.path, // R2 public URL
                category: m.category,
                type: m.type as 'image' | 'video',
            }));

        // Group by category for easier navigation
        const grouped = allMaps.reduce((acc, map) => {
            if (!acc[map.category]) {
                acc[map.category] = [];
            }
            acc[map.category].push(map);
            return acc;
        }, {} as Record<string, MapFile[]>);

        return NextResponse.json({
            maps: allMaps,
            grouped,
            total: allMaps.length
        });
    } catch (error) {
        console.error('Error fetching maps:', error);
        return NextResponse.json(
            { error: 'Failed to fetch maps', details: error instanceof Error ? error.message : 'Unknown error' },
            { status: 500 }
        );
    }
}
