---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-campaign-owner
  namespace: data
spec:
  encryptedData:
    password: AgAB4pVmdgG2jyHwIqGSDSteprH8E5qBGpmVqOuqhMDk6kdqg+n+u7LiYtxD3hokDtZyKmSD3r7nRCkW9aGkcueDGFK70hc2UANOBvgoSvqwvSw/7IMPu3/PIc0sQyoBrlnVFBWXMjdbf9MW8I/dc4cmqWVtncEPuNCeKp6O/XtO6I1X/o46kfsmAIhiRzWfZarcmGyKeRV59iRXyin8iXzdog1RKej0wknJdnyXGk/Zz9powhVPFCIt225XhpJjwI0YcH4NKRy0utxCc4Zza53f1Pc+kKZ5VurdKSUG4bjwkvY87ZxKKOqT4NvZ/UwZ7hb4HMFRtVzexCCO/BnhEnNd9hron7Je14NrVvISgAkdU2kzG7rIXoE/IMiggXzxRFzBN3QsSOmZSGxdyIlRZHuvQmvWhjUTsWi5u+pL04YZThNihB1aNt8Q8Yrh6JxXpsd0kiirVzAK1c5dNYdRPwl4ofFmapiH6/SRANZgA271QsKC9qteAPZUtzgiR8lu3PSxLCmoVUpLzU7ZOBErVA41zh+3Kyaa3qWlyelOfMSBd5QhwMigH2UXqhmjsKd/GYnu/Bj3ix1lmxAn7Kl7hFKz8uuFHTFNZQVqdX4zwDF7HEU4y2wmPolQoZbytttWonIniVidh0mTg5saLM6rSdXEXaKNS9AcCfkokoHF6GRB5HPjh16LKDkaDxsaqIAjRtueaSI32ywvxzQHV3AOsArkzg0uyU9c8X3LqK6vWdXPiE1S2kWD8Zs+pypwphz/2zcZ8yDJfev1mBi6Dm3C6WfqbQ==
    username: AgCdmmE2FYC2+K9LLi91457WGi4iuXxQMylGbyjr2FYG9cTBRDDWZNeMQ7Bk5x4Yofh4VoXz9XuAbCGpTZYKP5An0L597Gns9uIcA9mpiHRhAKzHlyi3c+pprNaSr2B/NbVkfDuNU2uyFfn8a1anhK6mnY3/fyrPN+EQGHTilW6sgimtNqEx4hi6vPhmqeDznhYcX3SuuBMjIF9MdDtBP5Urtz4tXeMWlVxTvBAcWB5NEp8rAoyBCwjqRa01oyw2LnVEm++hpqZsx4DKXp1PFPsUrDx0woQN3FZEihPjbybhwkexmalhrD2JAVMmBIr/GiUMOy4KyK2XTRCy7xRIYVUq6LdRbS1clU9lpAfeBm25jcbmiGNAupQHvoH3i1oqqWtPfvkS7eRnxy0T+70xwLLPVMVBrCgiwbXGu60RiMiOA8fE5BK1WQaVnJI5Fk2wQbk9oEA7WKyxBgC8g2lWNHkuq4Snwu9cf23BQElrOB89yuW2GN93+kQf51OKggepc7cRHNtevYvgHI69Z1ZpTs8mXtUdI5tR2qo0prf7P7JERvg6K1tHDqNEqEPaP2VwJXC1qKyGqz3L9x9Bqd2DMO+jL1fRNgCHxdwNyIgLk0e/OK3rCUYdVKTMUk07nqnO926f8kxo3gOzFVmMZ11w/mPYUpc512X8fQAifJZWvO4xNWF6u13546QsV7N8VDbFipznuDMWnD7R+rNilvDdMw==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-campaign-owner
      namespace: data
    type: kubernetes.io/basic-auth
