---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-dice
  namespace: data
spec:
  encryptedData:
    password: AgBZS8pvGJIKaxkLqM7RKk9iCtWXF/dEcy7PRmKflWWUH40SgvMhUBCQs82dDw6ocsmq/VBWvkfz9/dLs+FHpx+MmH8D/iij/r+P9//BVNhGOOmwjhWrpUHC78VPWC+XOS86tHhayDk8Fdmft1KeCfFyB4Z8DNNiNy3mxC9Fz1u32FQ4b03l5Lmy50XUEBGY/4Q7/P7ncn+G5VCNcZk6zvxUW/mIFzyIBz+BnPLHhJHBjTUc9O4tcFgQv0pXjbdbr3tblD7WqeNvS40grIU84zwsac1E+TTDnMcR1hCOuNDUtjc/HXw5ehzPEE/y9wWZ40venVHC505RxnALlMiqukHeONKxpvrLLtztvy6VQ6bINJ42o6gyoGCYtIyBokWPYKvvsZmVLixARX7KLj+7MtBWDORs7n1pXcKKgGE12inyUXHTWeu3+3CQICxd+ZDuW5iVQhGBNjnIMmDVMv4W1Ve0cKtfGs365djmZ8qmJGawGks+beBI3tut6maZAxF5cqKqj3Tpek3dsAflTkeSHS+U/aTrGPuR1GA+F/CXf+kIHwNjb+6FD8+y4DWsJ6Ej1ucD6FGF9YpHCb/4fTMX57sDENs7agvHRgcThx7NGaBDF7tMJoU+D05hZltaX/kmt/3K9M167VUdUAzJfno9rJ6ytH6vEfuBDyHqg7pjv59UXuTn7SxqsVyIo0LYLSbBbLHE89NfBjytA37FjeOfFfPmWZR42vMDcfJXyNnHYq1fRQmqRnjYQPW8pJYBqtpsucQ1xZzalbxLV/Hltmad4MzXgQ==
    username: AgCX+/tncA2siBn2rmk+nh4Z0MQIhGxcSV0oQFSuXlKvQ6947ny7XHZnDaWgcP1z9benxsL5cfNkC6Rz6wXqhtMPLXYXPTl5R4DZ2lYQsDT254LhOtP6PUJZczrpmU/hJFY3+KcSMUXQtiUV2a8XSprjsnyFQp+z+OME18lpZS9ADC+zZqw1I87oUlR8YefEK7kkLQiDBEnqql+NBEQQBgPcmozzYo8T1GQQModN+qzJbYtlrd0CryOj7MXrxNwknqiWHB5ckMuuSNtghFqoDUlBGlo8LxXj6JM9fw6jQnPVFJhKys3KZ+XyyCJS1/Aejg7ysC0/jvbhatGygeCcLHKtz4BmYLdMTLT1RSe4NEtymw6QjyCoEkbcVDC+G66r1BM65FmqcCCPMXmGVuce/KjZFZPBVcRS+Hxh/CxTfOp3DLfLZCOK6TRX9jmDAYaWQQ65k0JK0G0GkTMC9gKZN3rdyhm1wofdPXCGPjk8Z7dc6+Tr+HT3rU5ztcGiuBZghdhTqrwXo0niukXLkQsKW5GOej/vWzeF+xwP9G7hNfSS8WFvVy85XYBj+AxiAnG4htxyJaSKhhFQ4hbEqyUW64r4eiXFYndgtxWqPoufAXK/ZFOf1i7fPWcS9zDDKJ571f7QePH+ONJdlN3paZ87JhJEI/jZ5hr8yYlPbKFHTdRF8rCRie+ixZUSVgaWvXEyW09doLjZdjPLtA==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-dice
      namespace: data
    type: kubernetes.io/basic-auth
