---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-billing
  namespace: data
spec:
  encryptedData:
    password: AgDFOZeHzp8ZU72/HnJ3ohhTX8VSEb5aZWod6V9+7yYFwjS4+7sxYuAtX4yH8Q2hPNlIriMV0NPFYg+W0odiACHU7KdhOKagilVMpdyXnlzYGGj/hT9aywBtkNBZ/7evHAjcUL26E67utbPKvOf0GEnVDXHeHBY3MZK97KuinXqvEdyQwKQ2sRHijJv+TMve3moMGZzTsNWhX8HNLm1PWX4P0+dyE7rNbxVXnA5pJ1BrEYc3njaUqYhY2ZbTN8g+rtPqRQsL2K0rH1vxK1MCEcgRzVs9V3csrdwquRcG+EacQfjmGHKj9c0A0fPvK8DrEAd3wPvQqPRGLpSOs/9Yer6R+SWvwqqfdNOuyMBskYbO+j0wksywRJxlMf+gquGcBJrrB1JC+jIM7/w5xMo2T3BUitWZ4mL9+DoKYDU8+c+FE6uBJ0uFkB/TVxzw0qP+A48VZQFZaDM2IWwC2r6VYRa/tzM8mZf0eyOCtlzcmRbtVsFogMNkb7L+ZNYnNVc1H5T7Z43/GJT0QfYjLgWkacmGY4mJ8X3frTeT7eelpuu/ciAhW2Y1/1g380I4YM8yJl9jEqRrE6RPZEOFAcm91CaG4oEMWRV9GQJDELbEzNq64Sc4IkkuyeWBhD8uJw70BpgdPHLGn4hxjv958w6ydHSKPHusO5CVEv4IedTwGVXU4lb8Ib+xCE66QFl7n21hGulSNv8fK/i4SHBvvAA8aXDzvTt7lQJ7k4GzyZjzAR/6BRbfQtI4XuqtTkQaXxgTqokGW3WIT92CiU11s1Xj3CxBRA==
    username: AgBmD9zNUnVQOl4gqxCMw69xlULlFCY+vJ+xft4ewSjfuP5SxFincN0+9NJZOXV9R51T2qPPhu6Tf7F++HCSCNyIFK++Y/+aJAV2P3PD1XAEvLu6U50K3jrjbIFmmVHxkJxcsVkdvy2ij8vuc0w16H+GB9fKl9UBiJFThKE/pyIqQwhyOQ37pogRkwe4wy4pIxCOkk0TnGhkSJJZU5qEELvfPKwuNf7b43L7LdNAaExqMPMiTNqxealtDPXlTHjHgn0+losgcXko3abdy7Iv7hxEwSALNlWrDv0U9aXCEQnnnXCPMARUXlmZ33hkFk8meJ17sq29cVBWB2slUTaUsLopRL8i9mfy8ZO+f5IyzgM7CFrRWVMsy8L6mz9HiKaV8VjB9h7kCizpgKCEMhQahCJm04W+dqjef/Ke61yEbvR6hOvt8VYj9jiWFQOJuM0guBnnp8EnNdAFsEXL6DzKBNmpGOgas3p990y0RfWGkhuDM32xau2+U2WBAcLYzalfNyRzRIstcA1eHfOkbRVURk9H53N9qmTEr5J+Tu5EZMKO73aSDUB0uDM1QST2yR9LGNE8ZS7n1xUzCB3zDUjlkIxjUhFCD4XlpzYbsI37J/PGkqPTIstgI2/Zs4WsJyJGBUSTCzNxbP75OaBEFf6501qpoDr6hC2xedwkm6sq7InbmgzbK+BdtMmwJekGD1ORritbApmaKCwQA6pjkQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-billing
      namespace: data
    type: kubernetes.io/basic-auth
