---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-audio
  namespace: data
spec:
  encryptedData:
    password: AgCVBdfZTKN7v87byF0vBu9VPmgJLyL+hRaACJ1YezCHcvLF2/cTUKtDEoWCGdsj0pzEYYi1bLcgSl0lbhGhp3lkFDdlsU0ysxpWc5bWX4OzCiHTqZjOEdSBkjmJeRYoJg+iCwYnFp+2cRplWSQAgatBaFJZSSqg9y7gNZDmtncTWTIWlDsu6epEux5gReAJfBarvclqx+1yuNZ5pZo/Fy7w+5gXWuY6MJURWZR3R2xJweY0LL5h3re7EsFBdn3gC+Twj87q5mmCVvIL90f5MyZUvyGnT0Tfq+/akMKZfR85WXk5QTh7g9kpc2XNF64mNmfwZFx4k/PfFJ40LRsrG22SgBrklHT4uGM0ZrpqgE9XxYHyZMJ9epqGUEmNF1YCpk92M65dA/O+wjzDaizh9+xQF1Ojb2Vdip9Byd10agQ/eMxsH7FRGcwWiwRA+r9jGDXw5jOcgDVzyCY6KpX+mIEHcRMwAnmaNAjmanotOdZuM6FztvoN1eixSnzSjqEP0dmCaW/s0pzm0Tpd3bOt8DBqMvq4HYf20bniK78Knpo8xYfMb6omcaaJ1NAAj/Ia9NB06e5M4qE0FrZrvgjLYOmLLarqJ9eDb9jk1bRFE4zBYLO+vqQPpWucNkKkkaKRNzRxy87aHdZZdBPPdbQ2Gkm5Jl6UDZaFF/7JT/qEQMcALcaF7IZdRtexlFGqNFN9MKes9hFQ4dsLXYwTc5ieKPcX1XXP3Y8cjWSjQbki9bVZrEftC697ZavhhV3R7vX6li62WuparacUszwvsVsDloIh2g==
    username: AgA+k6Wdc4nkoWP3yi2iM24UYboUywZZ8G1TbekR+vnIc1r6D/+OBP3xalQ7qWCBTRFUWKX9ZGPMsNN7iJ0ZZi3XC/Ivn8QRAxE2dLFt6Ol04FVrtmMj/T72PerBMSYfvcGhb1Ay13fC8FILrYFRbKTvgVtMbvWsAHHSw2BbI0ff2+M8mIZO85zJkl5gqqs6n5JVi948Xo2/r6gnh+Uu9ScSifetqwQCrDRPB95sX1g4KKSOBYbKPaqFYCjSoxJoHeIbBhdZDqsgBZP7rM63yJF8q11reqBx2BNrSgXJzytbKL5JyBSWPuCIcnzfdiBfbWo2RK7bchpvef3KGpVyruNJgdvAbvgSUEHWnrrSCBTTt4pjO1J5vCwy3SJyj1Jn0J6ugxODPKcK/dEAutpto5QMzdL64Dd+aY6ZWlm+Q/W9UHSReDC3sJJQEb7xSgm4QVJZ9PbTSBI6I4G+QTtlyUPWhxWlFeFsf6kTTQJSlDu6qY0aKL4UNT88uIUwg9XZ04mF2NhfTciuaqxkSHYGKcjuYgzUPgUjttqiy+VPEKMhZzut1dBMaLG7zrlgYCrIFd1ZsFlFA304KggLF/mSqGn4NVIa7I+7oKdkXtA0ktmsnH9MzPnHIunpy+ojTjKialaD/mfd7/0ctdj33M9ABxe38DdM/EEvpyHX71R1GKKFmZZKek6ScEkvcrh8z3Pxc2DmSmvGfkS/ykA=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-audio
      namespace: data
    type: kubernetes.io/basic-auth
