---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-billing-owner
  namespace: data
spec:
  encryptedData:
    password: AgAE8oS9B/2+k1AnxAnFcCzbj2ww/JmdPsSBjIZHEfSE4dFzD8WnjjL911Owh2KbbvAFIvP+MeDKCvm1tXgXlHEQlxKYEq0nW/RmKzmzxrYOt30CA6szcCFg8P9LRjn509dBQjqoWevZ+0t2OzYcR/R6T1b71fx2IJAcsOw7I4Vs2hy7QFNwMSyhtkGUjH5P6a2jG9dGlY5ajpD7a/t2bAobeIZGwtyDvH5KR2t3P7OjVjKtPMWly0/UYu3yzn4KZKa/bodAnaHva9TMZg3UOqzztYPGFK+9OUrnf3IN0E6DMKRZi1sJMrhaI3QwIozXH0P6k1B8tgjDfpmk29nHNCgYrXLq1ZQFeKaYmv5ys4Rf8CIWfJlSGzso4f8Hs17PRkH1MOWCgkro2QbtzUxnfjLutwZ2RgLVwewr3jtIEsxNwDpVywS9CzH5Q+4n3XcPzATvvi+vn3+eliGrGhVdnszr+y1/e7ZVf1607c/582hRMZpIYpn+cg0c+x2VuLk4W2t3cFQcmk07dg3xBioqIkOtCcBaeJGrXXqcnAL4P5b0FmAXiKN2D0oUCeLH1eqoMPyB15IwOn75yMMGu7BCuOjyxowdJxFipIyfdMwqEO3TCsriYo+42Dx4UaYvhzASla+Rc4FlhrTVK9UBZ8M7i5Tojs1yZaLvTdLCPMv8ZrH70mkbLEjMcUtx1Oh8qBlMuViysUmQ6sgFqhlJEJDguLC8fpEmjVO8Xb/FbHB3Ppbo9mtyWZOwK0EdPxCX3n5FtdiY4e+SqFrnQsHCaIaIHV1fdA==
    username: AgBf7ePHWmv53+4imbxbyQhQq2eIub7aZBjvBeWsjmeeTRqJ5oOL/J4Q4fxEXFvUkdQq/9yvKVdXJO29flC4DVU9u0bKme7vSA5toIgesrYkHDb747ONA6Hs5G2ROfF1DFXYxWN1H3OSnBqLAolBFasyWTDW1MYF5VgOrLyplkhSQ1PCBPqYSXX6wh167VghF8mmEmgDEtIXgPIme8je7IyYvOSBKe+b3wyMqfvKfs/A5yqzEvtI93Fmrw7471d/CQ5cxdeWIrm1rI/gAHQfa107yq8rIgLbIfukMtlOdar8YfPg00gxcE+kf4WDh8uGJibwwVuaG9SWsqEbF7112x0+sWkLf0DtqXxFdBt8AKhQ7RexvNT3nhQSfHB48fM6Eq1FJsngwE/E2N8chflNEz/fUSdgFiO+UV2EFa5/sY2YEcViStr2A0VQSTPMczoC0Q1g6EewaZnQADJovXlQ/iKyNe04DB1Gv/yoOY+z6fESFFXkI6xkJmvZv1OqUwjo0yE++wrZoMpxw64gaoZeQZmwv7hPuNz8lrRT5SOoX7lT6EOib6jSL+gIGzCDkkjbQquM2uiR+tOUjR4IKAvfhVTZ9dig3xVmhMjMX/mNNm2iGZ28fpHush7OOVBEtHxzcQRA+TdI+lTn8/EIK4oqHJ6d9ou/8Wqftb1PobKC3iAk6Y3bwD7UEWttywPQJu/W6YOvfdgVmqQqzwKVPlP3
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-billing-owner
      namespace: data
    type: kubernetes.io/basic-auth
