---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-characters
  namespace: data
spec:
  encryptedData:
    password: AgAUNd+rW025YTF86h0mNRK2hDHpW3yh5vX3SgmuE3UTZn9bITWRpce0VCmUrrUHZNQJGr26eEnAX+S3QPe1YfPlDCiJIQ6pA05OlF564q+8trAyfo+kdMo8US7cgvnfKoApCe/l7IbRGaspjDCO/jeduQiFnzUn5q4qqVfBLMBvfT2tRN2voLlnjXlBAVtgQXHj/diHYggEsRSSh+Srd6aWU61kDn9p7Hyinkvh/NkT8sROTu1s7Er4Zf7OuJZ7V+/HF1qyDeD6624RlbaIe73CICZRqQoyJBg2d6m+TCioTKcqRRDMzyn3GpQ2a2c8swgtSQ78xKxfJSml1YPr00pIV4xe+A4KHyQsQKQdS3ap3Whi2TrzGGhD5pWzh1Th06779hbbyL2n4X6oSjUs+r8YQyudG8mWhGAr+fSDkD6zijfTE8qQ8AVzxtgTzxzbMhwOArIVMi3JXg0sYFazkDidB7IQ1kRb+9OZanei9+mWLsOw2ICstJw/pJEbhn1SOxde0aK9q1BmJdyPsLt6q40/kVDFlaTiRlwVcgfA2OkZGG5+8oT1G27XgYFd/IBsRWDpfWpS7AbiEJ7z82jfauHiQ1csPAMvsO+L5ONGWvIHx2GEyBVfFrFugOs99WPCKUiUIlhrQczKywAPksuB9btvtClmu8uwxqcbUJYPGWZIw+w0WHQUsnIjJl82FIhcKwxiIy+TVXpp8zLYHeKoiJsuba7G4NJv4X2LIQY2ucLtae5LIsRnkzguQkqImYjIPf6mZyhQP49E0uTc8TU1ESo8DA==
    username: AgCt0N8zKd4d6Rv+JNPE5idv/hhma40AO42hzRmwxbHO+Jek8h5I3shUQW/kKNkSF7/BuQpSRFiNRs46aIvrnavQ2e10ZdGCc1UFWJIyneA6sR25HE48Pqa039XWc9wGdb9MUI0e9iDlEDPoLNwQMp7SAZvPtsxU7abxENwDShgurPtfJZGAqgqtNzTsQQCMO/GCUHxs5Bf+QOoFUCq7OPhQE6KpjUVsMWZB39u9ljG7anWc6Val3nCrWc07NMt0rMjlIeF2GsMbk9gv68zRRfUr4gis6U5b2Havz+2zwAHuQgxeFfLCt8a/cl9W4cOyjBmDgE0RsRlAh5u2ePWlahEF97cDXFFj06xX+OEFLcliRaZdhU5ZnxYUodrW2KhLg/X/oFseZSzSAuudODWsVPe/69vzPIgzl3RsvyRrga8uf4SHPerZaQC/Lsw/6O3u1GyKPZtGJi1nEAZdGZQ8AkEe9HZHT0x8zfRHWH5NPVxuCPDW9Do1fLBgKem6xmZZFpXPPA9dEK9J3px47T6JkqUaTgmErmmoWWDtAxXZ8l/udR845c1oV7hNAZ6jwLjsjGmYjXczk32HeY6wTM20TyDgxxPww1xRoYb7myXpS+RM0sIlryeslT3zET0rtpVKhw9E1Y+BI/FSGrCgnE0bSh+Q1FT835A0N81mAJQAAZkdCzW9kugC0dgdsDEiqZSEWetcCs1fmdCAoTgpo2IulA==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-characters
      namespace: data
    type: kubernetes.io/basic-auth
