---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-audio
  namespace: data
spec:
  encryptedData:
    password: AgAv6rKCbPjOpN/QqCU6tgbANhkM948wxzGR2cQvQxJZW88BvkRPcfIGJlbHk3DA3Cb9L/aQqPxDE6Rzwc1jIdyOGiRvUgTRjZTmSBTZWCHpf7XLhq57xM4H4UmB9oicmlZdvagbA+Wb11fRHPFizDuxa8EaUbFR96d4PglvvkIHNIZlnt8yy7y5Q/2rlRkQUJZZKmHDCWyJt1WYPsgRtfgrsWgJtgSUSQyybjPCfEW60wNcS4TrEoxt1KWD3+jjBDCCmqBP1/o2WlxJqxczxhpvFnwF2MkS5U40mll8BEJDuH3f1gOjWs1F1y64fhO0IA37aDv4XBYae7fyvT+0sj3btt3mPksRQXoIYXp5sN8YHsREujrkceRp/Wb62YP7iWJvfqkwvwXe170073lpScmagPp60pI7avFmyOFWEHLM7dQgYD9hHetSQRPGEhKmYms+uwxe0lNc0r76XZo28pO0eP9DclKXMJH7dysFEPgPnc0ncWVD0XOKgDegsFhvSgwQXHsONjSTa8FOZVXWE6IXIUiDrPK9WWSuER9+P7Jz3L7sfYsZJs1i+m5XkzCCmGBc/piA+nCNQkg3o563H7lTjvZNmnskL2EvaV4+sYP49iWIzy54yO+PBKXQqFDVl70Pnt5/042rjkgDfmLmBzqsHqAKALXLSg7zOACwm+TuE7Q1m2C1nygbYUSTfb9mRt4VHZpm66U3lf/Um4gMIXIvNkIZmirOxwCQec6toYyoweT6WR2Q+YAwvJKp2QSZejfGMx5zUDJGsBa6nOmt7Tj19A==
    username: AgBQjANhHmJkZp2e9sof3kbTj/gjiHxRzyzKg/9SVSMs/rChSmLybWF/vjtI8MA0TiVEP9dYFKxw4fpRrZVR+2UsKL/ER2qnnqlHjYdJUrd1XlsitecI4H1h7qTlseV10LQRVfOSvhY2hryxSl4n5PpMbryTD3bXYoVIeQzp9HImaAP/1PyuPy6+BGlj8CIMq3zPEO7SthZ06Ol40LbTnv+4vBtlkYvjhb916hAx8++bVOtu79DywJijizxZPPMMbX6aUqGkY3U/GDGhZCedDh1V4ORMKXXSwtfX+AEzp6g95Bf/CpkxqBHhqqELtHjr4EWKPUXqH5ZssuzLk/IZxbPc68TKajaBZ9Lx7t5AYjl27gfgT30lJlVoZ+fXsor/vRO3jrFrxFO/39EAtBY6ULHi79D04HkFoJEGM1fX8xhTGglnsHAFI3KOvc9eQVpUoWrZhvKFMepWjtI6+Xa4crhcviy21AxbkWKiRZQld7vikvsI/kkc3+m9NRfJaWzXH6yzvlMh4X+cIpQ4kT86jRNRXfZ1/FL/EVSVy9PNUuDdF8U6EXJtNSj5sqrbELLOshMXdVOoqZaXaLPCndQlbvm+2cDmKV7VpE1MBQj1Pgh7PO5w6QMuZHHRcua1dpbbruO90F7LKSTsvfIfeaiHSS8DYyDu2tGBDhomVbO0EGM7uUfSYIdIfQJCa0cx5tKxrXQEA1wfDSip7jU=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-audio
      namespace: data
    type: kubernetes.io/basic-auth
