---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-campaign
  namespace: data
spec:
  encryptedData:
    password: AgAZ/WX9EdvbXtDvPt3Izccq3M75NInUbm46TLvw9MJZ/Fr30fTfNBzG2+qBky5leC0Zeu1CdpnjLOi/+syA6wGfldod8bXtJ1T1KaQQhPiA3o6WavPxfc1/U/67oEaXgmwW/jWxuhZHGp7F35eyvYPAJ3VXOLCDbIHT9X85PuihW6n47GWhpITFRnywGVDcisVAuAZvKHNsfbMLftWShaAKYjbLB2a9f271uw9Ilyg7efm7MzdHFcCMCA35xqLr8vzlej01zciw7LHi7YeeKddiKwxCNNabFlwRoRUApvpLBa2PHfbIXq5g8qwRKpxuJTteKrlejw5cx1WEHPQ2Kq4Y//aEERDYP2BPdg4mhIQVm5Rz5fPXZhySkywuHLbnTlCXWEMXpsgnsBbAIfQ6Lbcf9eF7TDmMPwfgmIUn2X0etDOg0kuoU4nS6CnFQbT3x1gOheKuN1ehDKHGrZYgA0u5H+l62ycjEjIeQTNTaQd181KLHs/Qer1SgFu7w1E78E8IQO91zlozXDglqBDzntTi4l0bt54K5lxEQsmc4U7kjvULxDj3kVeBFvN51RGaKxXyReqnyM93XAA0uneW999dOTDvvnaeiK+4njhtObMwNEmbaDNFt5ryLWGcEQN+P/G25+L0arWC53H2smUnIXbJGDamMAl1IZXTPgj8r7jm/hJ8yrAPKRVbMdll1ydhQFosmquV5QXuAOgeYfTlijIrYDnLtTSsK0sCetbuGFDYtdZmymblpuDSKjjnEN0F7yAM1MeCteWPWdwv/ppXUHlfVw==
    username: AgA9sgoUL6y5KI5AKcPs+nfsmcK6sP9WiIRRJxRIBzDHBGnXgfYbB4uDisX7myQs5eaIP9Fsl0FcXGnsx3Aw6OuHoY/vQnPXLtp+GXPDVgkjcgeCe5OdOIvCxBFGW925h/fSKVUiJG6WByf7Ui4VU3vA+1kJD4C7FJeFqTnQTOqi1MFgOGyLa8Aghb0J8IMKMqZVYsC983lVHHKv93VjWP2xmX7/TafflWCGgUJWh5mMmMxKjbzX4nX3gFpaprMKbUv1Uc0HFrnXJJNq4luFtEMt61J3fgoGwfw1SbL07xpZpIPWgh/jpQ4Y9SIoMeaACoijfvlKhR0mZNbSit2PkuNlZkx7ERtrtDtIEnYvuaUpEa0pLQR4d3MLNqsKxf7V1Q15hkHhk4Ajs9brILQioEWY53BH0Wu2nliubKdFIbfF2SN3BYVXfL6vWnKP1QwvJ8fLsNiVwMMzpBQhNRvqKc31rQ9rL8/kKaLw2mTau9u+18VFZ8k2CKt2YPxfaNSzP894oZFxKHKeOlvs6bUALzBDGaNEv5xeVm8yJ0utlyX4LQ3fa+QuvogvTlIJjlHPHsYnwdW22oTxA1YBib4ERsEwn9MgXTsiMBZTxQWhdCCCmD1umCa5ss9fCfNuotkPBeKFtL5gSVe4UWDfgVoyuzPSRr618Lm+rvm18G+sFYEdm99KCmfB1ZUvLq8Zl8ZYTtFTgF/mBPZdDOe2yvs=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-campaign
      namespace: data
    type: kubernetes.io/basic-auth
