---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-identity-owner
  namespace: data
spec:
  encryptedData:
    password: AgC+Ub/YCT/F8vh4xq3Tz8j73Tm2wA2NOPzCZ/i45oT2RO/lmRkBmR3QGEvSye5djUTwIv7oX1GBar4j3H7UpJdddD7RUWFPSN3kCnPyVTkKoOmfkC3vJOR2OWkX9yaHe210g9T7NKxsgOcuuLYxNAusB/O+ieChh1eh1PQnR8PkEynpuGXArer0f+YwpSNEIsEklV70MS082tqmcNhgPWaNlOZ9Zlop1lNswuXgVzEd+eJw59ZCcRMh7dsjeeozjGfFPTwqKhFoeylVZ60ofmZs3L6LEiJRP7JfAuHFgWNXfONii0kwXRYHUt5OkoiV/45EXV/cs7WpRape2OLuHubwHVKai9cAlhNav5a8bcmuhidqUuNSGoU2xrrqtf1QJMYY/9GTq6SxTDkLQwGy19ZvFfYe//rsrZ/k+OhVvZILtMjUK+zkfP/3unbWEx1lAfAEh60g+4sWI5Cq+QMB6YJxa5QpeZwYVaV7phSZZMc0o9LEsBZYC787Rd+EgEy1npU48pf6h0mZx5LirZ16TWA8q/Ns4O2IaQg9MZuC8J5PeTrVmiUUgsbkNK+j0HaNZ2T0E1uSNXLWlE5YBdyqyUS+1ZxhAL0o3ftr8qzETqIOjGg3bUjWkRJLLB5I6Yc0c4+ZrdfYASP9Yc32NS1PFcHiMzdFracOEM8a+FDONA3DUp9Gw67Uf7jK6cxjeh3529Ptu5jC5riGxQsuN+PkOfQ7XYcJI7IE2fRutdNcGx516KKWR8bcY6HjsDFiMlpW93DZ9t2lXooKMyunHSTXk1T3gA==
    username: AgBn6vaVVJqaCwUrTZNMB4zxUg9iI9QtftmF2NFMTTzVbHYenLXjKUhXX+GPEmH/HgSFYWirVz93YEDuiKmlzlGoHQP61MgbQ89axAkGQJGZUdzqlpbQiYM6kdvnqYcvyhTLouhvtd3AkjZ+FfH2nE1CRbcc4noFz2ZX0UWHGBBKMM+EJI+NJY3Hn4woS8EByULf9WQ/oZPwKR7oxXdx2fxTvFsm1Wim0a8siPnqWNe+Z051LB+Zc7VFImNKU7rU0bsYBK2s5LGilSSKBkzD+s5gU6R4+9R4lKy4C2O+hfb3uEK8NcSGz9KI6LMS36sijTR8Kqj3K/UeV2nouLs09o2ybc+zHG+TTIBXfxNl4JLptM82WqkJpAssYNA+1PI1H8cBf/ESXwcs2QUkPiZXLRMGVZ4K1Vanyfn0iypB/Y8jtJEmfguRGY77RDukbLFO/0G5OUnsHA2wyHUWiMK3QQ2rs6BfNh4KbECasX2frOmxdYhkd6UthhXaKpq9jo65Q7dbT7Ed1Qgj6KqOpOuotXXwmYV9yyM/6AmEO9F/qZWQsGOuzuYd5aaaXelRwmdDBdnzEQJVw2JzJ2qZC2K/GQTtP7n614NlKfwlznJlWLwp8Rq6xp3AVmAcw/hm3HeL1uYG/cvlYE00b3sgcaRdQ0o7hxYpc/JS8CHyXXoE2Jg/hFsylSr0X5U8w7krDBBhnp5YAr32pLLVEpem6UuFWQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-identity-owner
      namespace: data
    type: kubernetes.io/basic-auth
