---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-billing-owner
  namespace: data
spec:
  encryptedData:
    password: AgAkV13zt34wopB10wbldxDJTMREXcCECCm2EH0kcgGyGVEuujuS9ymaAk6/uM8tf8mJcRF7S5NV4nJq3vmTZX3G4A2yBG6MWOlj3GX/w9ZuxeV11Sb9bLAhTAdZI2znnlk9QqRxgM4F6pY/mhZ0IbshKuPNFxCKkasFOFBDFeFIFIf+HrpZW+PCp5KOYBEM0RRYGz06ZtXv2mZUYQw5R4ItVMPy5vycP3XwaBwNCVESGqKQs/gkeI1xi1DFTxH6YJ6HQOpMs1X3pFORQf0qPv/DbguONVqcHyuZYR/6b/PAfJifxXmOO8lCTLe/a7AIEZ8jSOyyPkLZzHaesNs6Z1Rh+mcCJrBRke3N9NOfVctUzS5w9UKKMDIvrFacW4CUb1HQFvldB23AOrqld+6h++09pgbLtlQBP/wXkWYcQES3k8Jor5/AjS1vjVe1sOnTjEwBfYXB34zFhlYMIAZ6u1+KrfbdhRhwaF6FQI7yg2a0ABNFR4Le6YDb3A2/dx4kQ/Wd0kMiGTqKyBNfRFOADDh1WoLhCWDdrUn8GBBMRx5Xw8TlAKd/avjd1+bHvjf5hsXBf/9uANPs7Gi4ofxfqrU4GsYuzXVdCVClnWKZdH6MK8ifEdFH6XGkekGJ5nzD4KqN2F8eWhaPM0H+7n3zXyuwp8G02fNOJhKnCZSXAJdYr5KERQ7oiDRncztYPYkIIKl2eFK8iVjQG/SG8bjefVgpYSmCTmTbCs9abKkBJ1XgJ80QgC9u+anepxxGX4bOsCUx64AKKjjiU/L/XZZjajraGg==
    username: AgABoZycunVwkJ0BUy8QCx5+gKab3FRUp5+JoLoEkrTqaot5RKSbqUkJLjZT+8PuXnsCxUP4pS3Iofz8hMAUy7kVeCkScwX33/WfCbGbN2Vs0selF98cUGP0F8Nwk+mvCH8sEi2x3zSVQfJ+XR4ZVZ9OYiHNdMmpzmQVSbqZhnuDZbvpB543bIjUGi0/IhwmQCPQBQdwrHsCeia0jaSlzOhkgZgdV8lPkA5iaxnnuQUgF9U28f95/Afny3aklMdfP31JCr8xF6FbbjfNQyjHeRJM5AUR6DJxci84wh5h+k7fn4ClqhBrrNawsPnlBEaHl/PapYsL27qft4uubkOIcMYWB9QVC+E7a8TjTUpjlGu8J/Pp1N/vva4FTcpt37Q5g/07d+njwYAiEpQdbxXdb1JkbpCWG04/KeeOCeiCdjEDYuo2wx4MpJWRpzZI95qUr3wVw1BohCHVdNAnKwiBhOA2uPDyoSQwtCOTJGoqgU7s5u8U7nnwibM34QbZAz6E8Amu9vwsSFAPi6LaWVMmpgaM4AxdEHfuTx43/z3Utqij3vrooYMc9PO3gkjTD07/NEUhRj0yxZpGgIxu2O7eqpz0kqgQ+k2y9PQQt6py5hM5YTgX1o7HMLtSDjU5YrxPenoKwLfHDGRqaweuFMXAaZZpECZ+YrBVjDfwytgr/SHT7LBcvI6c/3NoX716Vf/8XFfiKzZgL8UR9WoT6oVN
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-billing-owner
      namespace: data
    type: kubernetes.io/basic-auth
