---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-characters-owner
  namespace: data
spec:
  encryptedData:
    password: AgC4ygwDhb/Nenl4aTgEYhOwd0msbUHoWtcKg0sk6nNMwJwzsna6ydWH6HQ+uN8WfejBKb2goIzwRUZpwUSPecjiL9aVgdXiHbxLok1kVmY/teCfqSXyJi3glenKB2mDmdIkIf7LBvCcTvztCc3YM7rtyYpLv5ZwwG/De0F8RC/J1C0nkqZ8dabIlqwEhWUrj6MxCubhUtESeegFMohxWrsmPHGU3TqRTqO4ONhk0CrOueDJEWIornWgJjdLkE9QwxX8CY16hBmAtB3zd06hi+GwFSy0ygMO9/0hDb9Nsmw3J/mzm7rSG8YiMxlTBQMveg3ecFT2QXZETHyJAMHRRjPbS+TtHJ8WLsMW28iEw2I/j//Xe5AI3pDxLstDshCOei0uLIiL/NobZJtJR41dzf7LKspsAcpAtJSsYa/xo0nXfUnre+XOq6qLuBBlbblDXkgAYsCur0s/QozqeMxw0QlTAKPHema5lwgHc1Pq2K/XzMvdyMQElzI/ppogODVe8eHlEnev7pir4Jwm9hFKmgqoTNENP0Lf8oe8v/rvifnC9cw9EqT+aV1Z5yzqc40BjsHpawykN1FUJ4H/l2h4bdaAFP/p02+FTWzS9uDkghtdY8slRE9wePXFeKTN/1Jao4ri+QSbUwbucKg6gRGVhfjdOO66Fx0m/1Vry+zOvgglU+YRvYbYPTAxphYX7WoOAb8TJScbuI0llV6Xqg8piLqLq5IBoSTnHf03mqoJRZ9BpBcjBs7oO8jZNwwKCnFUP3Pq191iAFVG3osAkoytZSG/3Q==
    username: AgCUEwp9EnJCy2HrGIHHRHwsEfDLMOsTbDIVgKAb0N/F5vJ8FrQKqRXAYBowRopwefWigeObBpKgP0yfSOn7NX7oeJTBs3VS4eT7NAS1BEv5RQe8OeXZIKtOyx4kLQmMOcGNEnGe4s02FLTVVwuJDNhRu4MAd09jVXwXFxIWHzsOIAvm65f9Pcoj0PrLsKHYWMF/ElLZ7qNk5NWh6lFDn/YDQ8J9tlXc0buf8bAccin6JSOBCl6izEsI9XukUXoMAzcMnNFX5bK6W8QMQnjzskMGoYRlt/pzRgJt1XvI14XwUlimypXOZUAWtYcBi5HbPfQEYhDxHgYx7T9xdmMntVu16K9vRoUo34HBtalulIJmwXQHs52V6B02j7D2armaLx5iuM060bI/LBPbd9Qrsw5CSi5KPOjzLvuEGGer0Er+6nLL15tjk8v38DnZYUI4nKduEWrL+CS+a1R4rvj4FDA0sF4Db2E0YpNv7azNtFJ2EWv1d6NTrkptxIHomO1T0cBbpHK70/auFp7rSxk9N4EenMOXUeyRuwP+D1M0iMohcOMh9aCkxIotx3TSsMr93K/NgSLpvD4c04tUYnPiUVUvO0ipN+MZCgszUWkunhcZzQANnrslNLPxJvR90d1E7QXRviOg56YMtVp0CH6YrugZ9qNguynxGDZRgHjcVvRg7A3WpDpyXVKWPKj9r3lnndE5+ReMCzGVwW1kXxVPw/zb
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-characters-owner
      namespace: data
    type: kubernetes.io/basic-auth
