---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-audio-owner
  namespace: data
spec:
  encryptedData:
    password: AgDDvJfY+RyFOFbcURfbJSX1VRjtoncI7Nfn1LNtlQAsM/Q45sRa2uAgfVu/l/PfThANhX5iojFthq6ths3jIqeOqgpzOLBjRrmWQ+Kq2jKQITguu9fYm9suJdOqr8JIM+I8ZtHVrHdHu/DpYRHhs1mAqMU/fijlsQH8KVYgdtInvCRt9YXcCb+ZWzKOja7rW1ZV5T8KSIh82SdfjLDgR2MlOdMZf/IfwCCQ5csWRQPgudm8lnmv4PGMTETEus0v58f46XzXyb7QuQXwOqwIKWfcQBCB6jr9rgLSjTvC65wAIfb5Jj8dFSiBfNDfyI32oIcxlaQdZwKE/GJ6h6oCTxPt19YinhXVWy+FqZzJUA/L9gPi6uPTpDrrf4NcSAUpijvJWVAUSnra3J3aWggNwDfXFiitPMboqD1kpZ5JTfoE0P9/syPf5n2WiFfPg6I3FTAP2l2yb8G4SFyXSbHf4enLATh6yNADSc2CrbNI7apnfwPLzybkN9VfeSaIEVjSZNoDY6rHsiUoxz4PR+fAq1EWe7Ez8YJlUxJIG//WUmQ1aGLYpU+/EiysWkU2x+nnGl5JYUwBhann+qFEhGxWbnrs3H9J+TVn48X0uOr8ohnAIFQ30EpAFgUVJxXjE5a/ux8aVsPI3ubGV7RH1FbLdeI9k6xoObM/FeWwXdIqfSQqFAMIbVmbxN9wgPrSJPulaHt7fRaRmabvxxLxCCIpLrtm2VgqmFNFfs/A46LciSTqFjDIdKThGsexFkgL2nwLA/lh8S6NKHhOhpvP943SBP4Olw==
    username: AgCK+yDkIAwI6m2Fkra105zaVFOxPcAkRn2mqBzaySwJBtt2w2qyyUuRownADPw9AU059464cLGG6DDZ3wH21IwsNCeA/GOAvkfvfek2ruGhVgLcdvKnQ5uZ61ObI1VyKasSyBsxjIfgGkx7GM1PgXxPmQpfCpzVjXgxJNImWzSPNueerUtGOzlFA5c68ajXv1n1AZV+0NMtlDweQWIOpUgKZqXLqkStwTLiLAV02gQHkqlta5EzdJEysSTLmy/Y5HRSXdAmPT+QHHWJEDjW43RO4H7BybXsWrDjyCxeOXAuNTUARsPX4yJPogSaW789cZYkDtqPU0+LihzNfBOA8dhRfzlPWhKzBNUNjutkysGXkYXqcnYCjIeXF7UYG+uUuKlZeSj3PtzQIZ/Y7PVo320bIDDWjTu/emD6ECQHbR0UixxrUufroY+ShT8tsO1YfAeK9w02GN8N0ej7mVPDvpWlXEdd59Gc1Kal3tgY0TOm5/ZBb4K3Lh//qa8JSmX//KAqnzGmilqzvsUFNgDF14YSVR2hZKGpx+xrsUzeWLQXl99rix1PibAnvzCQoGt7vzo/N6c/Yc0O03xtRiCcLjtxOI+s18P12YorwxJ3zZ+/+WMFX1/yPFQDA+gGIQVjco3DCLD3VNEDtJRz8wv4eXq9z/2DMTCvrkrWMR3eMoXS9cpm4zpOXuK83xSvj0OWZv/4Kx8itrESB9Cg2Q==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-audio-owner
      namespace: data
    type: kubernetes.io/basic-auth
