---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-dice-owner
  namespace: data
spec:
  encryptedData:
    password: AgAA4eaXhWCXOWEVzYvKAwp0WgF0bp0y+rrRiRs0X//PTyoy/WM0z3VTscGxquX+oQrPlb7q+/ZNjnBXhPM69JR9y7OVPFka5ofxRiZGO0i1V6DrAfpdhCHuHls87Fa0MFcGMMUq+xrPW2T/cq9yzTpCuQZXsuv6VTE1iUtq5mWO+ibkiI3dYwwxXasNVQgtv3XIabDFsA+t6xa807jqOmbd5pyFjcSBeQhfuzDcg3U5YxE3mbB/o645WEEbooMxhA4MrbxgdYuGS43e3TZQctjewItL0bwP1FGUJIe9XOa/aez0qzfAfy+GkZ40xCL4conue8/VGx9tPRWykxwamWAVkz88WmSKeFIRtCYeTTDtIdAgovb6i+ogJ/xynoZfks0aO88+jBAJMPwyboZhHGGppTaW7nqsHM7j+o/2hZyeYLJblB4k9YzPMUYUc4ESY4x2XSPjQ5pYDZn1gI3ziHyFmqc9rrTd6G+fSef7SXvNhDbtRkiroPl8RtF1SL0hqdhfemmIQ7xHDJHaiQQxc4vbXl7rRqXYnbJizn7CUK8SSI/m0jYGjUvOk6YLdFAW5NDviyPH2gfqh/tz3V0fwMU0cU35X0266e0oHZ24UKF/TfSE0tBOjZ7tj4U1CAtK4yfZ8CpHyQkuGEyY3NCGXk4MufnbXibKkf6g4Y64qEKE4wN1zIjYjpvMhP2fqH6m5qBKXdPC2891LYrzIi0cz6IKJnsZ9rlScia3Vhz/iOTQTi/lunmJnm7HdfEGeXVgV5u91y0qBRNtAMeEJLoYmhDjxA==
    username: AgC/eBpcBn49AEHh2/+giJ6A/SwZdyMhHV0kZgm5lY1BW40ekOskac+MqKBSlHY+1gbwrUK4Fv12xxqaP4PIatSTbRurLuLsuBVe1GX52ryZHzKMYx3fV4lImqRG38WuNkqfGCwVxxvJIXaU2iDpPDVclWcyWjIfOEUbwFoYHJVmR4VdszR1hVdVPLjYTs//XNmWqV0u7JvR56s4DTMiT13t3v6vD8+Layr/rhyIWPjhO2rkt5MbQh0JY2RWDNabgJ+Tr6vTB+rbIvZAB0tqfhOjs1RwuszIR3xCRg0E4wn2G5cln/NtHSLZZbJFsfeQuVhpwQUKcdl/zYezwZB5W+/SWILWyuzMrQENI7zhw9aIvcwsKM0CKRIOst6xNEVcGGRwNDfDuIJqHahHkuIC/Z/f8oMomLcKaNm5Q+kuj4834Vd7v6Yfki13MwDvm40SMA5ULhpcu9KJtXiR/oWCoERODy6oWutx0f52pi8gMewhstPXTRjL6Oy3lJLZR8vWSwwpW2FhoBjuG2inty21qfG4TYwQij3cdF1R/9q/gUyXHBYu7PYNBFZWsTTinT40nkz9NeVtEzXSEFP+CciSrbh7jngp38GbsnuB6Lv8QKgBbFg97LGrMxSg3AiL7U2Lmpoj0QKevds/PHunF0hKPb8oyNKYo5S1SNljLra7annMdzZhrz5P6fZgc/+MTgOfEohTHCZqK7a7fFcq
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-dice-owner
      namespace: data
    type: kubernetes.io/basic-auth
