---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-identity
  namespace: data
spec:
  encryptedData:
    password: AgCEuubSWXcAiIANL55b8Dv8Y+RPXrRujQNvPPzPM75RF+WtgYAZ/gIV/ZkbNyYkfNBjTX/0im7qGvpW6AFyakbs5yjjU7s85kq/qCSwH/XL8iY5uQUM4PFz+8WAWGLYeU91cGW+UyWYXwOPC8ntw3RI5xy2FN/JTUzuvuhla6eDbjQQwfnJn72w4ubGBiULZ8O67jUk7oQlV/kOWiJItYdChVC8oOsh3JTmp2diMeQ+N1dJBqCA+n/I14lEsXw3/aUP2gIZpSdsdamHsbs/dWsGfKunWcJ4VzYA/y5yzyUoBeN04Ym6G11JgJZgpGUjxW9u19CbkLl6jDMzq0HhjXlbcEqDalNv+PSKH13IsnqmfEZqjAOnXe6mRJqqpUYue7ZjrSsbeJRTZPDiEWrqfj8d97J2bSHnJPc8S70EIFaH0sMIQuGSlA0B8OdM3FaAWv7MGlth/2F7Z0IUXk8pjdmopYGMq8WhxT8mWMufPME+1fdRjLGMuk4LX9jaaclpBw0NB4Z6xRkQD0Oyk4YU9g6azjJeCoBYYeu6C21R3O4QqkCC4AMFbyXYb69mgfOA37vWyYCJMwimwDulf6LVRpwGq3r2iyqEZZpbvmBE9n9hhk4yWYLJ09zHc/vNydlhH+hwk7QY5AxteArSYGCDYGqVcqcKaavxkQnwo0mHfgk+p+TKbbLyhf2A5xy2WxELO2+TCFzAdx80Rw/V5FMQyItgOXCd786Y23SBE7EGbr8sDJ9/PNnuprzwPAXt1g/8+JLmZw0XloTiAabEOu88MbbQ3Q==
    username: AgCzwXBhMz7s9Q/QlxQK6QJJnwQqobuVj+OnPRy93VgJhQkQAWOjstZO7ihgMGUM9ThIfnyMVgJf+Dm6BF8Y4gvhqhYQF0YEZLBkrxZeoXfw8ZwmN5LTz0hzGunI4Z9hj5Tg6ltg/zbH7JdLiwXcFg51wZjD1OhGbIMcITrTIj+Pgk8t4vA3m+az7V4NkuMa1D4a9wllCH/CGuZZZdGRQN8NCgrIAs0NoNUXD/enzA9j7hB+NR+/3nFF86hvltvotlRpRR7swF1TAVCgoRm0LqIRrwGur/nbqSliysYwYzPugYfQij6epBaSUwfkxV50PciSW71keLyerAdiWbSofhT+SvYoGHMmbXFjMCdIN9bSmJs2KnAcg5xLBIoCUsgYUrbYf7hXSAVmxNNPeNvfP7ihRK8Ql8rZvtqMPdZYq+8rGES8ozeV7LmsKvEc/rUV9Z6qznJlL+toS+bgC8NYTOydvUrSWoixf5Ensrf9ZD1tg/3c9hYqLJLIZwIUOdlxG0ITiF2pd/op8Rv/3juNI6k039WXpGwe8kFM6HcCagNzxP3TbqgdVH6AVwXqV6vVZUIIjUCz4R+QKL9z0SkomnyE8VOrIfL0zMZoFZj9v936COvbnUqExczAm5XSbqD/TpxlsZYh0rCh4ieOk0eG2T38ay4lForzIRe28hx57mfJoI2Koy16AJ3cZxQD/I9jVKd8sVVyH17NDktVp3A=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-identity
      namespace: data
    type: kubernetes.io/basic-auth
