---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-identity-owner
  namespace: data
spec:
  encryptedData:
    password: AgBa1Gs+8K86ymiNjrBNuOBYMXaFANqSR7aaKpvlo44K0b0VWM0KP0Aaaw/XPSH8LPzD0pRBUWdzMI3ddlmZVzDNsxKQzgg6E/pLoHASVUJFmvmaVZViobsOXU9KRQiV66BLzV/g6OKgy3ecBW2cRImcvqW5WC3UuZ/80h65n0jGBvtVqx506BUzXBRJhkzcoocBTzOSWYTC3SWRT0QnZwbrEDDHV34Ld0ru48KxvrdjMSW06wTKBdwrp67jLPk1ewIknHOeuJwlUvSc7j1vKnlWgYlre8u+B60o+PpHqjJ0Uc6dnHaS2taeQMRi76WA79QLvFxlOLCAWtJ5etTd/VgERv4YNHTUTZsRa2b7AzePkZqPj0nU7advcZ7OMkzC+DDTsXkXSvTH/2Q78e7sNxcPveCpIE2eArH7LvW9e+nPIOFBc04V6P/2/JxbnprLb5w+Zv5i+Fc+elAAxjUEnq0QuJP2T6CAi4QPzNJmcHxbBofhQdtQjkrAz3V6oUno+4V3i/FJH+xBkSSnBmhswckl+mmZjcrO+ADhe0ldg9YUpCXHXhJRYXU+UAOiTaxsUhxuD/soKfEBOwQwbLQ0M3mRcMFKzTZKDgO194z3nsukNv2ueOjssSvrzVcg4cG36QC40VvP1ug4Y8n/Iydfn9k/HTf6DBpxtU3vB7g/nSYnJPegfTMKqicZ2K6hWoWNLi029RSXkwB2LIaDEKT8Chj0u4IAFdwgmsPwPbYEuK8WkqdOrRpxV+Vmn6Cjzz2E1MGdZFAaNZG5/S9gW3f+VOuX+A==
    username: AgCkybUroHmxyZGWSQzxN+puAJcGttNDQ2EejY/aKFpYrlm0WWfqEXTe3+CGOvposEMDrnQih4Ahe/bcn/9vyMvjmrWX88ujvmW3CKPO54KXdKatS0jEnfynUMTJIM4L7VTzC8LfyCTOT/T4X7HZSSCaBGtqBB2O5Z4m43P9+0lV1j5CqAV6Jh+4WdWQr2rKiODDafGIDq0+i46sFx8jtym3iR3h7LXu+PJLTpKbVTQhQzLZe2WsLvanNn1czbevrlAgKpvVtx7H88p04kTtlbcp/uG7fssLBtSIZi1OpEe6z2lp0A4AUNANKGa9CxIMLc/bmuLZTWZRRYwGHyaywNSxj2nNKEm3R0CYn8TuJkYx6WnbXOICNgBJiCpiPt73+7FdRqfQC3X749Qpp9f84i6A0dI0WrEtSbPgqrNtHYdsymHlJc3wCRkb/VplcRnD1JWZ5f5NmUmXASSDInAhS41ABypVXNqVbX2g+R6p2ozq/FuX65tHrl2UpYNjMadFNZNJ8NSTYlZjd3AGiB7A/c2GGD4Ba+viqYiYcAlyLrQ+O59x3yZPpX7mKRHE75a4jmcO3ilVmdpuAczAgEQJAyq8g5kD3AGWTfTugLIRL0OGmAyesZKAFmwVsgPenKszAOabmrzN4mykxfM07XxUNcoHWXTIOxkE1aE7f0fOGn5863SUsBrU2mXDSKs27PM/I5Q1zUPOWkEetZNycicEgQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-identity-owner
      namespace: data
    type: kubernetes.io/basic-auth
