---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-dice
  namespace: data
spec:
  encryptedData:
    password: AgAGk+65ZumW02q1FS+slZu2xYeyK5da7uAZiEng7codVv/EROoDc201fMT8jCAB2pkDaw6I9fBv9SkkeUCZvW0qwrjJCinkk0WTbgPpbP03H561pUvXVjOAd0I77FNJLZBFEJNNXerhQKbffcc9or+nEiRNoWqoMTwu8+pIgMXiCXg4XRELVHJelbdbKoOzBd1/YjKmUuEsXEnj2ajIX4PXTCo4sGuZK01nJFUvBB+3I9/4ck0J7L5G2ETvvdDQjYL/Z9EGizvC9lyKszmrDrITXmoA7CcZaqgVOEo1dTpCyg23g8dr9JeF5P7ijigwqj7xo2tGVd1hKobH8T20gL6DkASNnb+MJyQ4Dlv1eiV3JX6/2m5ZKopyoELKmKoJ4TaY0Q0icMKs4f7wlIi1mtZrRWNX6/kJPFnQT5XMgHraIKuS65pEJ0xkobAy9SHTbYvaqkt7/haYniS6LHaAI5I3BsX6rjRSMzPsiWnOHlsrPDqv2ink8Pi40JD5cUWaRS3DBib0nRMNThXAmsca/jIXxXHpcG6Rpxey07CsJewFrUBxQi9k/fEpPB7yVcMOnvT0L/Xd0eTCcub9Lnm97oun3S6BDvE8rSqq0xFO1upq6qO/fvED10r9PQpxFIUGxI/FaG4Dg1UsRxvVERhUwdZtPKDzzI+zryxi5VkMX4q6WNRK6cI/ygZv3snaV5WvwWReHsc//7NMtw7iwA0TDdkPUDsCHR0fGiuDzPwgyHRTiCx9674b3mha5W60HIOpE3Q7V+dGrq44eLnQEeWTIS5DpA==
    username: AgCnEz27u6MfUR7YZwhr+J1y/VURm4LJlGydy8v9eiqQs+RvBV4Y0Z7eUx84ay5+av/oC67K6yUX1Xp7tjoRyLPsmcWra/RvR06Udh4RPRPblkU95eHKTcpzpscCinHotmtiODbjoI8uzvupxIlD7zLB34GV87ND4sf1tAMdp+k07Kudq+GUNw90CLm2U6Xb6Uepp7mGTfhZdo0lViD1f+DS/qknU/Q6nx/G8hdpzCcuoVKBTvWvb8kjo+GzYHts/fqpN6u1Zrp/NibeGjUQPpKyHPacIjYcG6iAWbQ6u44F4jkVNkFviZEOuLadPZGnRRg8bjFGrg3m5CT+ArGIXe6y617r7PMPqN1i6izR207rtoLuahhOssK01VUUVfwDKrkov9BQWzqRN3ULYN9r08m3UZwjVBYHJ3lYGasy/Cx0a/zIjdc4tfS6QiQ9d2EQStpQUHPupSqmdJazug3LcIBmAkJaouOXwAANBZtok+ad+jXj74d9kUVCunBza4q9sBvT1eFwdi2GmBZlQ2755AvK1UIWjL7mEuwMmr6q335Ofjt4Nhwxwy4iRDa1GsnKIb66OvVCPx5A//I3suPRR2SdJO7goylsxbAQKzv8Mym/skFAtHSfOCYflpk61Y3Oe37Xkb0Efr0xW9kQhmQBD0zYvO5iLNmxvqFarasI8ThBe44E1AEcA8Mttv6pOXlwiOtrvtmA+0fpWw==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-dice
      namespace: data
    type: kubernetes.io/basic-auth
