---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-characters
  namespace: data
spec:
  encryptedData:
    password: AgCH6QuDedJNc3btPI9Mx1yo3RrESCIHl1exv5AFHZSZBBTYve0gzylMjipuLPy1bXJCGo8vEiFSuog8LoEh8d8KJIy+hDk7aQjY6Vj8qUKvCImPt/qbc1bNKjDKAIxcep0oUswwwMYUoPRn5Y9Y6us8jWAo+SMDAeGJjg4TbwzAX+OlAsrhCM1wR798twrZYXiUkuNk+qIcRiY9F9aHQuP5d/GSEuTyks4qR76VF4ji1IaH8gmaTvmdhK0rCU4CbbRJ41QNUFj/jfE1Gv8afrmMvXS8jjoytn/FIKOQfoxigdDM3Sg2gev+GQBVR98gmIQTah2fmKI9GMGj+6y3D2G/6dW5MXo0TotqjPhG0Di0bb0zIW80XXZN4d6PunRs3Pnn/W/sqxx2/9sbhaj6QFWHk+pWbCgW+CoZeWGuN0hKUoHyXgPGckZnsf07M+5vjaE5h4WaOGgbv+Tkm6ug1TEOOz8YMz6lyo12YSPKzgaPY2bponkaJqhxKskzLLArqLWqjnk7tAL0qBOXDFu/24paqZTee9qbsIar1lslpWevqg/fhbUs/LTKucko5PRRPFPoY3FauMMsleBtrdOZa6hVol8ZJwPC+lrmop5uV4fVdpx0i195SSRKrWve6g/PN+MQRPEMnNYN0Fbkubl8KeWC5RvHRT+nusKv2o4V40HoRTEu+rxJbKRyl7/okHYo5wXGxb5P7VnPZTmPRMAtie7nEaMf0ywkrcDiC25VW3mfZviUTj0N2sZRrhGdj9EIAcChHYWO2EYdoqDuLy8GIDYimw==
    username: AgAjI0v1ykZkkWX+x6GTKqAAvV/WeqwmAI9C7RCuPUOVzKGvtWGMrogxbj3+6ZcoUTuWe5Ch3JZXmAdWj/KDl+Pw+7CR+wgANvZK3UGhYnj3V0Aispwz4Zp1lAm6zCSYoCzSD2KUlDDAVw/CClCLotQvlVTLPnI6S82QC6oCkvn2tpDc2kDUZK14w8IDJiXlTeLI6dH+X3YVu8oZ5kXZPEQxL2YOzjjA+u//suqUxnFGsBsAfKdGT9yZHHAYBbijOpbDpqTa5wcRuAmdbtApD0l3QEyOrJlDKffWm/tVP/nofD9t3naGbxwYoPmWMnHxGc0i9KWDCjLNTXWmtOPLVXZ2ho6t5m3FmPiVqMMVm/fvReQMprnANQJb2DvQKPJ16V7+Wx2nIgztzDombcD2oriUTjducJaTWLXA/+fP+4NrIcom1XPouB50BnZ/yih0Ny8CzzjK+16HGzmTM26OZ8Omg9Gn6rvBpffR7tM86ZvFXXAX87GybiGr7XMuydfSvzHpStKmG2NcB0Uslbnd7NNmKPiZbE4IOy+bWKkO0fxyQjCGppDuoGUoe2982qm2A9FuinPKHOSirqWj0pgNMjHknsrxkjTceP7Bgn1VUV2S3EkLmXtxXGXIFGy0t1LeF3hbhp2RELVZ4h694qEZC9I8VX0p0aDXDGarP48NG1yksnEgDhtd8QSOoZFpJhBFESVd2PJqXP/t2iUDkvElew==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-characters
      namespace: data
    type: kubernetes.io/basic-auth
