---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-history
  namespace: data
spec:
  encryptedData:
    password: AgAeeY8h+f19OIzilHwoK4eDRZITX6JN4zMFuqB7xKpnAFvajjQCWDQ3+wEwJCOo4YqYgwCI5S013vR6lf59JYb34YMeNNXHyvKDSpFDSqxLTVnlFwLkywsGA0iHqhKFivl0d9s0IDDeX2uUL4YxsIl0UsTHiRy5yvPvXDzVu+bnMcCAHs6dqvbEFi6ASv2UqD5k9oWyLw/BUV7sNXRDsJlDUKu60bkvAkuhRDGnytfzulFviCpkz9Yihd6WW4vhkuuWoXcuTC2NQwdGmBXklrcUUETv1+IwhXPWGIVuZsudM2U++qFp4VuMzcJciRSnxrb7yNrXsC4xM2/lk7vfCkek7Ng3e1fJlEYQWK5aH2zX62Tscupg0d31hWPJKFIYbtFP9gEqJ4odTmwbIl7EMgE2PmMfgnDOZW1/QPam+9Fjn3CDufGHmwCrF72xNysa9cA1eSQhO4JEbmrQxUytSokDOji7V0+UIt6Z0h/FyeuMD+kviMTap4pjL7r+Ut2K5jT5tENkrbpc88Ap8Jj5nTpH3bIS1yNONSEhbkRYCC40MqnsVkwcdENEgU/7ievONAVgsiHEojp78ADPf7Vx/TugvhGHETNfTZe5KDwjLAoKll8e9aNcNVoiut6LhUdbGkx2DzLS46PCRyXl8GH29b3YQAQyh3sFUOej4ABDwWGmCIPfctCBr8kYxTY166zLbTHs/W1Zv0yPZShL6KwvZ/+U1IctIisODbigGAIbm55nZwTqsaN1bkUFSJK1P/X8yRkjn684pD9r27fmoaGx2dCGwg==
    username: AgAyB08CgGM0+WyKMi/xnnCGa/iT66LTjH6DEOimBnOdabuPkDsn6mIMuK4iIryMct/9aG2cFuFBTIGRHSMRoDEkOQhfIuiOxsdYfEPwIm4V2FjZ6uj5cuPDP5dzuCpiOoBT68BlseUQUxHOd3yjgwj/GON33DKY0j7lPd59XErfufLf4zTbJmncYdY59NKzSaWU0xSNLOoGNIs9UWrreoq5oGDZ1/2/sKGO4fxorE2hydRE+wlAz50g05xeApY/YvLuvvxTptFuzIaQiX2wSVl4EEHol66CKVmzqYCo/NhMI/T8Z2Vl3OXjaq6NQQFw94294R553HNQUmbHtiG4zKDhqAAKWU7/CCozhSsFfkq1jxmoi2lhyKKRWsbA1QsEMUPFvEzIH394/uzasDbLh34bF4ibMo7b/GFvmuwrQbXCOvyF4Wk9adr7Ti5yPB8sIzEMnKjkupZ8AO30EA6AwcwU8WgA090R8iQk+ORXiYdnS3jHUGg8gbLNkZcEGdb5lAZmc1henBF2obrq9D3l3NT2Y1IOh5pbKhcnZFlBZ7cD0rQd0uZMO/LbzakeZ7tzZUU+zAAbudhYwKVwtKhjtpLT8rNeumLBjebDaV/jpnGch31nRHAmczgYA8QKzbjj9IMJ8uPiN1AuEwvGSCV+FOIkzopph9180CTc+xqF3f4zZUfYydZ867xBQZWGjbnIwSCjt9GHvyR03dm8nQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-history
      namespace: data
    type: kubernetes.io/basic-auth
