---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-campaign
  namespace: data
spec:
  encryptedData:
    password: AgB1DSj8sL8HFMVUsK1R3AcfRSF2SHMvrPR3f7GRg5WsVwPAZedCjG5S93ihl4dLUDkiWjgJWtLbNiTHKV5MlmpOyfP+L7Zxszl/HnpVaZok9noaTjOgq/XnMh3aCNgvCu5YMb5VUYDB50+fFZpPHgSTCMJvsbSzeOn29aGBNukpOoqCMmXfooTL2gm7WY+LSHbvacXN8iAOZ4xgzMHZh0riJ4zWqijqskas7vgPdlpsuVz4eVcuzyp9/96aa1HZX4TfKdvuXVAxKLzk1ANFMnMvNp6pv5MmynuZV1g1IXNDQDt907xZLARRouXmsm2Bllq/szIPg+QQqjEAPrGLYdwqdTUq2ehWs6OJbZyePV5sMeFRCCJY45IEnVCiY6fhn8eSebrMXVTA5Pbcq2WzHeOo+ErgG/Sngwj7vbTeR99dagZ4nHqq53y558jCSalmTWuFiqs1MP+AIJeXRHALLni3TAQG6J9d/Z8qQzQejhZycs0wJ0jMwut0ji0ZNvEbTIfEHcjOe6rtEwIRzigJqDqdThZNmNw34Cdh06QuQlsCWT9SgGrrAOTKGOndJHI/m7izuhGk9Hu2uTqztRKM6pvdzUuh5A7mlsCWhVkgw/eYOtOafbDgIFAZ131GOKfYvsBe8dAiqCPat6VuRRScIjZaSDMBwSOjmRqzsARngajzdE8cqHkAQKlSGpRPXOgiTnaV07Yg9+lBiJKg9NhGZ9Xl60q/qPXJ7ye/1yDHgaoFIoVS0TdkLFk4zv8aI8gP4QlAGcQtngu9ksiN7UGqLd2iBg==
    username: AgBSuekkl2dMWuJePQdUrS5+zqHxirV8fjndQePZlPDlUa+A63NmDVzLg6hB4Do8f/SeSZL+IVm9L5U9zz7eHNB2bCKWr5JWeWfs9lgN/eS/Jf1mvFedka0Ix0GWJz4rwak3189b/BPfQy1Rg5jicSorwMQOdo8FcruAUJNrq7uloybEUTjkMpOiz7ODsZtYDKI9geXXWgxUy07v3XHFD6gTYQwhCRGlYokE+/agPd47ApxljGYKq+dHT6p5kJ96cXiIJYGQqitaUh/pWLEhdbNDsfmj4ITekd5zpAULgTg4OmBsyv+7NmFcC+mKtmPC9u20UlPdf0raExSkapn+0uQZuI3Z1a7I8MpT7XZD5hnC/W/f23dcqunWpfjDDMLgHrkEO3HXjUue6Tk1HypbsNEfC5QutYSllURE0Igv/1ei5KrqswIZfKho8+tX8ofsYDH5EbCwwmxLjjE5I0SmL3yTbw+qSDGY/WmbOCnF4Eq0D5lFbGYpdlJPJnQ+pkWxjVM60NXDn4mO+I3ksHFP+gzZKSiK+BtjISETjRdGMU53Kp6xKjsBjU8FcEa3hxV+Em8vWQhtLy0NizOhb5nEwaVUo/u/Tz0+J4dPZnOY0Z4K1dJINK7tuTwXoY80Vdqw+BPcLXbDc/KRB7C57Rpo9FBEpv5PArbYQO7TqNRVF9t1tauFgLukxxQ6KeUzBkOOdAZpTWjGVXtD3FIPmrA=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-campaign
      namespace: data
    type: kubernetes.io/basic-auth
