---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-audio-owner
  namespace: data
spec:
  encryptedData:
    password: AgB4eVUAdkAwakpqvXd4Ur4siMr2d+Nf2bxvYmZTDiFL2/UgVU7+Atci3NRC4/0YtaVFcHG5e7BpmfbKSTHiwV+FwyKcsTyWHeoF+VXIUsU+jr4YwDxPsGSagytjQl3atJ8GSwCSgPJ+6DOUBHkhW1aDT1duaWb+TVH/KWGg9BNfJyGpRRBYUfzH1Ycj4ofVBLbtLaEJKPy3aTd2THSUTGlEnvP/g4AoZr57IQP6GCqAaaevpHeZGurwVMl6molcYsuU1riDbrpNYKkgWx4+PAD3s33iM2LDWGptoi7KY+kT0QT1b5yxPDtwJFthSq9lSjKJzgNvkplw1Rd6YRPa9fnShgu4cVDgGAFGLXlw0T/IwfJeXY0Fr4Xw/UsDoWsYlAO1J7HTIQkUFjcr8UA6kXj6sYerjDeI1fLZarub8K6Alhj0490h8mCmEkwf0buQorlcoRhK8a2+Q0NNvkENT3Dz7CIrdyk/fkgV9scRxKYtfAHtPKX9a6x/8eqlxbe897BAzIT85VP0agoKBU+WitFe/GBbUFtr5n1BtxT437IHc1Aan58u5IcjMHgymoO1iH35cUbd/JNfEBAVIqNh+Ogz0cRN99fYBBbuu7ivmn86jLpD6QRx4BqdK+kNLFi8OLWLtfJJaxqgEtgeCeWcfvqEf+qtMlAJkHuPil5YFRIlaUS7YKB2yt8wBhvWZFVqioGHLGLzsolrCuq+g574n6LyGQlnl5U7SFReMP5qSmipBPO9T6/I5u+NU31ERIUn3QSFEVV2RXyUH8S4tLojouCikw==
    username: AgCOpqp/CHvmJnTzoszDwQ1+n+yaCYqOwUbVJCZuluYPYDwqQw0HvT00UEPVVTMuDu6dwD4NdfvhSHgMsl3142GR2PnX42bt7itIccAWVqVh17MojkYE7nNjtXGphjsuXTIVg7yBpLgBZVoKi22jl/9YAjGZpUYbv52j2E3EfjGburpvMhOOEye1Ek9zKm6N+4WOFcJ5vI0SUou+0f/62CDQ01TT/n1YuGU1sW7qMjbzhRNddLx8lwWk2x21rBd6drBbPcrCRoWekqFq3+39e7fAxWHI4pOHh7WTmGv1Hh60HuEsYQN94/T2CroGY3hkE6f4jbujNseTG0DEhFiKqhQPAnAq/TGaUoT1IETNZzq8NOZigtjY6o0cBmsUNB4h45+umqHbr2pHl5fwNE7aA8oISUgsmuam/Z28uSNZ40yx7vgMsSdSHOxs0qsYb0BK1kX4gHb9MvjpIoy2hAFquCik+O9xUXJICbAHPp/meVKsjv7wKcpw6Nq9g8KzN6wusjpmNRT0ZX8477qVrwJT63TzBylGTxBo78imcfJr562Nws4VxJikTEwnw9Q3d5EXiGvHyVHK8w45tyTzrLWxCEz454Yp4fugUHrG7QYx8XiqUMZdGDODHAirStXjwFRv6ORAT8Pmlb/EzlXtzH/QJ4YvYLU6n00pTNJPHgdAnfL66ThX6kO6Xfk9luFMTGrlqU6ClZWAbfFmmJm9vw==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-audio-owner
      namespace: data
    type: kubernetes.io/basic-auth
