---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-backup-ro
  namespace: data
spec:
  encryptedData:
    password: AgA39IWVOgm7AsQZVi3shSAfXJsNdEwHAe1RqFI5qdBa7fxB2o3g52ZHld6zQSAWJG6lQKzgCPnHMmHxqdAX2D4Q424qGD2V4Iydt7zHjFRbho3SqRiwBHL0lcbZZD/ahJHQ9Q0B72UAPtlLNPTXEFooRIG3BUS5e4g4kRVxvoABlsbSpdQMNsaifryiNVuIpxuvbtdSMGzuM9T+lgcvy3R5eSTY1TeneMMgAKwgKBazQKPQfMh6r8LVcjfdTCbGau8eK9yktfpa0N1BY8svqS5bv8jqr0G8nmOn+tItL787xJzywbw0TEvzzZlPynDhwkUfg70RvU2Ea2ReA1M0g4nHDfwG3/qJCSKDepHjQyxX6c/AdP451wrBzabOoHNzYdXx6md5oVZDVGnRkQskkOud1aORQBZ4X4opHiFerSp3stdg3pWjhazCn3ebcqsFXOY+KKn6xAi1TFB1+fuf/VA1WGeRhxGekr46QiJtq87yGr66Vf1hK6NqsXek+Ywv0bWYIOFTSJFZoncF9Y20ZIecE7c4NdYOZr9zlAsnNav8a7ygZQI3BZK+vGbIsww1o3LWHiHs58KUsuClgrK/W5UWvUwCBrHaRuVqJUGM9BYhbDHZR887rT/Lzy3F1OH06J9f+HJEDOhWhgdE6CPBUVqxCvwx+lqi9MGd0poSq9qwlVzLXBEoj28rwDIYbh6RS0skJYufoLdd+FQwakliCbISfy7UBTgtJXbxrmjxkzrOsZYJSqToedDkknTdAXwp7oAVnvT7sndlJ1EI4NJDDu0N/A==
    username: AgCAvWpJgkvrda2e/SDRu2JhUMJ2LZLujgcY+E1aqrm7SyD/9W6t77EHSLdADEWBZ5GrmWbyfXs21ZtuLiBB6FMTTCzs7Q9ZMxWajh4/P1iHaxFPYwf/Y2HzkphqhdJh3SE8/CB/mfMthZPDCQB98h0MgM4TT8yU3nMTJHUxR3XrfQQM4l6UzF/KjaSFYcgjf9wQYisII2Y7HFKtkF/yDbBFcLNEHAB7MShM5x4QzjZ5fGr29Kfk5RYee7hMnYg0t4WWwqTeSvfl3ZZDmNH5A8y8Z5CWd4zKtua8drK0rtSc8CgDUVyb1UfE0hIEyB+5Le6GoQjChUlLgd9mN8HACTLbzPXD5anL2IVrT8REeKqUrUQAkn8mbyVbZY/k2mNCoiD36AQeDE3LAP4TRHwKexJNRoQ3EYqWeVIT0AZrjfI8KhCNTv4xZAZ7lzggjfWg2lKRtnR5KGuSMh77d6rPeOucYpRVmCgL2RN/fPzwJ+S+nJ3K7dOli8qQY1O7ucH/jf3eiz7+lVs+jUOJdvwWKl7gjls2DbT4C1285qsn5idxbnbVxl5KzWi0ilIG2V6cuN2+8qT9412Ma6tdD5aZ3MblGrAi8npfk8Ld7uHnLN8JUh047uGZacqCEFJ9vrnktpHu172uaM1cBthS8uXzHIPOwp7dqC4p+U2z1ROXw6zgkWVAOYP17z+Ol4P3A57amzAEimcQoWOzY7Y=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-backup-ro
      namespace: data
    type: kubernetes.io/basic-auth
