---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-characters-owner
  namespace: data
spec:
  encryptedData:
    password: AgBhsBr1WNf1Tbt/0PgOqcFPnx3qf1ZA/9MzQWklSayHiFJoitUK17AQmDqnIF1q5F9CJS1Kn4/lwAkGfSmaGvVgwwmpnMkyZzts/CzhfnvFgQHH4BXszBFaf3hiunPHuR96GPm90QcavWqYs0/8kXgLqJt7RseC6cxkZ7FTWaUit/3eRiJItoN1mCBoUnLIFCWO4K2YKwvmJxMZq/N+WU4z0i7mlkOhFhBorInoLODFHYWG40SPlIVzbaQQWVuROjxN5Ct0/CChKzWFtwJE8Y+OFdGCJ91djcf3p0IiheuTFKyu9nIDudP1IAz3dksZVeHw6myxJH+Gr1EO6KvpFUxg+ULWmAmKm1m/597vic0fmG1Cybofw7leN+WTutUUw/2mWK9P/Kq/iwsZcqxlbdj8p4KQWj4j/d+IZlEBcHZp44s5RGmsdul/HFpmF49z554H7CMy4jQPuoHZc3ZQVeDaVq1P82fqbKtj6ly0ivmeS2xmLB+TE5dE/1E+tJd30B3JYivpgH+Tb2YsDs7ub3/R7m5GL+Hc8FypG1/5GspLzTfr/fEbdOA/Z4zaF4ZVr1VZ4HeCaeh/I9xNl6kYRrXqQqXbjjyTJa4RHluXRLCRMVVB46UQtOmLo9N16lo/wmjOxuEytCQEZUcMiv+OBqSC5/Clis9pkpQOH+Vx6nA+W+WDGH+zRWBufqr6gCM5Iw7Ug025UFD0Eh3eJEdToJnsMAq0j5oUckJj7VRVGHt8ab0Kv+p3YqaY4ujPNLZeBVdSnDR1xxhuErNLJS1KLy7CXg==
    username: AgADmu8JWvP7ruPzBqctwNGHb+Qn7Hy28LdPrLrizi0pD7oLwOaUsr3yRau0+0ug3YJKQZw22MOu+RIcR45vv4M6+PHiAAOkrz460R7jr2hV79POeOjS6yXb5LQWLFl6jEn8Td57tu4YoQNJBQvq/Sluj5aM9LbVPB29YHKTW/VeobGef6rQjUzubInbmBOknt4Q1RtOeYsifNZ0eOdz5l7JBDslWm1OlV3oMS/TjT8/97e4ubgDx/oAdCvtanS3d+OLlbKY2dfRTaP+wz4U+wotuCk1KL1Udm3PejsyEQ+csS/txDsLmoCfkcVyKMhECZtbWA9x6kZB0SKjh6ERjhsD4qpMLNmtwLn6MUq/N2OlwueROBcLy4x+9Vt991ROsODprvbvsHJxhsBgEf//LfXmMVtPqoCUKQsGIEAQqbaaC8ZtbjvaftnHeFpTRQClZLaaEB7urt+pmgDeuKxGtFmTZnfpXBQsxHdqizNX4XQOXKOaN0J19RBuxLJV49DIiGR+JvzXsT3mP53ArFFRkl1xPwt/tCGBBk1u5wQWN17bqvx5wpqgcLJ4jTaEeGJT1+DEwyrJFcJC5TeXi54lI0VVNTVS3pP6Sc2wzvy64gPMq6clBjF9Sz12aOznv7aGxBao8ZF1h1tT7sgMqSPGOFutHvLu32p+ngv65GPqW2lYqzHwN4uK11W8UIUDtM7HpijJv6tPZBU7GzyCAGoSUNYG
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-characters-owner
      namespace: data
    type: kubernetes.io/basic-auth
