---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-history-owner
  namespace: data
spec:
  encryptedData:
    password: AgDCklKA7ncAB+66l/sG/dvOhaYLCQ8bLYkpkW57zRvqNIY30wvc2Oed0cnxRAFeFbZsFaUY+6kDx8zFBJwiDBI9kLAF5zbmO7KmOzPRImGj4DXMfsMOUaagr84az0ROmgiC658plijiNsuDD7mdEiuXLS+LgzDIWE47om2YywZ49PLmeW0ZFzYsOnyFpN4pHZZZogCohzQCOr6RBFx/9kCvaokRzab39j8mk8CeNn+Mj4kkEsztfvFWuF2pM2+mup7E4vGK8+IG59RpIP3b0uqZMSmzn1/eewokWNn6psWmUIHsC7nDH+s/Y9yXqr+g5rptedyueLNGwcRsRMxXdDi5vHZpKS2Z2Vud0q474irtLupeTzW28JhTl8p0XAZ5vCYuZz4DXYDt/kziHaMICEok+q/ZUjMzmDMNuNh9WmdadFIXAkUaGkSQW9knBFqImvb/00Hx+pKpcmJ0ps6CvpTZldi25/ZilONZXVxL67CkaiUW7DNWuuf83VyeVtuk/RH5U69ZHNl+x0lTHmCjAUjqUdxWHMsnZqZchVpSaH7Bm2PcpQwYtStmoS9QXI2wGxGOYzsp5I0VfBAKxf4yxNwWjYUzo/peafdPNQvYy9K7GySSV2bDp/vY5N9n83Mkjf9kOEfq1ILnMsUgYds9ia0DXzFdZiIdI31PsIJdybF+uyh3iee+DlZFCSxbDGPcOOTEhdyqOsaKejs15PUoCHt33lVEbntgYAOxpOgmf8JdTdIvLViYrRSXejLuu3RSPv9osFEoFT9MFu6hp7XFH+sqlg==
    username: AgAjkfNuljBhJashaxeHBA0oIDF9e8E43gx/t7f5p3kVctnAJQVdT/NN/0XAzUoBlcAw1/PC98ZE9+JHWsk6iVdBG3Hf3wae4vnJRICusTth89FJp2JDvG8PDUoQzrYqGnemlqPWcrWNj0QnKmYpaxVwH7s9PhEopoC9VWzfIn55rJ+vD7R407/jkXgkpw8ezYbVDlFii5TsjWS6TKeZLzOsyo183AgcheY/heZY6A8kXIHviTO7igaTRHIWVLt30yeXLNdm6MN3TAgILBX4ED9Vr3uPFNz6CxSx8b4RmkDwS+C7BNE8g0U1hi2RbElGDtM/zR/12Ti19r10CCC/UxOtIjyrLmwNjZXMMJVVSFPzZeIctTa3RnLJ/HNq+nldvCh1TJcdzHZozSlecbJZ2tOGOPpzB8gFgjgRumlvPBzCENw2rc4VJwqfctmgKc6bWRDIzljW/aBRy/vVkMlq+iXVCU5l9VTEB8UjTPywfO2L3dfgfbphYNTzcOWMVNGLFDmYBQWcubuXXJ5OLcQnBMFLujGWRAd4at8QUhkS96r5ubOO6hSpxOHRgTl0PZRlaJdgP2T1T0WsuwJoPOXdBVpg8A/5u4VaooQFjeQAZ3lwkrsNAgWdp8ZIMhhf+2QBmSlrZEfvMbxVg8MziGonpmd1rMPeU3o84Zd90mKNB1Ktw+IeVX+q+cdjW/lGXydgM0dHJ9+zl/j8kfWiZgcI
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-history-owner
      namespace: data
    type: kubernetes.io/basic-auth
