---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-backup-ro
  namespace: data
spec:
  encryptedData:
    password: AgAe0+QUWu/SouCFnXL356AKqKdb0UrX30g7+qKHm14MgMkSrmBlXEy6jrrTJQDtHTA7myJBgbQHpKmUjRKCPYnfGgPNYuKvcSpQSHBHOQ6s4oNqSzC6nMwkIuww4+kjwj/i9lryf2HqQ7qw/R2qvV1S5MXVavehmyXr4dNBiVdwKacAO6lNAcRD7hwBGvMKbrpQp30W/mhvpTEZmRpwf+vDePiYRViX0li7quiaGf4NE5L/Xvo2AZgchDUHRmn2+NxjMgszhe0lfxYZEKz5Gx/mAKAJ3nCNSuFYyGI3pi84QEgDNtNa/vrleNx73uaKP/DgStk2A/g3qjp4eJ7Cwo6eRzZxC6yTkcfW7NWeXBZaJ1McsVgxpT9bHwxEKl96/R4o46GNW1qrt5j6qErOjpOJX4qPePOOjjOe6KfM6TDrHlDLIx0HmxOsCntT5J/dKEEpCztiVCqLnCBsIwBmvuCQTFNsGwC06Z2a2Q9zrWqXrWHcT60koY1gW8f/cT7zuY/d+cEXhvDpPLMxHJcusjvwZ6tuWfcr16WBP6gNM/l4gQS5jSijGSCqiUm4kI+Q4lsoS+JvcqCqb2EGvHMQ1/0OB9VcB+oXRcqUkg0gvXkK2rokXtHuO0rnanKCvR6o2dtEbHBtxk5/X2DYL/eH67QBPcczlXBSc4UF7d9R1FZ4TkwoT8tBMeM7Mh0qI5U4PQwvct2AiiSeAExrqN37pDIq4ZWQrHOVvZhNMEL+GAMUVMrfaXk3Fn8XFh7DTgHh1TXjUNMA543VdwQvU2orDf6s7Q==
    username: AgB7E1WKB0rAIpr5+FM7FdkFtOzh72T1r02EUWARRqZ+YIV1Z/EwkU8R1htbVD5wqLFRZhWyQuyFXdZx9liUlMxGDreUg4MKDN5orTJoYkAwUOwEtq/qrn3UA195Zh0KooPG+Q16h0c7ws0yyuc0KN384pbmbzGvYGkTvyIyvCFMFDwcIxIui7+7J75g2VUf8I3DpOZP90WJ6xCxyafW6AgLkVkDw1xKxiWF5egXmiQTrSHfVzC71Ak8aRmg0m2Kov2i6OXd4QAPlwhD+1HAip2gcIq+Un/J/0XnDfelp6Jyfgg5N7CwQao9jgI+xOiugPiOSoSMSOFrbcA53rdkwvi1XcgBqKve2XP9zsVnML12yG8yznwjaSG/NUPfVtdS+NpF8IW82BraeRBAnzB/VD799C0SCsIsqAsPfO8e9wfvMYqHFDLx52MbmZdq4tdXbw/W8BEOpX+Nf2whBRC1YAoeMGzPOSTM9pI7uCWRSjoca6UO4T7YdBrF6RnZ/9bRULGBHTVgG6yTYKJBWfl2DvPkT43ciKi69gz2T+2O52OBMvFUkD51gMtfjViwuAXPuiaoVrYgx+nCjxlyRvxGkuPTHIEXvpolt9PsEBXcz+L42VgprQxL2mOrn6XVkAk0FtFPw0W5p2MQ56QW4/V4pFd/fYoef1IrDWUq+snfuXfsRcXOzr8d4KB5tcqb7hmuaZsD9GolXPwAthI=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-backup-ro
      namespace: data
    type: kubernetes.io/basic-auth
