---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-history-owner
  namespace: data
spec:
  encryptedData:
    password: AgBCgL4CrrBsW6gTWICBBtEs+N1ilwUqSu9wfC5w23EuFFtnC8Bwi0A1U5hWw1EtjpWlJxMZxnlySRN2h4/DAJznHsONT886L6XUk6IBbZznbV0fWb3dmgjXveIWcW/sIwlTKyDRXzsuQs9yN3tW6B5ob6AbJ/UX0gB9IkjXb7NrIDNdT6sidH3J5u1WgWLweLNumUGVhS0A3dIt4ltJuEzKXmoW5d4aJQS0rPWqzaFK5pSQOUT3LvOqrMb+O4ewwcDenbrMlaexuHojoJCPac08Tc6VzmvSnNf6afBUBNL9em18hxo2OGJJA23yWOGhA7p7wAa22imxLKJBAyzsQhvYaExv2ymFkujYM0Q7PJOET5q4gxDrCY0cYF+LNNFwKk2+f0qtvY7OryUdK8zCgnoBXOmBwqXEGM+nKHrZaiX0RQcSgBitoCR8xceHKFkNQsJ2oX65lP7gdrHjWvSVrkvdvDEYaRlyCTMXvswl/cg15MAA4eruizztgS/R28jvgFcPb55IVfbhWahqZG/f2WKFWUToibBu7UkXUK7VuLkoUDTyi0jz7/PmOcKbV1OyB9jkHxEycsyGfsrDnFobKP1FAi6JywYFOVAJM9qg8UqQ/499kxquxnOjCrF+mTGPoLG1u8/SbaOBwW9K2qyq/RQcxOZYDfuARK4G3NakSG3EESOSeqLEF9EchuV+9Bb/ArzkDUIJTPkwblh3BV6Ir7F6Q9hU5M06YUJy/GDqpVmCAlPgBbKUDPmygcm7BfzgddtiOl2j7yJk3ObWLds2W7XGyg==
    username: AgCUdMnokxB0tG39R8+dzuYtpwSMsmGVDIAaan5wBrVOGNWizlwtlLUE0la6J2YCYhW9Au+zJrasrZnCDeTKTrZKhLGavSNq+hYcHNqTMxD8PKw6TB4nNzwjmEwYmhX/AZ70N9MHS36So0f0M9U924Xfkb6gRyq20IDU+fyJDRj1FU44S+5FJRstFDvoYt7mYSGCHjYtGz49OYytWEiQRW7qoO+0J77aA2g3dZ1mBteU/iTBkWUipnD9TWwPgMSVgxz4vNc7HbAKpVnloC7PjFodBROj0MyB2JyV0CP1WTae3n7zycxELWBHetV2tO09T/4bZdXlKyjZ5GWL3/g2PTdliesKuMQQiifWuvY2/vKfdX+rZdkN/OZSva4CHp3W2gVON1YbFEoiCUdDL/Uz1Mm9SUgnfaxeOFx+8y45Oy+MRnDzI4/WmHw8fTAixNZ+bL3U+8tmgVduiPZQjg93/eN4XlthosB7cVLFYrWxU3Re/GmQiiZxS9VyQgzI0h/I2kYRBJhhyo5yZ0j7kVS4NnizkwzsZz2QNj4Bj0v8FMF66upVRA0oYsitYyTBmHLJmBcQTMw+URJfCKrSR4JzsC5qvfd4pU/3vuy567aDOumOHLd6yx02aNtwqrf8UQBh1YW81YLsBpQNhoawvhMhAIxCRDyJnjwaz6Yn1JTjHh4DnvYJ4ErpH0WbdmNLmksmQeIl/oL/8wOiKVhozr7A
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-history-owner
      namespace: data
    type: kubernetes.io/basic-auth
