---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-identity
  namespace: data
spec:
  encryptedData:
    password: AgAoChLcaGOrQ7fp/ufaID1WqLpsvCo72R5pY/ByrcKCmd81U8AmoB3WacBzjtD0ZPv622orb/b9dd9y6E7nV/U9aCqmHy9zo8A3mEmDV7vjuQjlg5wbg5liTgo/yROXUmKd758B7Nr7Iu3PjtlWnzkp8zuKakSw/irm/L1onGe93KnsqpE18ZANyO6uZvUbhomD3+NmhK2ShNpVwofAHxVvNxmWGnGzCgZ+GIu83ISazJWbXhk+032I4KnGu3vx0x1nx4/kI2rHEOKgW+J15KIMrrr7utoo9nR5gXM7yx7wyQxrfoFKUIF82S9hrtLMTj7VmrWKhNbsOZbApPUmNlh5824h+tiJzb50FnvEPNd3REqWjn+8K7tKxoG2ENTMvSykNHMfo4lg1zjsIdsiVjWx7YY2mF1sxBQsWJZKBYN5Z1RkId4+wIG1ZWrEp8uv6AqwHcsSysSBFJ42XHu5V9CDai/zpBaUZfHg73WyCHyDzWL3f46lfeugAGCNIZpBJbBMLdsxCP8X1nDFtzHEDGMfrm+BWjctmpucSggz0kaLyX97eJne+OHdcCgZjsMy8DjSWrwsYZtnu8EXovq6qbX2MkJh3LEINTVVw2hxFqULNnv3NpLEejIJHHJUhXYaVVNGoe5RpO3DbKYq25yDVhkI/eGSGJiZ97skW2p30Ht5ZjaTAQD0ynNSz4GeADxisL8TD5qNiqvU5zNW3UqsGcxRkZw33VBdE73YjtRGzZjcHOjYuqJMNB8Fr4bh8xVafBP61CMH6U7gF3h/sxXVR6ksJw==
    username: AgC6TN656OXIRlG35YKlzVgoL399uyK1AkcG9foi3EPMDR45rVtagbc5Lr6WofjBLVo7cT9VMMW91nLW1tER2EQHSk3ctJgkr0XX2XzSD+4GqgvFQgAt0/tyfkP/pxmbdf+aD+YDvkQRTdYznKMdN8ukgyfs0csCKk2H6rzXPZJG7oz6wmyzv2D8g76t43AU3dwTd7m4crXCcIRSLDmvH8TUUdfJNLP+gLy1nKXvvXPj3/wr11E5oRy8lTdlue4BsMif8dV7xAVmlU52p38H8qNR7m0159426e0HUugW90zN9Adw7XpGQUUXeUQIg+oh1t4JETMSSmupRbBY1QmxsLLoJVi/C35eaUGkbOJmzW2rvgJFjVrawfueO7k6qfsfOamcNy37bgIUmEoVsMWdzus9bKC7ewh8T1jKzIKjbav8o5nwnM1G/5is/u8PK6DEc1R13uUEcSdQRlSBq1FtfLChIAiKlqekKX/upCx43HSQlzadyarnszMzeMz0lpUUGitl7Htpzt9f+w3VbhxhzN+0cMZY7Jb6XMNEFa98GVjHq/aTmoeFvmY9juPU68nICMBdqjpUevCKyh61ibsHVfxCNOZAwpRpRjLZF7w3SK1DGE9FMjfSovYV5ixJ0t/nkLhFJBsL4UZ3g57LwANDlCTdsWljP0FVd5iBMsY+t1I5+MOq2qSIrVT/EX5duifDmW3ptFP8EospO7mqpE0=
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-identity
      namespace: data
    type: kubernetes.io/basic-auth
