---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-history
  namespace: data
spec:
  encryptedData:
    password: AgCYrw6jgoW7ynqtlF+pgbP/Ip78Y8gO7smfa16KYWFxOlog2KBVHJ2/yrLWqVprWol+WF6/+WFswxxpsuxyIZBIhKooioFK+BJsuwZA+a29zYFeQS5zq7bRzMpBfcOCDxD3iPkzf8R+tlmFkcmFhad09UZseQE593zMvvOf013XIqOg+gLRWvt6OWzRULQd/c+MEqm9MSp0SuqVXuGiKUkqsSIT4HWichMchfH0OXtf1i0KTBBa9Dier8qxvtDERqngS+YsH/kzq6whuL3KxvzFuhCsv/PSuf6Kjowo8kgkyYf41aqkzHGq5OS2wyhiAitM9Tbdfu+pjAw40MYvPEa3mh2lKVU98UKvdcglGNZkeUvErWeh3fjQo4C7JWsH7W/bXY45NmDvYcKy/hI6QWFsvz206QRdudJ18lyx7EdRUU9td373mBiqD4lH/hmHun3ipsRhv8wpEeiXLcMqHcVY2U0/V0v1niVJ0EbvNaT1IYYPjm8OvthUIwNlX8Eh5HKAoK6NItzhZZ5psKOduT2UDZ76d/y5n4jqVlS1xyK5nRkkWeaqk0mW5HgJO/9kSuw8A503RJVD6RRTOYQ4q5TPxVO0bPMKSc3h6ECuq60cUyInyte9gCULdAwzqFuZWiENhZUIGFyLm9KoW1X7KJFtAvw+f2a5TNGwXCVzWv6FNhvVZXU5votGlT//rQZcFKwFmnScuaII69e4vbXrVYLcd6JrHis1/qiSA0qVgJ8c8g1B8iWlV/ClfqsXyqNp6BhVKuC5/Sul4LKo7XsBjgFigg==
    username: AgAFa0Z1N2HvUqdlG4l7ut4ZuaFWwWiQfbsUPO5G+FjJunsKBq+fdss0T/VHoNtGumP9LrRS7S4LyDOs5USrVwZks7RA0lT4CyxRkkBNjtSbBd0yQQ7+7shluB41Df26CSIr9StooakzR1Q2MeCu52DfA69QPNnXo+hS41SmNcxsb89zj3ZRmEvZNZs0Lu2vJ3X6vIpAQeSHNdgleCVIlJh2lbmPPY5AU/uoVCleA/aPMK1QWHa+3DRWE7uYgivlHER/cQpJLf4hSb3SYR6ffyzURIA9diw146D+a8wYSpMO1NzmE7cTDpA5nt2rowm1riyeqJniJoKJbhv+vaH5WL8GKrlNIDAsObs/uBlUN7hP9IkVIwEZ3VgYkEPFy9dvHZfdCLthdT0Hyp1r7nF2saWruTLmPT3kOTuNcYNxWxUohodKkqEJHikJ9e0TpqEI+VK1SgypzpvtifOeipo35mSeLIB8ekjUijukYFScZJF8Xolhv7BJ6icfi5wCrNhZ5sYug+F8K7ee7dDLjGEYSkpbfJLY7f7suGfA/wkgzs8Bh/9fmyMUlVdb7s43PKNwb1LzMqQ5cr/q7vqidVxZ8gVwSe+tDTQfir7rQomfPCYcf9NPJUpAOJu130UnuE/ObCf8PGW9L76UDKibecW57xwSiyk1aJHMU3v74oRFmGVp8aZPXuUrIjpivDx4DZGvADaO60gff89UBX4iwQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-history
      namespace: data
    type: kubernetes.io/basic-auth
