---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-dice-owner
  namespace: data
spec:
  encryptedData:
    password: AgAOtCU7uOF6lpDlkErqLt5dHa5UyHMnyFcZQxmzWCW5WQIIZACoKqQQK4cZWUIkO9JNQyI1VLYpPPN8zjG6y36Vfd5IHWv7RugdHwes1fguID8uRYUgyyI1p+ox/yW4PyCc6hgYfX1IVMDUbK6RLAi467tbtcugrGDseBzEwr6mAPgy4jvq5jg4zVljGyPI+25SkDRVXgQTKPN0BxylpU9fXJ9V5RrkDQDPG6Rg51wnm7nHs7wbuR7d/I4lwtZGJYFaAAbAEGsurglkTtP2GNDF5tKHr+5lBAPbu6yL5tZE98hN5cP790F5JZz9PUadLKGIRJcFDkBuPRst9any1YefEt2xHLJyLKUrZEm4K7yASDOQPhc0PWTqvbxwfMb+HmuS5wXgaZU2tUEYdUC+BhNDULT9w7ucr9cuRws/0eFEa4gilRutiZ72LiWpljT4YJ1R77loWfZwmdS8csMwBDfFe2xVbn/JioTHWj4+0ZaL7jQaTbjG9Wt3ElZlxssOn7gX7//dwdjZuqt1Ds1SncaeU4pAP1hVVjUI5SfAFmyOZF4Mw2EzmtyAvJR3gvZpDw8EvuvTcfTyMutSY1of7QCMQJ/BccI2/WywrvWBwiII/DsKtX/MYJeDPDOgnpoLjPMNXKlIvMkXqug+02LzK2f1c/JSsb9eEVFMKwz0mMcNu8Sn5wrfzb0BoaVMmzmr+0930HypmSgo/xsJF3wNnDIP7PTlA1cjdKmW3o4bRaULAPS1KNayeTjRYNCaudMPu2anLnX2Kg75R2hXHvkJ5bAFzw==
    username: AgB1EuFscug/sG8DiTjkAb56sTAoMT3bvX/WOwc1LkuReeIl3HQB3vOLCOV3uoTJUHQte26mpb/Dh+mf4jH6iJVh9B4FmD9NipQf2QD6wqva6zDuetIp7Q+4mC9Fg+3uanY+50e0qXdYcXJWyCB/1NtEBgCU0XToHUBAQX7mWyscp3U6nl8Uw5TDe4gdQhc7D11jiyvhxnb+xH4AMb6kBpVpfcVTC279Fp86+Na/GT6Sv1u5f9tdKQr7aSYLA9On3DD6WqxFwbCFhvfWzXw9dhzTpgpASkKsqbqDGVFaycavmBdxpgWycxrwhrbK8XweJLHLrM+SxD9TW7i/S6Gi5B4rqPE6wljiIxZPFZIR2AR4TXPU5oj5X8Pzk24E++Agzm8tvkMJjI+KeepAP0StuChFijX3nqdBpUQA08NE1kid2U4UZJVu+syGkTzJMnc35+jmJNqKNM32BVgCsLJgsUGDH6FmoEy0waG+A5VzyoRIpEQ/xpvvCx494j9OKrk2g0OtQ8UPbntjPwVbseFeBxGXAVsLy7+dxwbY0LUHABNc5+kdJ6RfbB3rqTC+AzyjtxdM0MYdHu9nOOXcaBQKAdkgqu2Dq0aWQ9q5ETv1bpr1bAhZ9+no8GsXi45tnM04ix3czucWQ+gEmJ9coPTwC7IvFKUP3hMAmr+BGipE9eGtRWU1bHgOeOmWdkB0k6jfZnOuICTlQliy7H4t
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-dice-owner
      namespace: data
    type: kubernetes.io/basic-auth
