---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-billing
  namespace: data
spec:
  encryptedData:
    password: AgC18T8sO5/ncPEzD9LXsveoDfYAy00MrCuEJby+V3kzPNTo8iIGgQ5Jy9IjCEMMhGLTdwgJ3Hj9EcJq71AGxBZyk3ieZh/TAgwWGtnLwmsw73BoXm8HW+R4WIh3ZRQZOmgrxjLAVdhBbLuqlewvik8WPbroylG8QtATdzOkmOWyKZDLDKo+Di748gzQ6YoLZm7KOQL7eMz7jKqDRIKymrv6cljWgQbi3JAOrV1seuOM5O+EJZVt6EZ/R1rJINrgdYFEMDrPH3JkexrJWhRxUEgZqMIMw4la7FmnTcG+rz3TOskF0Yupk8Jk8fneoWS3GXe/CoiyHG5dq0j8uRvABmNRp8ntapDQy/6PV6YbsF34hVSgcDdtWpXTWdFI51QJxaUlVFi/+yeGnQw8GqTzbViuCt7RMKBL0rmzrQ6w49QvQYBwTSSXWN4UGgYSziJSWZ7CTG7dddPu9mQnjo4I8ooWzziKI/4qgmEJRr64N/ZfHmFpuIjgpQWi+RdwSXNUQ+gJS3MoPT2eoQA32sddjLHtGpe8q/oMWkdiDmLt423KNNTpZh8HgKhyA9KrcQJl+Nj7xPCkRXGBWdm3ScujWJjqjuadEJfpshp/EZWpb11NMffrPER96XkRuYT5cOxrMgIzQMyboAzKHfe4i6MLZFDt7llm6z5nqmrV133E1QUZDaSHoVRuQPwG2jgA4vkV4aEsRyyorrgnJkn3KkiuQAAFP3aTUPErzCxSW4V02EDrKj+C4Idh6RXES9Lf9ZtUzjDPxNNWUJy3cfUxOaYscN7+JA==
    username: AgCpFryYLBsvqwQIWaF7OAq4ePkeRaDaknuIHagWFUtWV7dp+JuPDR2561qWxjVFi56Wsw7G3XC/bHdNuZDDcbGcjVR6kz75coR5enARBWh5BaAAkei3S9KZmjyc0gtfVA7awZNrujsJYzTrDJnQM/reiJjUSSYYZxFg1TTHZunj0vYEWXqWDh/wirV9rzdN+FcAXUT61hYMrF3AfLJm4jICGoXngkZdnI+2cNiHYC8u7maZbHxX+pcbLvtih4XUEISIP5cKDsdP6T+o7nZH8m1s6CfniujPEozJTufPXYFuZmKitV/I94Xmu8sd2XaGiSaAi9rZybSGYZpU7UGv3oKiYAGqtF0mNdhoruckeen8uWG29JegsD20fTHrcptgkBvB9p8KUnzQjyFhwCf/a2sNStTYJ/CMatFLeqL6/dWQSUeEco/OY/wHZh4Sg208L74NclKM0loTdtnZrXzK6ZXcOyTfOiqxVeNDwA7IywNlHoy91awLrDc1GkJy1XKrINPxuNY79229rz97KX2DxDxb7IdVddmfahUUuztAiMZNN8jjfV6zZBmEVgR4BEhSmE0ftDuVOjq4mpuJrSLcVpeNDbxQFdbn/0kYtTuwIBHLnkyXpS6JynYfHPu2x2pLJI/xc9Djm9zw32wwmmtk2dOXFZTL3gsGy1p86YpKqsFlJzBvaa0sb3/Zjs60u8ib7jN2WKX9tcNuXzdZfA==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-billing
      namespace: data
    type: kubernetes.io/basic-auth
