---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-prod-campaign-owner
  namespace: data
spec:
  encryptedData:
    password: AgAzkU5VcBS4YIAVETmYhT+85OrlcGbWi5DAjWv4xd/qx9FuuHTe9zcvrI6Q+NbdAn8gSMq7l6ryXL6N6QNpOQeBCPSz/kyPoVJc/FlCXGABHU9hXzcKuBfBoVD1LbA1/J+rgEhbbGGclJ8Nd5WWn0rHio+zR9XlM3qEnm/wX+qsAOR5skFFGGrc6wyYJo46x5OYEfaicIDrv+/08Ar6WQzYB4LtY5qqMHU/cs9pjKeyRQj3/ag2ZeMsgpmQsFKWF/V+m6GnsFT9quCmDENSZX/p3gBU8hwUweZ/nEo3qP5xlO2nKzl+kolJMDowcTO+31Wy9b5flks5cXraQtc3++0iOtalAkJSKlXPcH9XYFvu7NXCMDzRHDMJHlYdZqzWfLPdVF7+x6pfDRRExm93kocbVC8g5GA0odxK5vzussGKJJ/DxnKumAeJqN+RgWqCWHz+pIKzah3e/ReS/23TTFvJruJd9V8e2yZyZYjvEUh2N7GMbXo3KQRv7pWlJuv9lIOxGkPI6KTz2HdrEQY/71M/ztwabmLXgFU6bO8qNRMvGSyG+9I6IeMhRDWQh0gnw1HeDK0pNqdpNX/GEV8IknwkU6cRZFGqC1+0wLf/d5mCWUV7ctdfp+nYH/lg3r1jHnjhGLNCoq1TL3ze3yrPbNp2PveDhGKckM8nITCxJuExjT6UDKbraGMGvqQ+k5MjgdKUOOZPsdLo16XQ9ig16rzJr4EGCoqARTSWi84F77YO5RegFHojc3VDQXHQ5qHAr8Yk9BdqkMvkF9ZH5Qn+mBFTVQ==
    username: AgAU8NbwuICjf3/DHB58oCRhDeW7obsL/6XA/8H8kKzFv66BbdB1bOSYEyY0Nsj0gSeFwKbkqos9MUaLGAjmOfhFd7v82vSmbOX2l602XRO4h9Nd9OFvguauyfjlO6iJ8muYd4pctG6NJMwJqZI7WwKLCWj0O+ARghBi35G1Z247pY8hHmBsxPs0jt1iYWqUgZqk/4THURw5cXIYSVGUHVnlOOVd39RJz6qz9pb41O20ESzzqV/Q8aymf54OSi91rWjLk171Y8xjbk8Ae4WluaQDdCMiDghPxc4KHCxppvmmc+R+JpAv2eWRdfgdFWS+I4UNlwEyJQd9wAaPfDB5UI9EbdjPIFOF9LSdgSV00O8G2ZrQXEylKqCuRPU3OuXqr1jEd1Sl5ExmGdXBEnpwdu63qloySSvWlnwA9VRmTMZbb8t8Boj+J/+FyOt7trwHak8pAWmoyC/tTxii3Ae7/NHONBoNc3FhDR0o1vG0rcfNWGSCd5MNoR4Sb0pB1ROWFzRcdPNHJDaXqzQ3plYxi+nIWPuySXQpKnvsPWp/EnV+rKOSJW08Pmy42sTIsfFTXpvZkQ+xALF7oYDQaFDh/vkZgHxUjljP99H33CSfPnQmXqt//HwMhpbUi5p5qkHgOBXxnpgnTMvMsRsTtySI1TtZxUw8VXqml+sgIemzRVBV7a3b1Q7CE7mQY6q/+34vtEPUzo6aiGQg33JwNoJGug==
  template:
    metadata:
      labels:
        cnpg.io/reload: 'true'
      name: pg-prod-campaign-owner
      namespace: data
    type: kubernetes.io/basic-auth
