---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey-prod-users
  namespace: messaging
spec:
  encryptedData:
    default: AgA0wl3j7A0gOlBlSGN4UTSwXcnnmdcCC4ELSnIM1KQAC4AoHJ59N4ewZ+HWnDpDaGsPCS4VD9PPDzwzCKBvMPwRXziAC64DOkaFPXUlPu+vd+K/3cjkMU8AunV9YxnRHOr80hNJ+cp12bBuILj8JfPKCGG/EydPVRxVttMrjnHdMKhSEyQhzA8oUYyE1lEyGEn5EZRz2D0fkNNsC4/w/1ijaUpS0F9e77q1DO+XVCmWHjxZQz31M2F/n6V6bkleNmV84R5IAa5lrecRnA4ptYP+PxipkFgox/w9hvcTVz4VtxS6UhOOwE9r9vQ/m8TCHQ3ljknVhYBGUnmPzWKHmo55co2/b9pNSjWFq9jceq7BDPZ/RF9jo7rwW1vC/ozPPlVr56dnKEoRoLepIF8pA1++IcOi5GwDQo1VVZjHSbXytj09xGk8vhGlQtd0qO9ocnZk2ArrZF0gaqA6Vdz35cukQQNeKvysETkaa0KxoadB//GV0+TM69k6TLEY2qdL/TVswz+37QFn2rJjDKrjOs/5v4XdSpBI+4/4xNbzHfmIYNl5CJBg9z8ek+f5G5P/HaVVW+w9ZnVECDkLoS+ffLNHI0v17PDaw4gQKgmAr52ph4enq2aDIBXjqY+6laOYxfvoy5H0HcRGxVdXVCLpxEUIMHCRtuUH1zreigFoJ6uWIX4K/WFonzlm6aSc79cLFhigrXcL4gA8UZRM+tFNt0xjaDhKx2+eGsTNX8BR3Zb+kjfHpUH/dQB4E8/QpfekXqmTZn+jMmfZAkyjgC7f+q39Fg==
  template:
    metadata:
      name: valkey-prod-users
      namespace: messaging
    type: Opaque
