---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey-prod-users
  namespace: messaging
spec:
  encryptedData:
    default: AgCcgXuwaL/+D9xN3erCHdN5IcR4d/6fhwePtnNOBzYfV4WD/kaeK51kVXEPp+8WktKe/lZAx4iJRrdpjVf0k7XB1NtsoczW2/dGm34IG33JEA8WyHqA9ElzynJ9snyLxrxLOCfPLLpejdKeTeC8zxPmzaBRS9rL60ryoMpEr0Kf/ib+GFw+/KN8L4q6D61mkT+2B5nehjoiwg/KNBwlGVcpHkN/8KDJf9uDC7QMcVtxg0Z5FvyB9NFqLRmw9jj06e9thOu67joCpzwaKHR6JlQkqTAYNDC6HSbVtB6dhjJpCBheuxFzzhhTOGYHSlrrYLu07dhP3nAxgqVgQ+ot/MnUiK+C46jWABvqB35i4sVsrw0XLD8PgtyEhNWkqmdtpiHC3IYrVzNWOG6tKFxd4EijrnDAWfwvdyJAhYMCYui/e+qhwMfSNzBq77iiUKNBhqXMdke1KCFirX4ZHWuJCTJhIUJ6wFqgkBySa7rCqQB5m/SOWaiEIqrWoR/hVYXfKCEsFH+yOaEy36h1m3eWXwydjILT3p6LtLVVQrHhtsfuLqlkKXjop7eUJZSvjm1BvY56hpkfJf+GSWxBu1EZEyfhIJsvP+7ZzHMYN+hLvKHMLDy7mAMiVFpz1/yPxWIdVIHfsj/4X8Ya+o+44o5xyStYCg/g0f+pSLI1pNcih5NZb0ayYcuAjqAhleFxnb3cAThjOjlr7XZF1MDSqpcGsHg6pMEuaMl+i22CYqZbpxNI0R+xdt+afAZa9T5xrk7p7FS1uaBRNdcQrt7CvUoEHQnxoQ==
  template:
    metadata:
      name: valkey-prod-users
      namespace: messaging
    type: Opaque
