---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-history-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgCIHyEUmisn9onOwVewGkVECix+NMYC1oSRjoX4L818Y48Vml1px5kcZs5JmpduCSLjKvELTd3mf/wcdXZjsLNXv5Yf/nwRNwPQwKnFU3sFHI1ysUZXM5ISwkSTkzmIDPicTgrV9YxwVf8HfLg3bskspqF6Bn6SDHAShUKRAWwmQm6bl80BIYq21vQBkdaTl/dC5f38kpp0WtHLccvyIKINxoPCROlN84pP9vdSc1KFC/5tH//90fcjAKK4DKXhNaEDmmSKCObDqojk+9yFt2k6dV1g9DWtRTJS5SRP/x0sHcLrEONM+zix9qVSkR5V48ouOAw4RfoqNbVwpFDZBzWIOTwTnH2xqKItno1FuN3Pe4ZqWUJ+frv3ETFlF9CoPWvpjFKmjMTO38Oek8hLNZ9uqewE+TopNvIvZaWvspqG41IFLF91pA9TAnCm2ZB2Nr9jaodiLZtROIuq+7uRcX3ZwYPKJ+HaIPSUXmjeqSXQHwO40FiAY9NxaOCFcyZQgHMulZwp1KOrqcc5lyoF6/sfxXGD3i6899Bh8YGV6nwYVdF4dB3vocQbyDCUqgiYcjG/hWReqSo7RAdCmRENPVo+R0ziRRuK9o0mYo6HTZlWOILo1nVnoBn/MlCoRTxBchwVcy9gQxw/kxQ7eDSOH9iEGz4A4OtEa9Szoo4pwzOeKuUe+qFJanPwCpTeYAJcqeIAEQ1obvqoTf9aQg8QI9xyw59hTenVToW2D0aWSgn7htbupUMFkc8vZBCwD6s6NaK/Ita4rmPR/od5RltDWNr+QQ==
    username: AgBX85/Uau/N57fGH4MMHdmYL9T4ZevJ7vh0OyIm0H0RctwzdigdNfRvvKdq6WuPm3Uihqw3qMNUda90INSjqhPHC7mxVIjwaG8r30rr1Kpq+bpyGKM1ei+UuoGY+uzlXJVGh6f5MLVFsImoW9B8CNrkeP3pTsOUpyRjQxnLPPU/jtHMCNdlMZxZkNwDaiO9IY0vBRUeoqlgQXT0p/UeWUsDbffdSMIaF3Sxgdcj3nr/ORYcYz9bF66X+iFqnfvI05SSiqTU6psldo3FOjhtWsMCzdqGC3uHbAuHs/JLOSbzF3DIPhlNTRq3cpFXS/BlR+F/NuFnwK7VPO9q8mBMG/HoAcZl0jBLBhd/xeYw/IPLD9lWFPXCpxC2OolwkOW83J3y5NsCdvs7aTywY/U+TO7BatK/TDQSGcsjV6svCsebSduMB4wJ7eo0K1zzGNU44TS/T1DWQ8V9IZ3k8DO9dVbjo9OjQrpjdrbEWeEJLVEG2qHIo9w99bhAmpLyuRpQRKE4QrdynwqFa9Y+TQcVFdHjkzJIweaGemAMzlHVN1R1D8OJ1IsOHnhl3Yr0QXADjluRAEoLN1O2BqlGhLR/Ni0s7YQ8kBP0WNKFhCpj1wCK2ZAiz5P9fR1HyNPGLGclnEf774bAjGsSiZmbre9xttScgw+qYpxmXOzVAulqtI4kLu0j967Efoj34c7doE2Sn1bdshcwxpDOLqQzkr+q
  template:
    metadata:
      name: pg-history-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
