---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-characters-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgC2tM1z+yGixcc1kmU8xoEFq+Pn0Ic6lSUx2PJXNWTwvu8qzZLG0LE+LTNDdlenKa3bDRcaaCTaNhmoMZayif51xahsUehbObEhfJldToMXBG3GikB2qJBeLseZgGdWnqn62TgzdYWaQIQQM6EyEsujYoqNgTzDAIp1g/uQbZLvH746rmsEEflnrRZpz7ZT3NnpUB3BOzH75qS4XQxrupiY3cGjezL7oCVR7d0WCQuiIMSD2aRYGtC/Cxd6kz4o+ofMgkjUbra6P0KYrGwsgUKfS+vnL7+i+xvOZmZb4F5HVqdwlcBdUJ02B4D1E93SLwJiiUAc6cW8iZAc5AUObp10+5iZyrxgNcNt+ZhvbbUBgvjFa3KyX6pG6POZ9KujjlWBeRZnF0EQMdvKXgsvxdUHfZxnRQkkS1tbPxjFuN1MDGHP0Nni4waa7Kxuzt5TXMEnTEX3wAGOn8XIjlzBreYsRjTTW+xlt64wxvY8NcT8IPoM5wD21pnuDlyxOEty0DjukLdTskTEIU7zjXMhp02HBZ8ftH/flxp6PjZetRaKMBfCI5mAD8BK2+oUtJbsFgrPcFa/W3AaCN758CdRGiCeIWdXYNC2SQ/YcfzWs7j8zntvvQHLdKLQgVjojv6QxwUA9F6Q9pvDGHXyJ8A+YR6m28axppkV9oVBSXb9QR2PbRECl5C/A7UE6x2xAW7Z6u9oHV7pcCBPNGY4N17e4DvEzpcVDNsnsq4hYawzbe2Y0OCsMrbdB3WUrpYnZxlyL2p0708nXQymyGk4qUVrx07wUQ==
    username: AgChNZQmyuO9SwKAn0MN/IIbObSNfnqifEmX9ZERTAIrW9wMTzAWk6plX72DjLpNpr85dMSsMlBNF6tqe3EWaJImKW8kSlAo6QFK478wnoVsP5IZ5pJg9a0Dgl6DMJlrSQJHonSJyQCiE+R3zgCSOxe1C1EUS4iC6FZVGQ/jlfNUhspJC0yBYk+8Q3hB8x0HJsG3rcDCUZtqxudIjIUsjB/X4qNgsFq1MYJPnI5vMkMAXJLmEpJOTjrbfXfgMJe2WTNgVO6a2w84oezjVFtLZjH68v1cnSXq4i86VZki67aRg+/dEoP+pfC6LJHxZDTsl68KjBO/kryZ2eCSIVdklllQyCwPTUKBoPdvS/BIKdoT6w10X1+VhPcY9O0UQVoUPVO7FulcqLCRcmMvHv/fhoPwLFfwRDvztErXok4VBCDwjlZ9BFEiqxiFk0+osqgYb4G7+AGJviceNZygOm7dPXDLw1d/qORVpFnt6M6K7r8Ey/VPY6eSNPzdH7ChVjVexSz0Xa05XvXBqNew9UkLxk5PnyCX+WZ0FW7E94pR40/mD2uowSDNQMl1JBw0191VknSbFjNixRoizJVkY2hPsqJzfvt9ZuwCLxeEupq4WMyV9fMogb+zCAt/FfutVhNaF1BF2AhI/eY3fX4982coz08ef6mBvsamJBuRmC/5dEOxnu6L7rXJquC+OFyL/zscktEQnYc3gbdUqyfRFj778eTm
  template:
    metadata:
      name: pg-characters-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
