---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-dice-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgAc/Fge1DhPrY4pLRTLtTDnR6rJ+ExlwTcYxARcjdcc43AHu0YQQez3hiDryOO4d8RtMA9/I0FSZfg+xHsdVA0xfdFQijDWejHsCv/ETOsSUqHGHJwhpu8OcGJPouOMibX2tnlpELWRQBvB7IpDEKWhduH0INFW6K0m4x7LK9U1jf8QzGhK8pLu9DwUvC9rv0L/H9BSn2r7KgBGuySl3KOTBa8JU/lbxcplDeQaMoM+UKG6JJ5rB74MOR2tKqGo3UYYf4hVfOfFCd3SNtnFBOTD77e3U7eX75gfny0go7YMJiUgpyxroId/Cx/74bl9CtzIUtTtWSjmITGBnwb1y2/fdqitZfLPEGlC5MBLX3gCPa/lbJnAauLrai45TFm3Wq5tPYbBY3kZMlCWtxdOD+uSXdCEtDFl35iZdOEtTvmql3SlTS9nefLPthVwHMjFn55WRtuJV9TS0uZo1pydmGO+XGJBWsDg4HZzfxRNDzm5pwrx/q0sNd/elTour3RlF8WSC3W6UvaJF8PFVgojB049xfEA6+mJS8OSHhn6xbysI1R/Vc78+bQ89xPjTEI+yZ6YSdaP/bzaorXPFMlUTKAbfIh9yM2AyIFRxqsWJV/uGSWm+vcUlkkulMicDhxAuouJbvWSlnZKt5lgiOJnsyrVNYQO7X9r6XNh91cimharni+CyxjUyDDSJIeE2jvYJh7M6TwAr30hx6X4n6zpFTNAKyxcwib90Ub7As78/2MxwOooy5UJq8vJ1ZXQV/pWH9PYtB7MrZW1J8qKYB/emi3IQA==
    username: AgBmBLNl0orAhOITwq080AqFreGz2AkiD4AYduJAlEOopCQQdkWV5mRwBCBm6ceZHCz1zH6MJd0g9b1b4CNrujNFJWQm/5aIfcm75152YJkFbHLvFTD5BU7AFrqG1VdeuGL33pZbCt59z+D32fq9LFl1/IT2RQ3fk+q70YBVzAPzTz6dxfF7A0R/B+wke+N9mH4uWHN2KskrQqrTBQMKfZL5frIrbOz/kSi3eIOs0F8OOnJaz0rgQL96c2CadSolYcOQsIrwMErnX/lC+BjHBoco3DHRMpx1vKrCjkJSRmh5f0/LcReS1OAHJSisVIaLeO//5AvoX4yQ8khmSd9BotK31XzFUlZL8nqcDrXEdsVslMo/hMbgaPCRFiQgmcRZjGbAPGURPS0TmptHGStmD3F/wnNAt1lwMiyJyVOWHc5IYyM93cgGeZ6Bpz8a+GQFJP4N50MqZEr9lBRAXyKbv+GXRbSqvso4/2Wmhs50+IDMRBew+v9ffHFGLpplORloFsx8jB+CeapHjiZiRxKd+oqFvvEJ0av4LMntNSTIojooRrz2MuwnkGPGnDvbm4WTN6v9Y9XNcnPLStQxoX5w5gwKi8GhATnTvmHm/BdUNHASp45XKvwYbW0s/V7K4puaaKcrlWCKfNub4ROf61LP7xXZV09xQCyf8o/vtdj28U+Fe2asSC86QOUN9ycmcTLHh7iTF+tn5dg3gTe/
  template:
    metadata:
      name: pg-dice-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
