---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: messaging-credentials
  namespace: vtt-prod
spec:
  encryptedData:
    NATS_PASSWORD: AgDEn3UfPGwQ6UsJdojSI5RwiY25X+/TAjPUaprcVap1UbojE4mX2NsPhU0aA41z/qkNBpbdsBxVM/9vJhiTjDqpFcroFd6BXuTFy4bK0Od/PvGn7Q30t78qR/3F+oGhiFjItwKsv8otI84xcbSEpiDJYphm3yq9BQqE6JCtlOI2kh4SuRCyYu8ReLC3VUyM+blIG9fy1sMGqC8RFTGF05yMNlos46eYpGP/oqj6UBVssMJCraoR6GGEzVRyS9gv08sHMm3+3xoamZfpzP/hh8BTYtqHyjT4ww1aeV49cPd14ebTAaseYI5WF86ilWi1/uPO2pjbCtP0UkLFtDaLHfpQyoF1Oi2sjZLIZcpK7kalEfXixthmc3o/5G4fJZzY5sRX9gEoFyw/i2ricmb68BTLxj3yPjmUCnB/w1vY3iroa+kuF+SnnP3uNq30RPzUNW4dycWopCNsdnmF8zmozKx28dgkcgOwWAzy3vcfusSuYDcF1S1oh+rXdgSFt1+qBnGIPLNrw2aIjQNtp4g4uAqdq/JDxEW751MIV7DYVJFiVxaqyH3QSeruBvHZX7AGLiABAtzyjSj2zG/qzfAB4w6Y6lD2gYI0+xzgx2B3wpViA37jqxoaHn2b1djIgQXfbVtWDn1C1Bii2MwJYcYf3+5uJd5oYnAp8y9cntQ3xwAaqKaZAEc2G8AgsBpOd1CzdFXnARldVzGEdrB6Xoi44NdEv9DA4/VIdwnFFHKW5FNNJ0tGnOZgfhjVKrvPVbjBZZ7o0N+XxcDfRLgIWpxO33ZfkA==
    REDIS_PASSWORD: AgBzfyC8LkxaBzj3svMpZqvEjYmjNkNwV4tv8EE37xFXK97MyEIuET1ZsvAP1o+RS3jiOoCbcpvjVG+bzqocnBgCtn1pypx+n3C8DWMiMemwE2zn4orvKvBLU8jllTe5cMUB8P10OXEYLkWcW6WLetnzc6vPSTtnAx+5SKw/PlF+Rm/sbPkO1Ea74AQyB72WzW4Hu7oEEp4Ba6W8p30z+FXdza24K8IXhK8EMxDIS839yoBzLyXZaJ0CrmlkJlGBWm6FSSigzHHPmPf8LrodN/ZDhHGyPNgPVeOIpH1vsAK7+orSp5o5oovDqG+b1pE65YGcjiz18GHlqkO+em8M+UX2JsUXL7hJhdDic9nKrFzTMJg/WlxIfea6j3ZeFeaU+MvUYpXsO+6zrBUGN2/kJOpAY78auZwfQZrAuBMB4Kfx+00xNZso9MiuvxAY1kPER6bGwHh4jsr3Foo7O/Y/Gnm0DQbWCnlDoaeqAqpRM9nNcw19M3m93ot3wPHnm3b1S/j52485MGbH+cq4mhCf4D3/repUjgqqfXq8x2u10KB6K9RHD0Jwx4YatzNEMl34vm2WkMv2ZaPtSnTwknBKOzxd+6azGkeXYy8jYkj6bGDR6hvspLRrcQkE5nvMfZyiziMLPTKv8J3jWwIxRizaXFCuX4qRO/wB1SsXNv6f0IRcMd2KWOrPfvsv7SOfk5xkHQfxqRafqrWVucF1xqLutziTuvriNcpO4kfIyH7En0m2wsOQ5ZEIWVxR8vvNQzm0nasxl5LiYp5h3qjTthocdKwBxg==
  template:
    metadata:
      name: messaging-credentials
      namespace: vtt-prod
    type: Opaque
