---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-campaign-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgCghXeTJc7Zuwy8zkI+17VHAGxD+LHut17VPMos4kroOObJY6tpmzIa6KVOcEKuJ3AB8lpP9cn2xsSHV5ZtOzlrijuF+NVsObJFz046Tm/0WMx/p9+SeeOPwNnpdQMCmal01SRTNwpQBfpDXEwAI+evWcIWQs6w7V/RWKBevdb205EMkeEyFUz88WE/Ws60not1o/aaci5OmvrfG5qOLwFgSNW2Cq9ej5m70QMM/P+JL8CV9bAbu6Ya18F5WqPZWGDRsCnapj3loHxqIK3vvGF6MmRdWh+3NCr7iKbNxpr33sM+/ATxSyEUJak7XmzE/btC1EgmllruNxvvyvK/NPoNvqNq88B0pfk8eDK+hfmmgTPiQhYWJXlwBdVt/kqgrWZAZwZ+BBi7O7uimA4rYuo00sXoV4+cevi0dulRPDT9b8eO4tPeUqeWM5RtyVpy5BG3bKCpqYshcGKLMiQTiwJJlbeYRExt9szqDI3MzmvU84PH+OyVWL1uTmRCVTvvCB+auJ67tmFqFzJ5BTYDYKIqUvFDqDpoPF2+9FVAGSfv81JIOjCSKz5G+hMAL1MwLtEGyK9hIkeWp7OgybzbEygcGJQtFOGwHZHpI8ma1YBaCm51oZ0vWe6jK4mnzkqQ+SGi0vmAwzzrljEoazTzInvow1G4DqB5Jq+VlBXRV2zi9vnVTOhlGDuuyxP/j7J/REHzdMqq/eRWlEH17fExcOIAwh5H0cymUq5RVx0Cm0dEM+RAzpkVkGZQjo8whc4bRmWndU2G8TVEL+gz/WEBgcLOcw==
    username: AgB282GOl7GnvV6wLaoFzh5LfAH30ctxHR9xhYLHxi/Ry4d/tI4Y1Z3FNETs50+PZopwW8szpFt+afB2gFyGskr3qsFgLmzekmwhd1/IDZhPiRFy5pWMYlQnpJ7HLny6I37xlg/iX+XLKXHMFWjI6STMy5SSZxwEBJ2d2rTfA67oL2cADXn3NnF7cwg/xb04Y83bJTZVDZIlOIr5JlXyBdq9SB//m3V+bfPFHei/VsjLtoFLYHHu2ZWsg0P+87tKPMfHJdDaXzgzxpEecw8cmvWnx1QHRmaBOEQlcJT+HiJs0ogdWGMYhNpdppydlYnWwWyUBerd6PbpiQJJJ1Ij0QQxFF6dY+jFLiK32PTFmu2+3KgcOnKYzvte7fXZWuD7BE1pEFbCmI3ueEiNvcq1ytpd6NFUJfCJKLYYbakv6oGKLPkYoB53F0Im3huPJ/RPQOvViHzTzzTQb3IcoDhJsKjPRWDSIMXbFyrs/PAEDlBoBpYZKp/Ot/DnYThy525Pc7Fqdmpxfs3eyNaGJ46wGsDIBomdKFSuIvtIOeQMs8ZBdRLCmAUfLzRN3IapoUW4dQrI8zQFb/ZMT8MvqijcnFGzeyCpDXEseIR+cgfhwg3uK7/GhvObxOkhZB1UXiQd2xzvgVIzszWOz7H6p/9UHhbm8ScksRZbU6e66/4CDmsZjGbTgvGB5eJYmigGXejMg1738BgkKQzTBa2nPPAqCQ==
  template:
    metadata:
      name: pg-campaign-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
