---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: realtime-secrets
  namespace: vtt-prod
spec:
  encryptedData:
    INTERNAL_API_SECRET: AgA4vdpEF5BHSXLgNCiRpl6l1y5khcqTJmLuzPY28ssBWKQ5L1bCCScw50mGM84LUDD2waOOEKcl/uO6bcyFU9WUtmYLHboUQ8Cn3oI6XhRGFO8KtIKArFJyxFqyZw4sCgVk1VV66o+QibYnpi2G9zmqkbKDcybE/94QnYjJkJzG8uOsk7Kr494H0y4SdYPlcxN82Fndp/o2cXFYFXBZU3fS+PvI2XIcsqqkVLZox6HQ62NNT7CfFDi7Pdiv3iALCQw442pawVaqqwREWsaGEmwaF+B0NUBdzSAsfth4DrsfTvrpI4VxAiNeiBvZSE4k7jnhzKkXaj1P6A+DF6dqJoAycFTOZZNgkLl+yK7cQ+EwCnc1FezbfQxuPETFKbBGwpeTfsLxX1QCImP/8CLP8z3gWE9Rw548N8AzkqQ5Y/1x7FZEHShUKI3CpI/BN+h/hneWuSwQRXLY7vexMLfQdGS1pqf/rZ51QAkiWgivBNM9oGGX/mMF0e6jYYGzOiyXArkdZUH/rSJgossgyeEWGpUPs0HHBXmdFI+JD5TDs8uCkt2KYD7+Wvi4DggwTFdpTmKmC6XR9rAT09lkSQrStCwy2X7wsMYX75KvyG3OFrBUlTiso6vPFPdCJDHHHM3VXPvR6O2B7cJiB8bVKzIaujd7Eee9AVtSdeK/SD0ic93o8nWb1Q2ZYrYqLl/sOQKvEH6hGVbrs9qnu4P+9TMUKRd3iVlq+U9MipF3ClyZmNZOL5ubjIiy2T0Ktm9Rm2+rliRVNQhMf141NsS2MTaEo2dOgA==
  template:
    metadata:
      name: realtime-secrets
      namespace: vtt-prod
    type: Opaque
