---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-audio-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgAZZ9mxPmT/9TmZgecVHertDg+DeqbZOTvhrMjwKDGHRMagzZghNwPjmp3YKOKaCj7DaYIQ9ZF9o4UPanrINIgQqCge6Fokz0G9i2PRjCyL1GN+Py8vzjJykJl0+si28ZpcFHWHZMxcP1hmxBIO+yJKP0OOdC5xN3EjmzjgwjBnhEmYHRrxLQ10ZyDhV4K1h6yY+h+Tw2Xm1zvkHKLKOKqIgzeW77OG+hJKeDHHRmRJyFrizdd0iwxz9cwQi0melHkK0Ry+Q1WdTgn79SKY0vUo4WQAVMnyXR5hVbRNF8hng7kmxBeGZjh0VXx/TOrwOk00EHvCQj0eqiljDeOdxHiAwxACythBFQ5110p58GqbLmEinp+n1zSSrXaOzu7WyEBWUkAmInkVxaAP/ykqmMcoqNuZLx+fhXLsFktBPgzmD5uNCbIIV2JmbwynK3U06HAzwda9JIFD8VDmCZ0P9XEn2RHp5/6675npage0JMEmR/qACKXZD+FHnEnM/WM7xYoZ+K0j5y+3308I+LrzGnkUWmA+kUpZtsgqMbwTfWqz7SkugGBk1ks+ZmVUXuVp6tRyUGy7qzmG+QxPry4B2/mg+vRuip+L20VS7uTowrLhK+cknqWuH8IBvQfh/N4/ht+aNTaTBxOpP3n0LjPk3eCtS7yasmhZ7phKiQMBlonXK/rTGDYcZ1LOrUOg4YwNMztcnPp30m7xOuXDhazVQy3QhwoBNKbftDCif6yL6Po8P2eJBGq60lxiszJZsymy1S+OJa4pZfMLTlAYE/dX+ZxiKg==
    username: AgAwPL+iDSv7Jx1v7Naf6g2xqJlUuAIRvdfYrCV9AKjFOO+DLbU4qt0BuCw9lv1flxJ7MenhsLHGO27qDm3zi+i81XcSUxVPDNPLfy/d6SuGCY7pks7ClGBGp/Xoedz+wA1v3AbbgaHMU8QW3LQ1Zwgv2xn2AXyO20DVG8CQgx05LxmAYAyvaiQRks6E/V93PRQDuXF/YI4dftYa3/CBwCTeCwHC6s88U7W09hUZWPSC676ebUOKtZ/ibJnOYDhHOSjpBc2NA003PVv7DWpo1jhOhHyxj9nMf4SoXRsvsj1Guxj668Z6BpLgMZ09/KM59rcX4LX/AQZN4FJUniXQDxj6ZXu5Yow3sD/kITPLpx/3DXgKvlkB8BWw5PoK4hsisGZd6kzasQ+QBDgQsfK5PGklt9xeDcY8MzuInLpfLn2R1sF/RNT9gKInHWXkhmCsW3Fd0jwjmmEnfQNzLubEwyf82L0ZKKGUuyIqZT2pCesJkpJOhzeF8n7IK2KE2VLT5uLbhyMH8MCGmDcjULIZ7EnA8BesVqp3MVR5LEbLro7G7B7n42pdZH467rUOGWb6QC79KWEF4HMFUEgJZ9O761jAV6+A6vHQDf6ro53qohqpmihm9K8I4eh7fXewr7IEqMkRUNp9UUtIIIN2XimnLqoJeE4ddMcVnG15EXrl+LL6H0Ec2fmfzrY/N4lrRFRqUGCwnfbIHyhE1+JW4A==
  template:
    metadata:
      name: pg-audio-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
