---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: messaging-credentials
  namespace: vtt-prod
spec:
  encryptedData:
    NATS_PASSWORD: AgAQvAOXiHILctLsr1JHp///L6HayKP1sj7pn3U8IhM8Eb0DF20tLHzRBeB/i9Z5Z7xfbbDrV9zw1bHH1aJU7Xi5LOhiqypdabI9PMsNafp1WaIuM4oHOhhIxXMRf3A3s4C7l4fdxzVtFVm7DcLXkRe5aXGg+ri+54gtK67MKb8RHmg0aSEfLhDCfnWIGZUl9/dyji4TL3ayuMEoiIivfLa9wVBLoMF2f/Or4RnvTvEAj3cAMyb2wZPgIdmLDN0esSjDqKcR53ubNuB2ujDFGz4fnHaqFJ/GKd1uTtzytMkupcJwU5VKoZ/KRp/ILbapHfFD0aiPxKPKz9dYPTuynx40599/3T4Y2FRHbvYX2jy7wxhcUQMA7jYTmHbDFeihaTw60Ql2C0IClJVAgZUodjzhfkKAH5z1d/yi+/xNMPNRxHB4nDmlO3JZlUdJ59J29tdhevENELomqHwZNvFmIKWHEE5NnERcor4fHni1Qsv/vXrO0LCFFh62IP3PikRmYDs2U/SYa5rLOV0d6V8d8YpGsE6+K7brKJkrfVtRERyryhUDmQ2e/R+iwx4fS3mJNOOr8h0P2aROCEzp+93gHatg5Zt+AGJrJAkxN1xJIIdUQ2bVp1KNQKAXSQ3kCnMS7oK9ubNpxkVzDC9VukmLSsBmBAlxPt9IG/nUq/x4oBOSMqfhmB9jwSwBSkzm+/UKGkOORktlIJTuCmz0ErAGTuhqoqxPxoMAUX5MQ6OMnGvN4Y2WVGHNY13tF402eynK2nKre5buhaow2Z2TDdrOhVbc/A==
    REDIS_PASSWORD: AgA4HQv2nPBD+SUJn85jkAUyOB1FTrJos/kcsD+/I02SYGOU5Bs/sBqow6OGM9r5eQdcg4PJdrp1Jf61V/6JXF0xaXKPis6JD42hAwgiiTTet7DQ4+iaThzYO0QBoVngeCUEb3IU8lGBg/0vEMQL+QyCqTxCB1vY04VUqEd1sW7iDEuF+K3w+HpDcoNIseabWmo2CKwQVSgKhfr/oCVBkTXKqZ0FnFM+hVbCJRxUuZu1JSemK+EIgc/Y7DEXxSqSF8edYoDKhuQtuedn224shUS7E1UOpp5mV8fmY2T1SEuBLlSz9DzagpJfmjyrghbUsVgdxLKP7Sjffcfoqe3D8qFqPJ/eitnj3SWYgipd21ibscqc3kRRylxXbLV0U+I0qjZweix1Au6fuW9sEV5/FdvNA/5LgmSZB8XKtIAYNITbXNMI9VBkeXVy6q5OowxhmAs+08mMedWG0AB00Oi1I3CrFDvb3K4VbI+zE+v8g8rCOoAvkyRNTKIbnXWJt/aQh9FTZT0hzdPi5SdRj5OQd+tacqr8vdXJr05QC+aemiQQJzwGYWHQWosCljhEg1K7i3yJeZUvX8BrqZ0IvJ+vDyjzLN6WSTV0kPZRFjuozuGnPwUrVRulG0cvCKwdcCZBLlViWOxxQQtR9KmScqYhgRBJsBcKNqd8R1/24KBBOfGHbzj36Zj91CQolmXNQltWbahC6IhnbcGCQflNXbR9ghFpJaWOVH9YWftwksuEHTn1RSBv7vQ5ffvwtKhAoyrPHqkPxEz31n2dszaDzqr00qRz6w==
  template:
    metadata:
      name: messaging-credentials
      namespace: vtt-prod
    type: Opaque
