---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-identity-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgA9N3igYw9FP8NB4GKNRQQmkL6VZNaphGyU9pP7zHKjOOmBdNfHS5HpsdC2qZEf/JXpNshjj/87l/qPrpHlZpXPYJuDxmgjfloxKtX3DBfz1uFPq22vrCdTPHRiVcuecPLVjJm7ikBRjJm3oSIsdnTGbUMH1s8XH+wp+lBje9Q6TeBwbMAmAxHY1IZjpMj2cVzdx8VeK5e7l4QY+vSvxy4bLa9pAXGJbUNaiCzXprpYYVXs3/ygYJVkvAnG/3qWQatxGTRSE/eRPf6RoQj8Y89ymxjbvaFigwiVLTPZg0nwcmMiQiSQK82RcdoAqTtwL0rNmzgh2b11tFFmjPPT+gLp5mv6/DoizT9IsW9vxEpGRHVTZHNxBev/iRQ3ujvdXVUxU7m+x0Mh422fO9sYW+YN4eA4bymxQueHNw0vhKKb0cxAonKfpfjnyJhHT2SAIne9w7sMYAxvQa1leSqi0W0vW0IZQVGy34WBnNFWNnJ6BlODApxBKdQ9IUdbfyG70jzFiLKqV+aLF4QKmlxKtsfnRBTDJBlH0yaRr5xpVK3tSHBomESSVf1EvAwsrTpFDX3TRpxJkfWwlYDhD2GZrxrzU3Ke/Nier0Wvj/YmttyuN2HH9FaDX4EeDGPiWWkU95GfSy8thz6yIOVwwekwTSoHOTjV8XbHmrKgyYebx6+Ay+M8NQLs7rF4AmJ5itkwKJpiDWxM0ZNSG+Um1UFHIY7iTTDSeemB7l3qj4Q2jqPj2h9qFksQB3KI6mrTL2cPx89fZrBYSu89Eswx3u1mYnZZOw==
    username: AgB5O9vrv8/cmuHeAEFbVZ5f7d8yg+lrT23qY3TtP5cm0IXDcqnvJ5+3L4PpUop2HlKk3kH2Qi+swqrnStA+6fr2Xvcw01OnvuI7Q+4gzotO8S6ni2XiOwutPGq/L5GlGeGr5xC42m8P5enrfi6/9u9fMt8FlElUhAqx9vox/U1LtM07GH9QgLxG6YfxEDEHYUFN/AEH6N0AP5OoXMI2vTWOLnXyJ2V9IWJvAiu01Yo50oyZaVzwnz5knSgHtIk7pWaay6MSFRKUz6iPXPSgS+A85GPXefvfkhH0pbNouKyJvRwaYr69/J1gscWaG48WSBHmvU+0m2R+UeW5mgZukxHHvw6rS4hBafkthT7/hZKivaJ4IzaWedUhPCYwsZygvtkBIjQEoGoOZC70t6oFfsboAEvjldz/4vrFP8PRAyuv/0YSkUWR6HWuWA6NYU0C2jLZfv7ngkpboDYx+yDlRJyL8yG/z/XrWcm03QISkt21oKwePmdHnyfrXHEAjqDC3YJmptecsND7My7NMi7mR+FIqepa0TDyn4UslPW/NyISeW/Z8zceRLxBcDWH77Oihbe3YRQaw8+94wtyLBHVQpG8sSpzWRpVJYx2syEVfaevGknhOVo48Lfx0Az/1HlqloTsZLn8wpmvKYIHkyN1XEVHo/YJC2C+fZsuoBBehaLIub6xz+izCxzF/Z0Htt+2j4uNFp+1iiphBotOHU1vsQ==
  template:
    metadata:
      name: pg-identity-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
