---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-characters-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgA7WO6L8xvMcD8vT08H1ClAeCukF9YeWkJMVntuLLL/SuMCE8DXqyz5oYSQWCFBIMlpytDXd49GbKogaYIR6LwYhorKtsQb66ac0sKvbvb8xSh3YggUpPEf6wA+eys/R96CFct4DSAMgdUxAYXZn0zV0iqC2TCLvMJelq/xE5U99wmEtl8tN1N+lSiKe08xWWIxeDnLMVMMCWnZzUuVaQdLR2Z4woi9/KquKUfg4si8eDWgUiXsFl/0rTBVUA3EnMrHRFuiUplloMU6y09YXVjpPcll/RvwPg8HHm5DaUWd69IC3EgQAlyxpYa+2uHuXSqiS6mCbCPCL3jlUbgLMTiA4BIsTQIWhm9RLmiIDqnY7U6jsf0af2Z7TkAjHvo4AICc1EWHDBCTligrfdxM02g1hJZnuEnIfh8D/lSnTomSCRXbw7Fivnx6gIMKEMbInsfYEBPFUFpA1lFkWRcCsFZhMaUpSYLF/oR5gzA9E95OujAscGq5hVu6lNEkzJiKYHD+wMIsKap4JDzXD8n+FiygQauSvCrgowLcH0fQJqsGpWK5gYxlTfx5P0hnAEhFMyh7okCWdPqw7FtmGlULET1QKYt0TiGeeUPoqpoKprv7pW++S03XEjsJPcR3w8iVkkHaI5lTLZWVZ7SBzBToEqRAwJM/99Bnrsat+IH6Gs1AMd3P64Lurp3ZYPGPjDcJ1sezlQVZ8ejDsOgwQnkCcw65Zwm0RSlMN+7rzEiJoY+RSZHCrZPn4vavjuYOZpLCFZfCxP1UDHTuw8r3TGn3uGH/EQ==
    username: AgCsEwQfov2JViicaWUhFHsvtlGtZyeQk0/W7kiCqdeAMU2+NtjCzAewlgaWym/OHqdMZ+99NRUc0bIEHMZXwI2/6WV9v+S0+puaPynZp5W3trZ6zIaqTF0CHJ7pgfozXAit3ApNK3OPd3eLQXsZHYaSJT3twhKbVm77Y4tk6srpoqxDNsYR3t5NGogT7tNZ0HJEX0nty63Bh8Q6LvS+5XtIWsyP49BaGyN5ES4fKoGkKl8z68vLTdq2/789ZDAKqQC1+SEs5iccMAywOXu3u554si8xrEwRkZ+foHFBRhzqyaIg/G4oEHsVqjb4cDCDlkuw1WM1zzf1xRUbcUVb2XPqRXV3YYzjEyBm2Qpdl8AqIym0M+NY7ZZZ7wHJ2MWe+47300vcAJNSLooPRwdET3p+LFeKjlxdB2Iul4nyvrhZxouhHh1l1pW+VlT9qCj0PmkT1WHZPgKuj6kOGHP9oQP4mh45a9BONhG/p/0Pn4nqq9MRPKrqWVMH28gQkQjDovV2Icf7H/hkCLsF4YYWsWY5adF4DNK/1rCg7ghjcLp5XtijSEKwzM3isBCMIFV9VZsVmWROBfx9+Y0xc0h/0nS3cq4sFSlvDm/TFl4lWn3Gk3XRLj9qLesiq0ZWKEbqVPV7gd9hli7zZ6G5tQDi7uZUohhp7HrfMoL1G5zBsip2pT/XPYwy5yKvKTjN1p5ZYPkhaQSNH1Y4j1BuMpZ9UkLX
  template:
    metadata:
      name: pg-characters-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
