---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-campaign-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgABR10xnksfXDsZOeKF7MWgPBN9bMr/Eh1b95GBJq6azmhCnU9R2up0WUYm7Hm4ywys/+6h9uTDiWCYY0BIEZb41+HA0jL7x3Q2U7vYxVIUkNRsnB7gT7DLdZE4G4diNtOSXDb5UyDOjvbrrosX0Uit8jfH1xuyJuB5459KTBSZBIuSXkxIu/dbrAoqbQ+Bf4bTAQ6899YMye/+MKqmYSTeYbm2Ora2js8chVpbzArN+Ez1breV/ilJ2ik2RN3HbpHpnw55rbdoLMeIgu+qTrt7BIMt9ACsUDXWAu8fZX2hvRPnvyHuxbTRPVAdP7EoW1119WF/8F/xEENE5MxGFscyyRO0TXFP0Hz4ugV0tNSXcCC7R3fVTxs+BFCNSX7A29amYkj5d6uudzMk61JqULiVrIeS2j4PjBEq05SMXKjW5LyatlVNzwrs+zAjvUoaGNM+dsgB9p2eouy7mEAMoLV9WwnXHpiOW8v2CxazPDJRWBqdPjiL22ka002Z5iXK8dLsEtxmKufngeY/Zn/OMgu7DLbvbvKrbV/v+KcLiPDMX48tCdUP7NYGfqdekVfTcWRMXFJ+/clvqEdrvcADtMd7AH5+4EjpMieUJgxoGxUo5miHIwXyfGAoHTFgobZFqOxKorUGNzwNSPArzgi1sWMLH1qdR6FV464XTuUlBDSJz1hK1rmHti5AOo1XjRNy36A+NmBsJyjbeD1vw8SV4vlhMH9M8HxEn0lCkikK7U71rUSz5TIIzoz3wkecITVasKRm6MOJIzJXMOJgV6pSjlwWgg==
    username: AgCz/UJx5+rxY265Jtw7biSH+vdMtveY69hZbiyIcj6fm/C7ZH9mBfXnx8VmMFmJdt24zm/p5MZvqQ/RMJktBm2ajbzrii65oqAihF7R0n5WNLxIAOUml9g2GTomfpw3obNwWHieK01QD+NdhWfv54MJneQafWsgcWz4arU5DonSCP2B6+FThU8bMq5j2r+VoqetC0gGJA+9tc+Mt4FKy97xFcgaAdosTAsFnC6PwVVYSDUlAPaOcJWcf4Bw9EBZtb6fa/ni4Asc6BV4H7O3xbtpV1x5M3yq6pN6LRKfvEezy9CM8M2JJLX7fuRYHqjwEDjyCcDeEPNzwkWBOPlU2pv4dkqqpIMS76kN1q2DgwE5a1HL86pNbqGdXOhDAXdoL+GCUmyjpdVzDcz/7e5f5bAFPongHbDNp6m/NVyQG5FfWQOy+hzxseQ/p0ww2OgAoQR3J1YVbFAnNEDOfSk/j0Vqpgy8l02FoqqNyGIa/B5+qGVYZ6GqbcMnpxNmJoUs568tzPhulOaBVA9BgieBYnxcVQswSfKmh+UVDg7gDnVKjo6dGJfmiOjDTDrIYcsFx/27WKTm37af2XK7H2sFfkXH5fEaVRfE6cs9yqOEzMVqSA6vC42ZtDCHxlWzIbLH7TYsvnDh0RyZMwyiw7bHcrpa1EtFQJ/1T2jVrQYmpWcK5fb48Bve1mK/1fhcU+GPGUUoX5U8+BK8LZ8tvk7/bg==
  template:
    metadata:
      name: pg-campaign-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
