---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-billing-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgAkpAsJStuHvA3f6e9Xw9knvQV0DRl6timMfcmWTEIkmrpY+MRzFy7xk9Vy48510Wr+TVgfxfXI25k1/TmgPMpWEno4LSU23SJTGHFvOTrPqmmW0ir1Sk1ltMz5k/9Ls2OleQLUtoh6MJAsdQP2MZSU0j5IMEgLotJwzK6edJOpo/Z6wrPP9QBjZq3kSDbxY6EiS76s+cxeIkMNwSsgACCFpm7RM+pPLeSdm3EvDoz2ns+CPESoIrRSOYnXg3EarjHaD4KcND80IktxbrAZbr++XYUudare0kmbzlmLKyPx6r6cjiHcq0viQjP3Mkb27RhEDugZV9wJ9APFPPOyUnE3wUFwcWN9L0mlrH1u7szLiEzP/EalY8HjLwNqVFpUiJ8ZYBC4Lt2ROI7M2zo5CiciJzBPQlrznMiHz339oGC8ZmnAZ8WLyYFdLJWTfbgnE0YYRHdCBJbI+Qi2r7p9nEe/SknhgwyOLimNM4g5Nr5qPJSaGwLiEatd79NUDlRVAx48HyY25WQh/rXU/IqnEYC6E80SsJLALM0qi2auInqJLXYC1mMfmhYCMNEAeyT2/ytb8PTt4p1ElMK+OhLdmEh/NPtH9+tI1rRuOfAKUxDGO+6iCyS/b5QDaq4Kk63FR0Ym1EzNZ43COhg2PBOweOBkVYlUvkBennQ6qkW1KyeL++zRvPXZLMJ6hPomc5e9hNdOHwaP8V0qmXaSkE4+2jWQDgcyuq5On0LYuTSDDyTgU5LuTgGYld1N/GPJR+Q7RuH/kw3QNpJoEUjJrrFnh5u/sw==
    username: AgAxErm4e+frI80lcbOY3eFFLXM7QizHPaCSWixS4kn6W5jpU5KCotXYPDq87lJO3OUkCCBua6L2BizJGODhbG/DxOAJBsE+3EieqPyA8JX6zh97uHM/5I4z+5PFFL+uuxw4JQNGYtAIYn9Ccp1pwU6XFJohCUZiyrj2fE+hxCSy+s923xAoPmmp3nXh0btGTVbkn0E+M+STNYxhNoS/12RVhu139goCzSNI3FyhZ1YkwoZ9HmBdi5gz+tx2gkxFC/vWi6oBeV7gZIK4bELypkk3VONotcibOBUiey/uyQyEuxFmIfgNG7XCcsOpwBVNDDnQvhmLs8woetsnOGN2iEYtK0rp+9XeJ9c+PK3iSx3GmRH4ER0k8e8ZXoVsX/JRTNhOhRopFIUNUkmh+Xcvx/Wi0j9ykSOBs4Dhq4IX4E3SWvdayUcSgRlwmbM8deSKbhd/TyBkOJ+Tr1QO10J5jM/eUCyKeH/UHeaQj+2dv9nP+Fl8vV1HgPR3xiNHguLOuDx9wDzIuEf/3dAHLlUmmuREYggS08+VFllRepONa+x4abs4Ee45feeQDnmgSWjvOkHDhKp1JtbAyjdQKcyfXBUxwN6XsHDoLJHrQ0sxtXcPRX/Vx8FuJ2WPE01XLiMUpBszTWLN3fpIhRfongvctBEuEMV+4elvCYWUQGJOTxheF2g4VKgarisHcZvxP6q6A1dFMd0tZ+JRiM7vunI+
  template:
    metadata:
      name: pg-billing-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
