---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-dice-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgCMhzxlUPKLJ8DVM+D2XUG6W2rA+DdMSVohz4Oszoj+hNsitO+s1WG3uBQUz2xaJI3YGlUgWdgsWee3mCJS8bLSiA3fLlB0PjNiskMjbpMdxqwQI7itX+OdkTmqFSNiKD9GzVr97Cma/EimXVSgE/oNGt01W3TbAiAU+HrcUetD1QbfNGyTqnbzLPsLbEOrg/iR01qxCB8lbfMCJUQ6lNXn9IurUVt9cdNjFgdCX448iPX/p1EifuauTu+UItgJkpniVG3O3u0nZ2iO5wBhEl6YE8XJpkdy/0TMgcwhSo21pergX1RdpyFik9TiHBzK6zRhCEvcb7q0yu5lb1ieJULRkHSuRzeKPijX+/ubnEyD/N43pp0X5WvZl9oUr58m0VmlC8ExDaVo9nss9Jtw5/pG2vM4IV0McMFTGE7n79uvGK2OUjoFTTy0Sgv0ginX0pJ9UZKtqSo8fbFwLTouKoeWGkB2dCbgFBsDa5cCdiAfpWgjJTN/yphg6GEUR0fpGMTRjJUUewqBSlWKPmSsK4cl2KlVu3+JKLoGVfZZCbikq8fAHjUmeBFruAIqgSXoyh5R2unLSH00YyZFbih1oJsUWSyIwWyKomFRmNRTHpgdcqgLqGAtP3I1w3PiJ/L8b81RpgPUXRbX/kdOVW20d69uu81lrpLpWh/QZoBt2ZNqu7o6TUBYLOEYYdIqJn9uO4zAf3w6ZK8eav4B4R+urAqk6snMxKw5IdPmptM4QXrwnhsqSLs+FdXHt4M10IvNGPTLSootUqDApzINDzfQ/mV0nA==
    username: AgAHORG93Zr304GSJvQGSgFleY0/EQ7grCJNR5XAIjJ6PZCgS3uaw4qvQm4z5UoPnA8ol2FbDhjASEVDmrWfPCHkcAKcrDGRAdNx0jsqBNAHFKw4DYqqYAIajOmPv0NmhKcTecnq4mVMQoOnHtvQ1vfiIYi6ea/91fxij/vHsIjcVd8b17n8hJbfQG3dsIdjlCgnib7uOpzEou4CcQtsfvKiHYnbLehRkdmR+KW6Xox0FptKKAQGwrTimz9Wt7trsPoXdasYbLAxRPCQjw+VYjYZxDuraGCzGib6GulFnXPGgqmxasTl4GJOmcoPad3GAVb5JRNdF0i50mRsIAJgiZXku5LP0n6JrFcyyv/lj2UprjaZmO5IBDS6Qv/SvHRihBQzm8aVLWR/DBLbtiGFhmwhFMbAce8CpH7ZLffRy2MUf3tq7xY4w9L5Rcu3gnYGL01SZ9J1TKtI6cO3Heakzh8fRv7l7nwh+tw7dgUGOlaM+4ZqP1l9lsi6AOlTgfDQiV5fKiHhguXXv/OtfbS+frKraF60MAgMGNQ+6rk7d2Qi3OIIyV1IZT2jCTpwa7AzjVzq9axHsZVlJ1in2y5cpvIwda5e+LQEW8S2/BLFVzKpzZkzSZSo11kbXx2zfJeSXvsaIVXsSSaiZNUnbVVyvRikN+9w67rfuFJwXj+KVsZS1L8Yfasc5ax7T7A687Jq+5q4uwQ8Jde+japY
  template:
    metadata:
      name: pg-dice-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
