---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-history-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgCndN+9rbjO+427MQheSA+B/Iiww/CO7v6QcNdXCU1u8HQwFA3Q4e5fQCNenZwbDhRrJW/tRhgZwi0Vu8UdxzjAkIkNtwzlObEnkYFsboo4texxZCfwImihwXkXS+loR+URDwD/UTWKEK0O/+u8f42/5RBZraVhzCK5tmIZX2/7xrkOZ+ek4aFd9wMvgCQrU5zN2GBTgkBSsDBU9bUrBUK/n1Q/cDc0uEIQMqVs7qO6uB42PGUOwxHIIKiQKROzM5aUtTEQeTWghY4/lOhIavlxfO9XdV4IN0WGI77tIxv3BSE4rp/en/LdymR9QiV3NBAqjBz6VBxGLEKf4T5D4lL2rkLmEF9UOQFkbWVvEn4rEWOGwa8u3usZMk2uoMSJCrAWxByR92WEmvPRUAyZRC5NTpGUtYRNvxx69bQg1HJs2Y11P3lIt2Em9dZNEVzH7GkrLFjaP8Q3MWCMyIEMyofMLrXl3VAZpKu5pinQNrccPT9kM5OVIc3Z191SDQTjjYGbW9PeMOzxwh9K5sPn2kapC+nqZgNHng0IRQGZxUun16lrr81Upv+8RGWPgY1zpz1HC2nK4ze7qJAImPUgVxvdREaRpo1k1ZFEl/r/6IGtKNVz/eFVhao1Ia89Di1xU0M9YqD2ntXdZuTbjrlpgLLs9IxezI1/annga5CW7k4CR/g4tXiFVnaAL65g8p1TZrhirtnFu7TyIABHIvjNAQAVx/lHZyV0ao1WgMMDH3F5+kn0GfAGQ4oW+yYutRlwanKD87Qo1Xb8Q7OdGG631dtyRA==
    username: AgBPVBryB9h2YBo2zWs6v3a8G3ez+Vq+h9qtgoEPSW/FUkXjaG0sm9fpx2kx2Kg09thiku24hFJC9nxVE6oTJ82Ay7PDu4V44h1eB4mWm1ckdfDtp7FgnmuwOUTosM6t9znyLdF4dxd0RNfzZaKkvzMCaA5UMCQZsZ104vza1G1VW8Wk0RMlwLfRO7L8RwWe2x2HDXYfbbUJMhmxn1Gq3SELVLfLP80C/z9EqjZHjTDIABE9Q2QKEubWry3GZaWB2iI/V2GrQ7KKfvKpudN6LjuB/GKaIVhRQKPZNiNQGeIU+hhbawSI6J4YF+KymVcfshVfer7sN22z2osjF8dYfpGR/nUG/bX8+xAmiZs12nb+rR8NfdNwqI0l62p0bg4ITK9KnVjduK29ze4czb53dPogfdwAGlQANRaubsC/wsYAhjX72EsatFEO+FtO8So5CeKbRmi9W6XUt9dNrGAS7PIZVnR7OGXpdNvLn99ya3J2i+YV78JI/riPDyGSDLJdq/G1PNMs3tORpiIUP3zyw4Df45wSIdGMTXtxNNMfxGUZ9HvP7crHwhPQxZkunqty86jlaCBl4ljnhQePbE4GFBRzhNSjDaJhjCE6VZSKuGo9kRBtiQoPQbHVunGEp80JpD07H0ZuB9GWl/7kq7OnX+d3TS3TZ9IfTijMx+yWWK2ji8WspZgLj+30JuqghzdqiuvWDpfsWwIdU9L/hpD0
  template:
    metadata:
      name: pg-history-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
