---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-identity-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgCZExkJGb2O1AEubBI3/E664fE3wiAm36oDEGfior4TUPyQCmd2fGC//kAh2CXD6h32TmtyJkIK+RfVkPSqpj4kQ0eRID4GYlf2zjaApkr4Aldjr6U05WR8qBjIxHTx+f3cIRGYp7dRY/bo9zQfoVHJmXc61G+ee62gIBMFB4LtqqoSJ8JuywaYiRuk9NGMrMsI6B8b+TrulEMfNTVmTKXgtoBOepdH3lp1XLUSHSEtSwqTS9xE/W6C4rSAp+jTUHrgjjU4BIB6fxnjHEgvG/CRsrzIAOu9HQoaI47aIwzd7ESQBfqu3UGiuKBF4Neajki6XpMoRr4Z/EpkmFutU/aQrMSBHc8a+/L3Ky8inKBllaQHZQ9skLO5taNzaP/VFxzWZl9ToJFTdSrrOsH7FCdFA/OJW0cAkUo5XiQJDZ8oQV4A/aFYTV0AvXsccRrqhnMIrQYYs3wzCF1E6eLz+gHzBtsnUZjq0rJ0ZAoRHLqY3v6d/TALRlbWoJQbQzQ4wiJmkf2cHaMgOwNd+Z3Ma+jG/IqAfLoTI5Cwkg0YJirJW7zskuvZJr/S7bb/5YTAsu2hHZ0yNFLUe0ebGTJNdEaTXsp/Rkgg/4KghTyUWKzSATB9KXQxbPIlpl/dPX5kTWggRFIZj3A85utOxZ4kY+MYXlzHb1W+Tq5MnNkjhoEfk/2222FNJNppAKmev+balrhueP6gQ5qFWsXk1V6YTmG8BaYuazpwCIU+ZwgiUz25C2y5BsVeMf23fXqTZ8JgWdFUn7cdJff4gPlbgHLBUHML/A==
    username: AgCW8RtV5T3MbOBgWDqPyeke2n9+OjaeZnnWLADlaM5z4Nddm1clN23LxjJ4P9ZQn1QbFPG3VleH+duKp6XJWHnOZ3Zs2LjXPjiNKfjlFWWKL8EISaoPvEumrw7lBkwRr477bkUxilGtHLtJchyyx5AWn6egNP3ztuJtxrFuswhL5OxXk9M+qp9rBtXGkzc5SoSYMNFXLJvT4rNbCOpZWmPvkP3vlLTtlIHhsXLTXJZhPomSAwGcgbdfAbhUcPnIvwfeVGee+Cq0GmU+sVyZ3EyExKNziNbh1BANFHXinZF4Lgw+utp4TlbodlXROwmUxT/rhC5tVtN//EC7+pbAGAoFtRm0t0CQbAkfggVddyRllYfz+n+w2jnG7FETyT9s9YCbMFSM79gnLnWY2Dp7w7HLofe/QXhE0mzY1Vw1HDAlOjt3OTWcB7KspzvkPGqS79fysUtDMbWa5wTzf/0iq61dh4oqRXRvGNPOsSmeoinJJWgoXwXjYOwRSwrYzmtt7rrJq6HSIve0J+HagueijiQFXqY/AfqM7KNHztv0X9rmbq9rDfM+1gYLUUYassLrgIWyZ7IPNqdRvzrpo7ydp0mT9kVp4/8BbwyM0uhWMn1JcO4r1N/JfG05xn58vVwQT4og5lhgjkXB7J2alPDTEnMQHnXpk3oaFWqreKkrruER9WGACAh0ezJBVdnpMPkZgZWerUAk/aPwVfX4kVxBGA==
  template:
    metadata:
      name: pg-identity-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
