---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-billing-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgC5Sqt60/Aai+mclhC7ClBIV68e2CnJBAyZhy+XJFxqlDnpxk3fIWeYtk08yIJRNmk4RWYt58vdrLbIsZ0RsIHVvI+HbASjz74On96vEL3R5hP7H8gcCtpVM1vpnhLKHUPw5kF60zuVpcMsFR6IpNuXCcNg6JSZYu896PWAuClokVlG45CNjg89KkoNqDJxHBk/aizHKMHK7DIm/FgHWIA1P+IrynGnHVRN0MYt/jKxltioRqAqr0mG1B5M/T5wvsrxFpOpWZ7aAe4Xk/mUe9sWx5quaOqswe3D27r2sxvQX8P27eVWqEhoh9QRDjY4N0UK9/IjadG3I8YL8/9xKx0YKpekgw3w0Rpq/9hq4Nw5V02vRA/olKCsnyKopadyoMHDlkcaFUbd8LKO2XF/KwnT2tlnFs0QvlzFhh2jx1/6opCtZx43B6xs5hjzA0ac8RR0FFqfLjd8sVjRC1HwwMg2gynukscsfLJpXLscVgXdTIdCxtOfR4FSm7PJcO1aM+dsnyaFcx0KI0UmhrNUJE0fARxZzOo3O6hYQIzUZ7KSWMbB8EGVXk2cGF2cjWAVSh4K2pJc/qR/HlADfeaL4zmhRurXBLDR/2Bf9Z2ykjET6YTAKPOnDcG1Wv/NTcwC3RNoknVkTAnUJPFCOnrubSNfytWdIgr33lrvmF1V2gwDy51h94W9xY2RemBJMOnPgRxQGOvrVlfnh8gf6AdJrmrgy1Tboy1YNtTUErmw1G2ttHlcTsN2Pfp0x5uwG06MZZn6OztiUFn9Qrny/n6ClL/Wsg==
    username: AgCCtavRAIVi0oBdDxJOZgs3JjZ/1WMxf3PGouPSCl7OyldyM0hc36J8lZ4x9/jIpjJZeoZAUSoPPXAu/irZ2RNxhd/lPNx4BtjgmDIYa/1+Onqqu3YbWRhQwQwOYAwzBv/VBaJtPfCKSbzZRaYAEOw0xXNYd1uQigncpltjhsU4s192j+P7cXCw98p6c0NFgvrtVhGYVj789T9mEVDxf4MBpX2o+p05CsXvW/O8xfoyxr/L7LXmLMGARdefIhrRaA+3AsMbrl6iTcJq9rjh9ZRg8q/D+xoZlxqqsBUgvtAbJ5lppc2pWVJMEhWf4/+BLu4/tRYX0N4Q+zCga3FHNcdJjikMdXJLTTrRKM1xzdnVw1cxdkQhcADecOnEKiWbiJWes2+EBQlCMT77JYYC2ogNatu15+/EfW56G4/OWX7FYYWgPoPFaIrwMqgjJOFWiIhFSOE2BvFYm4zNClOPyRYCSRoNACuKvvEmUjkEBKSoNLoy4Er0E60JG0m3WWvLOUwbY2APtOTI0E4D+cD5lqAzhksiiwWSNhCLzhCPpMU7SHsTEfDfT3wMNJdtN0smuLvu7oz25vTBGtO10thKmEj2FTddf2L5qaPJ2GaGrH2G5MJAoESC7rJ5kBdzdueVgBDaAoMyA1Ojrg5DE1Emu/FKER5Z6vmdkic+NLllT2/LEHFqrguWDfp0yjmV/Q5yWrA9PRjE1Lwbp51aWPaf
  template:
    metadata:
      name: pg-billing-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
