---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: realtime-secrets
  namespace: vtt-prod
spec:
  encryptedData:
    INTERNAL_API_SECRET: AgBd2wOIhP6ju4KsN+38iVe3Njloxgb+CyWpYaB9fZlhNaI4uv8DqyGBd2GNx8GMlszzpzOwtlVFn+Fh1be4w2/j0b7JbE3wiQKv7SOnFBABVYYT3C9tqoMVr+iHhsh/zC7M85+KbjWR2L6RDE3ptjIq1el0/F3UG+ekQJdf+jEnGfq8dycfEyEuCvcEiQUevFjsZCo0NIItp2GXDcIbjZs4GeR1hzuEwziF6rV95HTApF6yS7aeZuC72YDDNXfunTTanBt8RK/cphAI9Jiw5/vkF9oj3uyIHSEXQvNhe8gDZ5UounEH50otLWpRcHClpfJx2AbJqSpQdW7fXrm8QWd3c3yFvw+AzrdF1doFje9eZsYsiQ45tAangrBpeTNR2NxUtq2GSj6+MXcsn1IyHDlntN9TN+GIQumlONNCakD31hydvlyEDAqJr3PIMVPG+CHLuCnuv1UG/VHIEoNR/CITHeJWkiEIwdsC5H3/YtM1DJEQ2mOPOFwBAl6h1OVfXCwWmCLnWFlYAfcOsx565abGRqCp+FFDQ/QJJ+DRQX3QraoQA0FMcIxCY5jYCvvbeorp+rRgV3LWrQKPPGl/b7i4OZ/JMQ+2tsZBYh4XoNY2EVwMl9QEHG7cUKKPMn8moVb51SO0xGZy2NUEAl0dzMR1IPMUWUIcH+urkfK8x0IQkh/nTtzYlrTIX/8g0+HNZF5rVH2IhatSsJYGDIEq2xAT3j25qjzKkjMCzoFfr7HW/NHTcWNRlNjy1U4fi2AHpvtcypjF5J/esq+jrw0XqFa3zA==
  template:
    metadata:
      name: realtime-secrets
      namespace: vtt-prod
    type: Opaque
