---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-audio-owner
  namespace: vtt-prod
spec:
  encryptedData:
    password: AgA0H9+ySAb8ywgU7Es3XbqfMSsa8HNHiBR/zI/oJKy08puhlPyRqS+eWJ/kA686avTmVPlXwpHiUUxq7YuElXac+/ItfAZMJmx42QK5QqstKEfPlwWQsc0K7dIkm8Bu134HHVr/pNVXAEcOYS8prOfoGWV/JU4dmasgqkS8n+zp8NFRNu/4tpUwqrZnCMBQcwmrFF0UtHr9LHWIzP0sVND3B28XcJt0kuHcenOuUwN0w/9Xkn646VCglb2cuMqkvXvf34H/MwSkYpGlePE3FCR12FewPqWTMG5ESlupgsV4rkOTVbKVvzy21U/E/ap8poZdJsVjDg8T2dHylTR0c/DWzEgxVyE6giZZH3JbFBWa3HywTuCB4BBPouUQgDKSRFXAyZWpEMjeJHZS/6CzhilToU2YvGVZGuJJLZxKnFlxtFXA+uetGPmXJXJU0kZHpKxoy8ej9Pe9H3yG01UztX90Q2GCiCIxsXKJ3jQolGUYqwRxbmgnAeLsfmhyzLfrqBKzSGJgiGuZ2M/KfJ7eG5304iBxq//fa0Ko35Lz+tqQ3spmSyyVV+MhaPq1R7axMLrcIKXgyWjRJmwSS7mYocBR6JhIKLzI+7z2lYxv9QXVVO8Rj4aowEESONnuDDvCzUA6xv2AjVOpg/yURsjVRO5LcdFwJWYSNX7EcCkvSaJaYIwZPEJ2l4lMiEkpypHdsIW7PokiOPmabGt4yHPnxnpsRZgKaUvAYtPur4PAk4ShwQd8MElOkh8X2v9yM0ymkhZI+ioLO7iFq8lLP6bXnLsVsQ==
    username: AgB4GC0bBGXrumKK5WMItKL1Y8mervIXNWzvApzz/JjKXjjzytqVlTzC4xDVbCJz5ri2cnAf7/nqkjN80+keaSHc6QESMsmVT7Kh09eWN2FWn8XsL1ksM1RC4gtJTVM4kUHGdV8x6/cniMx2L9uP/Jnzi4WKtqP4UK/sC36Ht6W13kO2ps9iryuykzuXycZhe3hgk/BytLVKUYSqMgJtyIIg4qlbwL5Kfd46a6fOIgnLWjqfUWf8Dag4jtOsl/yHSXBbqLyFUteh4Mn0hbRLvADMCaFGlj0tILaEOnZvfsMGoWXGsmUuXNd+XfqoHMupznhf8CmQyEz16pUStTrO3OEYIcBl+h4X+rCLf1NXY2t+MBrw8ySN5uUPd4jWrRILkhRi5U1nqxpmUSNXPXIwE679Poz+j5vmH+qv8+r2Abl6G6EtvT3I0UKFnCyMt1/H9kuQVMIO/T3hL0jWrYsQSlVjUQLE2KJbvZ/Eji0D32XQZ9u0FEv4oPrrjodvJOES2teXeH8xFcXg1iNVm8AS9an9g+MS20wQu7SWlOI6+61cWJRMD1V9Yj2MoyngnY21ltzob7IPM85TLVq8mcLM/S8YEbpUMXeL7NO1cTbulH2fKcObYQbw1xICHxPZx9kQqHlOqSelvnaGFDIyNxdFSTdHL0ab3I6H7SfOIbvJnsZJ/aIi4to1v3QYReqEk/uvLWAmmwBk7vqjrWf9eA==
  template:
    metadata:
      name: pg-audio-owner
      namespace: vtt-prod
    type: kubernetes.io/basic-auth
