/**
 * Données du catalogue intégré, reprises de l'ancienne app
 * (frontend/src/lib/suggested-sounds.ts et legacy/src/lib/suggested-sounds-starwars.ts).
 * [nom, chemin, catégorie]. Les chemins de la bibliothèque par défaut sont sur
 * assets.yner.fr ; ceux de Star Wars sont publiés dans le bucket par
 * scripts/publish-catalog.ts (wav transcodés en m4a).
 */
export type RawEntry = readonly [name: string, path: string, category: string];

export const DEFAULT_SOUNDS: readonly RawEntry[] = [
  ['Forêt de Nuit', 'https://assets.yner.fr/Audio/Foret de_nuit.mp3', 'ambiance'],
  ['Sonnette', 'https://assets.yner.fr/Audio/sonette.mp3', 'ambiance'],
  ['Forêt Paisible', 'https://assets.yner.fr/Audio/foret.mp3', 'nature'],
  ['Rivière', 'https://assets.yner.fr/Audio/eau.mp3', 'nature'],
  ['Feu de Camp', 'https://assets.yner.fr/Audio/feu.mp3', 'nature'],
  ['Insectes de Nuit', 'https://assets.yner.fr/Audio/insecte_nuit.mp3', 'nature'],
  ['Pluie', 'https://assets.yner.fr/Audio/pluit.mp3', 'nature'],
  ['Tonnerre', 'https://assets.yner.fr/Audio/tonere.mp3', 'nature'],
  ['Orage', 'https://assets.yner.fr/Audio/orage.mp3', 'nature'],
  ['Vent Doux', 'https://assets.yner.fr/Audio/vent1.mp3', 'nature'],
  ['Vent Moyen', 'https://assets.yner.fr/Audio/vent2.mp3', 'nature'],
  ['Vent Fort', 'https://assets.yner.fr/Audio/vent3.mp3', 'nature'],
  ['Dragon 1', 'https://assets.yner.fr/Audio/dragon.mp3', 'creatures'],
  ['Dragon 2', 'https://assets.yner.fr/Audio/dragon2.mp3', 'creatures'],
  ['Dragon Ailes', 'https://assets.yner.fr/Audio/dragon_battant_des_ailes.mp3', 'creatures'],
  ['Dragon Dormant', 'https://assets.yner.fr/Audio/dragon_dormant.mp3', 'creatures'],
  ['Gobelin 2', 'https://assets.yner.fr/Audio/ogre3.mp3', 'creatures'],
  ['Rire de Gobelin', 'https://assets.yner.fr/Audio/rire_goblin.mp3', 'creatures'],
  ['Mort de Gobelin', 'https://assets.yner.fr/Audio/goblin_death.mp3', 'creatures'],
  ['Orque 1', 'https://assets.yner.fr/Audio/goblin.mp3', 'creatures'],
  ['Orque 2', 'https://assets.yner.fr/Audio/orgre.mp3', 'creatures'],
  ['Orque 3', 'https://assets.yner.fr/Audio/ogre2.mp3', 'creatures'],
  ['Loup 1', 'https://assets.yner.fr/Audio/loup1.mp3', 'creatures'],
  ['Loup 2', 'https://assets.yner.fr/Audio/loup2.mp3', 'creatures'],
  ['Worg', 'https://assets.yner.fr/Audio/worg.mp3', 'creatures'],
  ['Aboiement', 'https://assets.yner.fr/Audio/aboiement.mp3', 'creatures'],
  ['Monstre', 'https://assets.yner.fr/Audio/monstre.mp3', 'creatures'],
  ['Grognement', 'https://assets.yner.fr/Audio/grognement.mp3', 'creatures'],
  ['Grognement 2', 'https://assets.yner.fr/Audio/grognement2.mp3', 'creatures'],
  ['Rire Grave', 'https://assets.yner.fr/Audio/rire_grave.mp3', 'creatures'],
  ['Foule', 'https://assets.yner.fr/Audio/crowd.mp3', 'foule'],
  ['Taverne', 'https://assets.yner.fr/Audio/tavern.mp3', 'foule'],
  ['Flèches', 'https://assets.yner.fr/Audio/arrows.mp3', 'combat'],
  ['Impact Flèche', 'https://assets.yner.fr/Audio/arrow-impact-87260.mp3', 'combat'],
  [
    'Impact Flèche Précis',
    'https://assets.yner.fr/Audio/a-clean-and-precise-game-style-arrow-impact-1-450238.mp3',
    'combat',
  ],
  ['Dégainer Épée', 'https://assets.yner.fr/Audio/dégainage_épée.mp3', 'combat'],
  ['Épées', 'https://assets.yner.fr/Audio/swords.mp3', 'combat'],
  [
    'Impact Épée Armure',
    'https://assets.yner.fr/Audio/armor-impact-from-sword-393843.mp3',
    'combat',
  ],
  [
    'Impact Hache Métal 1',
    'https://assets.yner.fr/Audio/a-massive-axe-impact-hitting-metal-2-450253.mp3',
    'combat',
  ],
  [
    'Impact Hache Métal 2',
    'https://assets.yner.fr/Audio/a-massive-axe-impact-hitting-metal-4-450252.mp3',
    'combat',
  ],
  ['Impact Bouclier', 'https://assets.yner.fr/Audio/shield_impact-6-382409.mp3', 'combat'],
  ['Coup de poing 1', 'https://assets.yner.fr/Audio/punch.mp3', 'combat'],
  ['Coup de poing 2', 'https://assets.yner.fr/Audio/punch2.mp3', 'combat'],
  ['Coup de poing 3', 'https://assets.yner.fr/Audio/punch3.mp3', 'combat'],
  ['Pas classique', 'https://assets.yner.fr/Audio/fotstep2.mp3', 'pas'],
  ['Pas Nature', 'https://assets.yner.fr/Audio/footsteps.mp3', 'pas'],
  ['Pas discret', 'https://assets.yner.fr/Audio/footsteps-75638.mp3', 'pas'],
  ['Pas Couloir', 'https://assets.yner.fr/Audio/footsteps-in-a-hallway-47842.mp3', 'pas'],
  ['Pas Escaliers', 'https://assets.yner.fr/Audio/footsteps-stairs-slow-106711.mp3', 'pas'],
  [
    'Pas Parquet',
    'https://assets.yner.fr/Audio/footsteps-walking-boots-parquet-1-420135.mp3',
    'pas',
  ],
  ['Pas Lourds', 'https://assets.yner.fr/Audio/heavy_footstep.mp3', 'pas'],
  ['Pas de Monstre', 'https://assets.yner.fr/Audio/monster-footstep-162883.mp3', 'pas'],
  ['Ouverture Porte 1', 'https://assets.yner.fr/Audio/opening door.mp3', 'portes'],
  ['Ouverture Porte 2', 'https://assets.yner.fr/Audio/opening_door.mp3', 'portes'],
  ['Porte Verrouillée 1', 'https://assets.yner.fr/Audio/locked_door.mp3', 'portes'],
  ['Porte Verrouillée 2', 'https://assets.yner.fr/Audio/lockedoor.mp3', 'portes'],
  ['Clés et Porte', 'https://assets.yner.fr/Audio/keys-on-door-and-open-6861.mp3', 'portes'],
  ["Sort d'Air", 'https://assets.yner.fr/Audio/air_spell.mp3', 'magie'],
  ["Sort d'Électricité", 'https://assets.yner.fr/Audio/electric_spell.mp3', 'magie'],
  ['Sort de Feu', 'https://assets.yner.fr/Audio/fire_spell.mp3', 'magie'],
  ['Impact Sort de Feu', 'https://assets.yner.fr/Audio/fire_spell_impact.mp3', 'magie'],
  ['Sort de Glace', 'https://assets.yner.fr/Audio/ice_spell.mp3', 'magie'],
  ['Résurrection', 'https://assets.yner.fr/Audio/resurection.mp3', 'magie'],
  ['Sort Générique', 'https://assets.yner.fr/Audio/spell1.mp3', 'magie'],
  ['Clés', 'https://assets.yner.fr/Audio/keys.mp3', 'actions'],
  ['Corne de brume / Cor', 'https://assets.yner.fr/Audio/horn.mp3', 'actions'],
  ['Pièces de monnaie', 'https://assets.yner.fr/Audio/coins-clinking-sound-410677.mp3', 'actions'],
];

export const DEFAULT_MUSICS: readonly RawEntry[] = [
  ['Chill 1', 'https://assets.yner.fr/Musics/chill/M1.mp3', 'chill'],
  ['Chill 2', 'https://assets.yner.fr/Musics/chill/M2.mp3', 'chill'],
  ['Chill 3', 'https://assets.yner.fr/Musics/chill/M3.mp3', 'chill'],
  ['Chill 4', 'https://assets.yner.fr/Musics/chill/M4.mp3', 'chill'],
  ['Chill 5', 'https://assets.yner.fr/Musics/chill/M5.mp3', 'chill'],
  ['Chill 6', 'https://assets.yner.fr/Musics/chill/M6.mp3', 'chill'],
  ['Chill 7', 'https://assets.yner.fr/Musics/chill/M7.mp3', 'chill'],
  ['Chill 8', 'https://assets.yner.fr/Musics/chill/M8.mp3', 'chill'],
  ['Chill 11', 'https://assets.yner.fr/Musics/chill/M11.mp3', 'chill'],
  ['Chill 12', 'https://assets.yner.fr/Musics/chill/M12.mp3', 'chill'],
  ['Chill 13', 'https://assets.yner.fr/Musics/chill/M13.mp3', 'chill'],
  ['Epic 1', 'https://assets.yner.fr/Musics/epic/M1.mp3', 'epic'],
  ['Epic 2', 'https://assets.yner.fr/Musics/epic/M2.mp3', 'epic'],
  ['Epic 3', 'https://assets.yner.fr/Musics/epic/M3.mp3', 'epic'],
  ['Epic 4', 'https://assets.yner.fr/Musics/epic/M4.mp3', 'epic'],
  ['Epic 5', 'https://assets.yner.fr/Musics/epic/M5.mp3', 'epic'],
  ['Epic 6', 'https://assets.yner.fr/Musics/epic/M6.mp3', 'epic'],
  ['Taverne 1', 'https://assets.yner.fr/Musics/taverne/M1.mp3', 'taverne'],
  ['Taverne 2', 'https://assets.yner.fr/Musics/taverne/M2.mp3', 'taverne'],
  ['Taverne 3', 'https://assets.yner.fr/Musics/taverne/M3.mp3', 'taverne'],
  ['Taverne 4', 'https://assets.yner.fr/Musics/taverne/M4.mp3', 'taverne'],
  ['Taverne 5', 'https://assets.yner.fr/Musics/taverne/M5.mp3', 'taverne'],
];

/** Chemins relatifs au legacy (`/effects/Star Wars/…`, wav). */
export const STARWARS_SOUNDS: readonly RawEntry[] = [
  ['Déplacement Droïde 1', '/effects/Star%20Wars/Droid/Droid%20movement%201.wav', 'droid'],
  ['Déplacement Droïde 2', '/effects/Star%20Wars/Droid/Droid%20movement%202.wav', 'droid'],
  ['Déplacement Droïde 3', '/effects/Star%20Wars/Droid/Droid%20movement%203.wav', 'droid'],
  [
    'Allumage Sabre Laser',
    '/effects/Star%20Wars/Lightsaber/Lightsaber%20Ignition.wav',
    'lightsaber',
  ],
  ['Impact Sabre Laser', '/effects/Star%20Wars/Lightsaber/Lightsaber%20hit.wav', 'lightsaber'],
  [
    'Fouet Sabre Laser 1',
    '/effects/Star%20Wars/Lightsaber/Lightsaber%20whip%201.wav',
    'lightsaber',
  ],
  [
    'Fouet Sabre Laser 2',
    '/effects/Star%20Wars/Lightsaber/Lightsaber%20whip%202.wav',
    'lightsaber',
  ],
  ['Charge Laser', '/effects/Star%20Wars/Lasers/Laser%20power-up.wav', 'lasers'],
  ['Mitrailleuse Laser', '/effects/Star%20Wars/Lasers/Laser%20Machine%20Gun.wav', 'lasers'],
  ['Laser Lourd', '/effects/Star%20Wars/Lasers/Laser%20heavy%20duty.wav', 'lasers'],
  ['Canon Laser', '/effects/Star%20Wars/Lasers/Laser%20cannon.wav', 'lasers'],
  ['Fusil Laser', '/effects/Star%20Wars/Lasers/Laser%20rifle.wav', 'lasers'],
  ['Dialogue Alien 1', '/effects/Star%20Wars/Creature/Alien%20dialogue%201.wav', 'creature'],
  ['Dialogue Alien 2', '/effects/Star%20Wars/Creature/Alien%20dialogue%202.wav', 'creature'],
  [
    'Hydraulique Vaisseau',
    '/effects/Star%20Wars/Spaceship/Spaceship%20Hydraulics.wav',
    'spaceship',
  ],
  ['Survol Vaisseau', '/effects/Star%20Wars/Spaceship/Spaceship%20Fly%20By.wav', 'spaceship'],
  ['Charge Vaisseau 1', '/effects/Star%20Wars/Spaceship/Spaceship%20Charge%201.wav', 'spaceship'],
  ['Charge Vaisseau 2', '/effects/Star%20Wars/Spaceship/Spaceship%20Charge%202.wav', 'spaceship'],
  [
    'Fermeture Porte Vaisseau',
    '/effects/Star%20Wars/Spaceship/Spaceship%20Door%20Shut%20Door%20Shut.wav',
    'spaceship',
  ],
  ['Intérieur Vaisseau', '/effects/Star%20Wars/Spaceship/Spaceship%20Interior.wav', 'spaceship'],
];
