export type SuggestedItem = {
  name: string
  path: string
  category: string
}

// Objets Star Wars — uploadés depuis public/temp_starwars/ vers R2 (voir scripts d'upload one-shot).
// Utilisé par ObjectDrawer.tsx à la place de SUGGESTED_OBJECTS quand le système actif est Star Wars.
export const SUGGESTED_OBJECTS_STARWARS: SuggestedItem[] = [
  // Armes
  { name: 'cannon', path: 'https://assets.yner.fr/items/starwars-armes/cannon.png', category: 'armes' },
  { name: 'cannon-2', path: 'https://assets.yner.fr/items/starwars-armes/cannon-2.png', category: 'armes' },
  { name: 'cannon-generator', path: 'https://assets.yner.fr/items/starwars-armes/cannon-generator.png', category: 'armes' },
  { name: 'cannon-no-battery', path: 'https://assets.yner.fr/items/starwars-armes/cannon-no-battery.png', category: 'armes' },
  { name: 'laser-cannon', path: 'https://assets.yner.fr/items/starwars-armes/laser-cannon.png', category: 'armes' },
  { name: 'unmanned-turret', path: 'https://assets.yner.fr/items/starwars-armes/unmanned-turret.png', category: 'armes' },

  // Environnement
  { name: 'bridge', path: 'https://assets.yner.fr/items/starwars-environnement/bridge.png', category: 'environnement' },
  { name: 'bunker-v1', path: 'https://assets.yner.fr/items/starwars-environnement/bunker-v1.png', category: 'environnement' },
  { name: 'bunker-v1-mossy', path: 'https://assets.yner.fr/items/starwars-environnement/bunker-v1-mossy.png', category: 'environnement' },
  { name: 'bunker-v2-desert', path: 'https://assets.yner.fr/items/starwars-environnement/bunker-v2-desert.png', category: 'environnement' },
  { name: 'bunker-v2-metal', path: 'https://assets.yner.fr/items/starwars-environnement/bunker-v2-metal.png', category: 'environnement' },
  { name: 'bunker-v2-tundra', path: 'https://assets.yner.fr/items/starwars-environnement/bunker-v2-tundra.png', category: 'environnement' },
  { name: 'double-raised-platform-stairs', path: 'https://assets.yner.fr/items/starwars-environnement/double-raised-platform-stairs.png', category: 'environnement' },
  { name: 'elevator-tube', path: 'https://assets.yner.fr/items/starwars-environnement/elevator-tube.png', category: 'environnement' },
  { name: 'elevator-tube-shaft', path: 'https://assets.yner.fr/items/starwars-environnement/elevator-tube-shaft.png', category: 'environnement' },
  { name: 'fighter-platform', path: 'https://assets.yner.fr/items/starwars-environnement/fighter-platform.png', category: 'environnement' },
  { name: 'fighter-platform-raised', path: 'https://assets.yner.fr/items/starwars-environnement/fighter-platform-raised.png', category: 'environnement' },
  { name: 'floor-tile-1', path: 'https://assets.yner.fr/items/starwars-environnement/floor-tile-1.png', category: 'environnement' },
  { name: 'floor-tile-2', path: 'https://assets.yner.fr/items/starwars-environnement/floor-tile-2.png', category: 'environnement' },
  { name: 'imperial-reactor', path: 'https://assets.yner.fr/items/starwars-environnement/imperial-reactor.png', category: 'environnement' },
  { name: 'imperial-reactor-offline', path: 'https://assets.yner.fr/items/starwars-environnement/imperial-reactor-offline.png', category: 'environnement' },
  { name: 'imperial-reactor-on', path: 'https://assets.yner.fr/items/starwars-environnement/imperial-reactor-on.png', category: 'environnement' },
  { name: 'landing-pad-double', path: 'https://assets.yner.fr/items/starwars-environnement/landing-pad-double.png', category: 'environnement' },
  { name: 'landing-pad-single', path: 'https://assets.yner.fr/items/starwars-environnement/landing-pad-single.png', category: 'environnement' },

  // Fournitures
  { name: 'chair-v1', path: 'https://assets.yner.fr/items/starwars-fournitures/chair-v1.png', category: 'fournitures' },
  { name: 'chair-v2', path: 'https://assets.yner.fr/items/starwars-fournitures/chair-v2.png', category: 'fournitures' },
  { name: 'chair-v3', path: 'https://assets.yner.fr/items/starwars-fournitures/chair-v3.png', category: 'fournitures' },
  { name: 'elegant-chair-v1', path: 'https://assets.yner.fr/items/starwars-fournitures/elegant-chair-v1.png', category: 'fournitures' },
  { name: 'elegant-chair-v2', path: 'https://assets.yner.fr/items/starwars-fournitures/elegant-chair-v2.png', category: 'fournitures' },
  { name: 'leader-office-table', path: 'https://assets.yner.fr/items/starwars-fournitures/leader-office-table.png', category: 'fournitures' },
  { name: 'meeting-chair', path: 'https://assets.yner.fr/items/starwars-fournitures/meeting-chair.png', category: 'fournitures' },
  { name: 'meeting-table', path: 'https://assets.yner.fr/items/starwars-fournitures/meeting-table.png', category: 'fournitures' },
  { name: 'office-table', path: 'https://assets.yner.fr/items/starwars-fournitures/office-table.png', category: 'fournitures' },

  // General
  { name: 'conglomerate-datapad', path: 'https://assets.yner.fr/items/starwars-general/conglomerate-datapad.png', category: 'general' },
  { name: 'conglomerate-datapad-2', path: 'https://assets.yner.fr/items/starwars-general/conglomerate-datapad-2.png', category: 'general' },
  { name: 'credit-bronze', path: 'https://assets.yner.fr/items/starwars-general/credit-bronze.png', category: 'general' },
  { name: 'credit-gold', path: 'https://assets.yner.fr/items/starwars-general/credit-gold.png', category: 'general' },
  { name: 'credit-pile-1', path: 'https://assets.yner.fr/items/starwars-general/credit-pile-1.png', category: 'general' },
  { name: 'credit-pile-2', path: 'https://assets.yner.fr/items/starwars-general/credit-pile-2.png', category: 'general' },
  { name: 'credit-pile-bronze', path: 'https://assets.yner.fr/items/starwars-general/credit-pile-bronze.png', category: 'general' },
  { name: 'credit-pile-gold', path: 'https://assets.yner.fr/items/starwars-general/credit-pile-gold.png', category: 'general' },
  { name: 'credit-pile-silver', path: 'https://assets.yner.fr/items/starwars-general/credit-pile-silver.png', category: 'general' },
  { name: 'credit-silver', path: 'https://assets.yner.fr/items/starwars-general/credit-silver.png', category: 'general' },
  { name: 'crystal-black', path: 'https://assets.yner.fr/items/starwars-general/crystal-black.png', category: 'general' },
  { name: 'crystal-blue', path: 'https://assets.yner.fr/items/starwars-general/crystal-blue.png', category: 'general' },
  { name: 'crystal-green', path: 'https://assets.yner.fr/items/starwars-general/crystal-green.png', category: 'general' },
  { name: 'crystal-purple', path: 'https://assets.yner.fr/items/starwars-general/crystal-purple.png', category: 'general' },
  { name: 'crystal-red', path: 'https://assets.yner.fr/items/starwars-general/crystal-red.png', category: 'general' },
  { name: 'crystal-white', path: 'https://assets.yner.fr/items/starwars-general/crystal-white.png', category: 'general' },
  { name: 'fallen-trooper-1', path: 'https://assets.yner.fr/items/starwars-general/fallen-trooper-1.png', category: 'general' },
  { name: 'fallen-trooper-2', path: 'https://assets.yner.fr/items/starwars-general/fallen-trooper-2.png', category: 'general' },
  { name: 'fallen-trooper-3', path: 'https://assets.yner.fr/items/starwars-general/fallen-trooper-3.png', category: 'general' },
  { name: 'fallen-trooper-4', path: 'https://assets.yner.fr/items/starwars-general/fallen-trooper-4.png', category: 'general' },
  { name: 'station-support-beam-1', path: 'https://assets.yner.fr/items/starwars-general/station-support-beam-1.png', category: 'general' },
  { name: 'station-support-beam-2', path: 'https://assets.yner.fr/items/starwars-general/station-support-beam-2.png', category: 'general' },
  { name: 'station-support-beam-3', path: 'https://assets.yner.fr/items/starwars-general/station-support-beam-3.png', category: 'general' },

  // Stations
  { name: 'antenna-black', path: 'https://assets.yner.fr/items/starwars-stations/antenna-black.png', category: 'stations' },
  { name: 'antenna-metal', path: 'https://assets.yner.fr/items/starwars-stations/antenna-metal.png', category: 'stations' },
  { name: 'button-pad-green', path: 'https://assets.yner.fr/items/starwars-stations/button-pad-green.png', category: 'stations' },
  { name: 'button-pad-off', path: 'https://assets.yner.fr/items/starwars-stations/button-pad-off.png', category: 'stations' },
  { name: 'button-pad-red', path: 'https://assets.yner.fr/items/starwars-stations/button-pad-red.png', category: 'stations' },
  { name: 'button-pad-yellow', path: 'https://assets.yner.fr/items/starwars-stations/button-pad-yellow.png', category: 'stations' },
  { name: 'computer-1', path: 'https://assets.yner.fr/items/starwars-stations/computer-1.png', category: 'stations' },
  { name: 'computer-1-broken', path: 'https://assets.yner.fr/items/starwars-stations/computer-1-broken.png', category: 'stations' },
  { name: 'computer-1-off', path: 'https://assets.yner.fr/items/starwars-stations/computer-1-off.png', category: 'stations' },
  { name: 'computer-2', path: 'https://assets.yner.fr/items/starwars-stations/computer-2.png', category: 'stations' },
  { name: 'computer-2-broken', path: 'https://assets.yner.fr/items/starwars-stations/computer-2-broken.png', category: 'stations' },
  { name: 'computer-2-off', path: 'https://assets.yner.fr/items/starwars-stations/computer-2-off.png', category: 'stations' },
  { name: 'conglomerate-datapad', path: 'https://assets.yner.fr/items/starwars-stations/conglomerate-datapad.png', category: 'stations' },
  { name: 'conglomerate-datapad-2', path: 'https://assets.yner.fr/items/starwars-stations/conglomerate-datapad-2.png', category: 'stations' },
  { name: 'duty-station-1', path: 'https://assets.yner.fr/items/starwars-stations/duty-station-1.png', category: 'stations' },
  { name: 'duty-station-mirrored', path: 'https://assets.yner.fr/items/starwars-stations/duty-station-mirrored.png', category: 'stations' },
  { name: 'duty-station-quad', path: 'https://assets.yner.fr/items/starwars-stations/duty-station-quad.png', category: 'stations' },
  { name: 'duty-station-small-1', path: 'https://assets.yner.fr/items/starwars-stations/duty-station-small-1.png', category: 'stations' },
  { name: 'duty-station-small-2', path: 'https://assets.yner.fr/items/starwars-stations/duty-station-small-2.png', category: 'stations' },
  { name: 'duty-station-small-3', path: 'https://assets.yner.fr/items/starwars-stations/duty-station-small-3.png', category: 'stations' },
  { name: 'duty-station-triple', path: 'https://assets.yner.fr/items/starwars-stations/duty-station-triple.png', category: 'stations' },
  { name: 'energy-field-active', path: 'https://assets.yner.fr/items/starwars-stations/energy-field-active.png', category: 'stations' },
  { name: 'energy-field-off', path: 'https://assets.yner.fr/items/starwars-stations/energy-field-off.png', category: 'stations' },
  { name: 'generator-brown', path: 'https://assets.yner.fr/items/starwars-stations/generator-brown.png', category: 'stations' },
  { name: 'generator-brown-metal', path: 'https://assets.yner.fr/items/starwars-stations/generator-brown-metal.png', category: 'stations' },
  { name: 'generator-gray', path: 'https://assets.yner.fr/items/starwars-stations/generator-gray.png', category: 'stations' },
  { name: 'grav-wagon', path: 'https://assets.yner.fr/items/starwars-stations/grav-wagon.png', category: 'stations' },
  { name: 'grav-wagon-2', path: 'https://assets.yner.fr/items/starwars-stations/grav-wagon-2.png', category: 'stations' },
  { name: 'hangar-hose-1', path: 'https://assets.yner.fr/items/starwars-stations/hangar-hose-1.png', category: 'stations' },
  { name: 'hangar-hose-2', path: 'https://assets.yner.fr/items/starwars-stations/hangar-hose-2.png', category: 'stations' },

  // Stockage
  { name: 'cage-gray', path: 'https://assets.yner.fr/items/starwars-stockage/cage-gray.png', category: 'stockage' },
  { name: 'cage-orange', path: 'https://assets.yner.fr/items/starwars-stockage/cage-orange.png', category: 'stockage' },
  { name: 'colony-crate-black', path: 'https://assets.yner.fr/items/starwars-stockage/colony-crate-black.png', category: 'stockage' },
  { name: 'colony-crate-orange', path: 'https://assets.yner.fr/items/starwars-stockage/colony-crate-orange.png', category: 'stockage' },
  { name: 'crate-stack-1', path: 'https://assets.yner.fr/items/starwars-stockage/crate-stack-1.png', category: 'stockage' },
  { name: 'crate-stack-2', path: 'https://assets.yner.fr/items/starwars-stockage/crate-stack-2.png', category: 'stockage' },
  { name: 'crate-stack-3', path: 'https://assets.yner.fr/items/starwars-stockage/crate-stack-3.png', category: 'stockage' },
  { name: 'crate-stack-4', path: 'https://assets.yner.fr/items/starwars-stockage/crate-stack-4.png', category: 'stockage' },
  { name: 'crate-stack-5', path: 'https://assets.yner.fr/items/starwars-stockage/crate-stack-5.png', category: 'stockage' },
  { name: 'crystal-crate-gray', path: 'https://assets.yner.fr/items/starwars-stockage/crystal-crate-gray.png', category: 'stockage' },
  { name: 'crystal-crate-orange', path: 'https://assets.yner.fr/items/starwars-stockage/crystal-crate-orange.png', category: 'stockage' },
  { name: 'garrison-crate-black', path: 'https://assets.yner.fr/items/starwars-stockage/garrison-crate-black.png', category: 'stockage' },
  { name: 'garrison-crate-blue', path: 'https://assets.yner.fr/items/starwars-stockage/garrison-crate-blue.png', category: 'stockage' },
  { name: 'garrison-crate-gray', path: 'https://assets.yner.fr/items/starwars-stockage/garrison-crate-gray.png', category: 'stockage' },
  { name: 'garrison-crate-orange', path: 'https://assets.yner.fr/items/starwars-stockage/garrison-crate-orange.png', category: 'stockage' },
  { name: 'garrison-crate-red', path: 'https://assets.yner.fr/items/starwars-stockage/garrison-crate-red.png', category: 'stockage' },
  { name: 'garrison-crate-white', path: 'https://assets.yner.fr/items/starwars-stockage/garrison-crate-white.png', category: 'stockage' },
  { name: 'small-crate-black', path: 'https://assets.yner.fr/items/starwars-stockage/small-crate-black.png', category: 'stockage' },
  { name: 'small-crate-blue', path: 'https://assets.yner.fr/items/starwars-stockage/small-crate-blue.png', category: 'stockage' },
  { name: 'small-crate-metal', path: 'https://assets.yner.fr/items/starwars-stockage/small-crate-metal.png', category: 'stockage' },
  { name: 'small-crate-orange', path: 'https://assets.yner.fr/items/starwars-stockage/small-crate-orange.png', category: 'stockage' },
  { name: 'small-crate-red', path: 'https://assets.yner.fr/items/starwars-stockage/small-crate-red.png', category: 'stockage' },
  { name: 'standard-crate-black', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-black.png', category: 'stockage' },
  { name: 'standard-crate-gray', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-gray.png', category: 'stockage' },
  { name: 'standard-crate-orange', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-orange.png', category: 'stockage' },
  { name: 'standard-crate-v2-black', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-v2-black.png', category: 'stockage' },
  { name: 'standard-crate-v2-blue', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-v2-blue.png', category: 'stockage' },
  { name: 'standard-crate-v2-gray', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-v2-gray.png', category: 'stockage' },
  { name: 'standard-crate-v2-red', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-v2-red.png', category: 'stockage' },
  { name: 'standard-crate-v2-white', path: 'https://assets.yner.fr/items/starwars-stockage/standard-crate-v2-white.png', category: 'stockage' },
  { name: 'weapons-crate', path: 'https://assets.yner.fr/items/starwars-stockage/weapons-crate.png', category: 'stockage' },
  { name: 'weapons-crate-black', path: 'https://assets.yner.fr/items/starwars-stockage/weapons-crate-black.png', category: 'stockage' },
  { name: 'weapons-crate-blue', path: 'https://assets.yner.fr/items/starwars-stockage/weapons-crate-blue.png', category: 'stockage' },
  { name: 'weapons-crate-orange', path: 'https://assets.yner.fr/items/starwars-stockage/weapons-crate-orange.png', category: 'stockage' },
  { name: 'weapons-crate-red', path: 'https://assets.yner.fr/items/starwars-stockage/weapons-crate-red.png', category: 'stockage' },

  // Tables
  { name: 'hangar-hose-3', path: 'https://assets.yner.fr/items/starwars-tables/hangar-hose-3.png', category: 'tables' },
  { name: 'hangar-hose-4', path: 'https://assets.yner.fr/items/starwars-tables/hangar-hose-4.png', category: 'tables' },
  { name: 'hologram-station-combat', path: 'https://assets.yner.fr/items/starwars-tables/hologram-station-combat.png', category: 'tables' },
  { name: 'hologram-station-off', path: 'https://assets.yner.fr/items/starwars-tables/hologram-station-off.png', category: 'tables' },
  { name: 'hologram-station-planet', path: 'https://assets.yner.fr/items/starwars-tables/hologram-station-planet.png', category: 'tables' },
  { name: 'hologram-station-planet-attack', path: 'https://assets.yner.fr/items/starwars-tables/hologram-station-planet-attack.png', category: 'tables' },
  { name: 'hologram-station-sd', path: 'https://assets.yner.fr/items/starwars-tables/hologram-station-sd.png', category: 'tables' },
  { name: 'lamppost', path: 'https://assets.yner.fr/items/starwars-tables/lamppost.png', category: 'tables' },
  { name: 'lamppost-effect', path: 'https://assets.yner.fr/items/starwars-tables/lamppost-effect.png', category: 'tables' },
  { name: 'pylon-v1-black', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v1-black.png', category: 'tables' },
  { name: 'pylon-v1-brown', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v1-brown.png', category: 'tables' },
  { name: 'pylon-v1-metal', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v1-metal.png', category: 'tables' },
  { name: 'pylon-v2-black', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v2-black.png', category: 'tables' },
  { name: 'pylon-v2-brown', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v2-brown.png', category: 'tables' },
  { name: 'pylon-v2-metal', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v2-metal.png', category: 'tables' },
  { name: 'pylon-v3-black', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v3-black.png', category: 'tables' },
  { name: 'pylon-v3-brown', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v3-brown.png', category: 'tables' },
  { name: 'pylon-v3-metal', path: 'https://assets.yner.fr/items/starwars-tables/pylon-v3-metal.png', category: 'tables' },

  // Vehicules
  { name: 'advanced-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/advanced-bluish.png', category: 'vehicules' },
  { name: 'advanced-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/advanced-gray.png', category: 'vehicules' },
  { name: 'big-walker-clean', path: 'https://assets.yner.fr/items/starwars-vehicules/big-walker-clean.png', category: 'vehicules' },
  { name: 'big-walker-dirty', path: 'https://assets.yner.fr/items/starwars-vehicules/big-walker-dirty.png', category: 'vehicules' },
  { name: 'bike-black', path: 'https://assets.yner.fr/items/starwars-vehicules/bike-black.png', category: 'vehicules' },
  { name: 'bike-blue', path: 'https://assets.yner.fr/items/starwars-vehicules/bike-blue.png', category: 'vehicules' },
  { name: 'bike-brown', path: 'https://assets.yner.fr/items/starwars-vehicules/bike-brown.png', category: 'vehicules' },
  { name: 'bike-green', path: 'https://assets.yner.fr/items/starwars-vehicules/bike-green.png', category: 'vehicules' },
  { name: 'bike-metal', path: 'https://assets.yner.fr/items/starwars-vehicules/bike-metal.png', category: 'vehicules' },
  { name: 'bike-white', path: 'https://assets.yner.fr/items/starwars-vehicules/bike-white.png', category: 'vehicules' },
  { name: 'bomber-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/bomber-bluish.png', category: 'vehicules' },
  { name: 'bomber-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/bomber-gray.png', category: 'vehicules' },
  { name: 'cargo-shuttle-flying', path: 'https://assets.yner.fr/items/starwars-vehicules/cargo-shuttle-flying.png', category: 'vehicules' },
  { name: 'cargo-shuttle-landed', path: 'https://assets.yner.fr/items/starwars-vehicules/cargo-shuttle-landed.png', category: 'vehicules' },
  { name: 'corvette', path: 'https://assets.yner.fr/items/starwars-vehicules/corvette.png', category: 'vehicules' },
  { name: 'crashed-cargo-shuttle', path: 'https://assets.yner.fr/items/starwars-vehicules/crashed-cargo-shuttle.png', category: 'vehicules' },
  { name: 'crashed-cruiser', path: 'https://assets.yner.fr/items/starwars-vehicules/crashed-cruiser.png', category: 'vehicules' },
  { name: 'crashed-dropship', path: 'https://assets.yner.fr/items/starwars-vehicules/crashed-dropship.png', category: 'vehicules' },
  { name: 'crashed-shuttle', path: 'https://assets.yner.fr/items/starwars-vehicules/crashed-shuttle.png', category: 'vehicules' },
  { name: 'crashed-transport', path: 'https://assets.yner.fr/items/starwars-vehicules/crashed-transport.png', category: 'vehicules' },
  { name: 'cruiser', path: 'https://assets.yner.fr/items/starwars-vehicules/cruiser.png', category: 'vehicules' },
  { name: 'cruiser-dirty', path: 'https://assets.yner.fr/items/starwars-vehicules/cruiser-dirty.png', category: 'vehicules' },
  { name: 'defender-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/defender-bluish.png', category: 'vehicules' },
  { name: 'defender-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/defender-gray.png', category: 'vehicules' },
  { name: 'fighter-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/fighter-bluish.png', category: 'vehicules' },
  { name: 'fighter-chassi', path: 'https://assets.yner.fr/items/starwars-vehicules/fighter-chassi.png', category: 'vehicules' },
  { name: 'fighter-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/fighter-gray.png', category: 'vehicules' },
  { name: 'interceptor-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/interceptor-bluish.png', category: 'vehicules' },
  { name: 'interceptor-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/interceptor-gray.png', category: 'vehicules' },
  { name: 'juggernaut-dirty', path: 'https://assets.yner.fr/items/starwars-vehicules/juggernaut-dirty.png', category: 'vehicules' },
  { name: 'juggernaut-tank', path: 'https://assets.yner.fr/items/starwars-vehicules/juggernaut-tank.png', category: 'vehicules' },
  { name: 'juggernaut-weathered', path: 'https://assets.yner.fr/items/starwars-vehicules/juggernaut-weathered.png', category: 'vehicules' },
  { name: 'old-gunship-metal', path: 'https://assets.yner.fr/items/starwars-vehicules/old-gunship-metal.png', category: 'vehicules' },
  { name: 'old-gunship-worn-paint', path: 'https://assets.yner.fr/items/starwars-vehicules/old-gunship-worn-paint.png', category: 'vehicules' },
  { name: 'patrol-bike', path: 'https://assets.yner.fr/items/starwars-vehicules/patrol-bike.png', category: 'vehicules' },
  { name: 'patrol-transport', path: 'https://assets.yner.fr/items/starwars-vehicules/patrol-transport.png', category: 'vehicules' },
  { name: 'prototype-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/prototype-bluish.png', category: 'vehicules' },
  { name: 'prototype-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/prototype-gray.png', category: 'vehicules' },
  { name: 'reaper-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/reaper-bluish.png', category: 'vehicules' },
  { name: 'reaper-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/reaper-gray.png', category: 'vehicules' },
  { name: 'shuttle-flying', path: 'https://assets.yner.fr/items/starwars-vehicules/shuttle-flying.png', category: 'vehicules' },
  { name: 'shuttle-parked', path: 'https://assets.yner.fr/items/starwars-vehicules/shuttle-parked.png', category: 'vehicules' },
  { name: 'small-proto-walker-clean', path: 'https://assets.yner.fr/items/starwars-vehicules/small-proto-walker-clean.png', category: 'vehicules' },
  { name: 'small-proto-walker-dirty', path: 'https://assets.yner.fr/items/starwars-vehicules/small-proto-walker-dirty.png', category: 'vehicules' },
  { name: 'small-proto-walker-weathered', path: 'https://assets.yner.fr/items/starwars-vehicules/small-proto-walker-weathered.png', category: 'vehicules' },
  { name: 'small-walker-clean', path: 'https://assets.yner.fr/items/starwars-vehicules/small-walker-clean.png', category: 'vehicules' },
  { name: 'small-walker-dirty', path: 'https://assets.yner.fr/items/starwars-vehicules/small-walker-dirty.png', category: 'vehicules' },
  { name: 'small-walker-weathered', path: 'https://assets.yner.fr/items/starwars-vehicules/small-walker-weathered.png', category: 'vehicules' },
  { name: 'striker-bluish', path: 'https://assets.yner.fr/items/starwars-vehicules/striker-bluish.png', category: 'vehicules' },
  { name: 'striker-gray', path: 'https://assets.yner.fr/items/starwars-vehicules/striker-gray.png', category: 'vehicules' },
  { name: 'tank-clean', path: 'https://assets.yner.fr/items/starwars-vehicules/tank-clean.png', category: 'vehicules' },
  { name: 'tank-dirty', path: 'https://assets.yner.fr/items/starwars-vehicules/tank-dirty.png', category: 'vehicules' },
  { name: 'tank-weathered', path: 'https://assets.yner.fr/items/starwars-vehicules/tank-weathered.png', category: 'vehicules' },
  { name: 'transport-clean', path: 'https://assets.yner.fr/items/starwars-vehicules/transport-clean.png', category: 'vehicules' },
  { name: 'transport-dirty', path: 'https://assets.yner.fr/items/starwars-vehicules/transport-dirty.png', category: 'vehicules' },
  { name: 'transport-weathered', path: 'https://assets.yner.fr/items/starwars-vehicules/transport-weathered.png', category: 'vehicules' },
  { name: 'transport-weathered-blastermarks', path: 'https://assets.yner.fr/items/starwars-vehicules/transport-weathered-blastermarks.png', category: 'vehicules' },
  { name: 'troop-shuttle-flying', path: 'https://assets.yner.fr/items/starwars-vehicules/troop-shuttle-flying.png', category: 'vehicules' },
  { name: 'troop-shuttle-landed', path: 'https://assets.yner.fr/items/starwars-vehicules/troop-shuttle-landed.png', category: 'vehicules' },
  { name: 'troop-transport', path: 'https://assets.yner.fr/items/starwars-vehicules/troop-transport.png', category: 'vehicules' },
  { name: 'walker-chassi', path: 'https://assets.yner.fr/items/starwars-vehicules/walker-chassi.png', category: 'vehicules' },
]
